### ISSUE TITLE
Bastila showing all four visions

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#10]
Making it to where Bastila gives all four post-vision speeches would be nice, and allows you to view any of the visions after the fourth, and not just the first three (the game expects you to beat each planet as soon as you land on it, so if you visit the fourth planet before getting the third Star Map, you have the vision and then just spawn in front of her; it evidently expects her to already be captured by that point. Likewise, if you ask her to show you the vision again, she won't be able to show the fourth). K1R has this fix.

**Comment by DarthParametric** [comment]
Requires submitting a request to Fair Strides for use of the K1R content. Sounds like a job for @Mako88

**Comment by Mako88** [comment]
I talked to FairStrides and got permission:

![image](https://user-images.githubusercontent.com/4147635/52006281-5f587000-2491-11e9-8ef9-bd615e754e6f.png)

**Comment by DarthParametric** [comment]
So it would seem the fix consists of adding a new Entry to ebo_bast_vision.dlg in the Ebon Hawk module, which has an added conditional
```
int StartingConditional() {
	int int1 = (GetGlobalNumber("Ebon_Vision") == 3);
	return int1;
}
```
And fires a new script
```
void main() {
	SetGlobalNumber("Ebon_Vision", 3);
}
```
I am assuming that alone is sufficient.
