### ISSUE TITLE
Dantooine Star Map Ruins - Conversation/cutscene issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#105]
- [ ] ~There's a delay between the door opening shot and the player and Bastila being jumped next to the droid. It should be done in the opening shot.~ Too much screwiness doing that
- [x] The Overseer droid's line about Nemo being unworthy needs a delay before switching to the camera angle showing the body.
- [x] Bastila's line after the droid's talking about Nemo is off-screen. The camera remains on Nemo. I don't think his corpse is interesting enough to warrant that much screen time.
- [x] When opening the Star Map door, there's a cutscene showing the player enter the room, then you have to manually walk forwards a few meters to trigger the cutscene of the Star Map opening. It should just be merged into one continuous scene.

**Comment by DarthParametric** [comment]
- [ ] Despite the previous changes, Bastila failed to obey and walk to her intended mark during the conversation with the overseer droid, instead staying where she was when the cutscene was triggered.

**Comment by DarthParametric** [comment]
This appears to be another case of a problem that occurred on XP that I cannot replicate on 10, like with the Murder Mystery corpse selection icon. Even when clicking through all the lines, Bastila still ended up walking into position as expected (albeit at high speed, which was humorous). I don't know why it would fail on XP though.

**Comment by DarthParametric** [comment]
- [ ] Might need to change all of Bastila and the Player's lines to set the droid as listener to prevent side-on camera angle 1s.
- [ ] Nemo's camera angle needs adjustment.

**Comment by DarthParametric** [comment]
@auri0n - It's not perfect, but try this:

[Dan_Ruins_Droid_Convo_Adjustment.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3772288/Dan_Ruins_Droid_Convo_Adjustment.zip)

The player will look at Bastila on any node directly after one of her interjections, but there's no real fix for that apart from completely rebuilding the DLG as I said above, slipping in empty nodes in between with the droid as the speaker. The other alternative would be to lock the player's head orientation, but then you'd have them just blankly staring straight ahead the entire conversation, which I'm not sure is an improvement.

**Comment by auri0n** [comment]
I'd say that's an improvement, thanks for the quick fix.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] Both the droid and star map scenes/convos need a ClearAllEffects on the player/Bastila to strip off Force Speed.
