### ISSUE TITLE
Dantooine Matale Grounds - Mando unintentionally switching to melee weapon

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#111]
During the "wife and children" scene, the Mando killing the civilian equips a vibroblade half way through shooting him, presumably due to anti-fist fighting scripts. This needs to be switch back to vanilla so that he keeps his blaster equipped.

**Comment by JCarter426** [comment]
Hmm, I don't recall anything in the community patch that would affect that.
A sure way to avoid the issue though would be to remove the vibroblade from his inventory, then script it back in at the end of the cutscene.

**Comment by DarthParametric** [comment]
Yeah I can't see anything in there. The Mando looks to be dan14ab_mand01.utc with OUD k_pdan_mand55 and OS k_pdan_mand52 (global script). It doesn't seem like he should be affected, but I don't remember ever encountering that issue before. 

This is the script that fires to execute the attack:

```
void main() {
	
	object oVictim = GetObjectByTag("dan14_victim", 0);
	object oMando = GetObjectByTag("dan14ab_mand01", 0);
	effect efHit = EffectAssuredHit();
	
	ChangeToStandardFaction(oVictim, STANDARD_FACTION_FRIENDLY_1);
	ChangeToStandardFaction(oMando, STANDARD_FACTION_FRIENDLY_2);
	ActionPauseConversation();
	ApplyEffectToObject(DURATION_TYPE_TEMPORARY, efHit, oMando, 5.0);
	ActionAttack(oVictim, FALSE);
}
```

**Comment by DarthParametric** [comment]
Proposed solution. 

Step 1, OUD event that triggers convo modified to remove sword:

```
void main() {

	int int1 = GetUserDefinedEventNumber();
	
	switch (int1)
	{
		case 100:
			{
				object oPC = GetFirstPC();
				object oItem = GetFirstItemInInventory(OBJECT_SELF);
				
				ActionWait(3.0);
				
				while (GetIsObjectValid(oItem) == TRUE)
					{
						if (GetTag(oItem) == "g_w_vbroswrd01")
							{
								DestroyObject(oItem);
							}
						oItem = GetNextItemInInventory(OBJECT_SELF);
					}
				
				ActionStartConversation(oPC, "dan14ab_cut01", FALSE, CONVERSATION_TYPE_CINEMATIC, TRUE, "", "", "", "", "", "");
			}
			break;
```

Step 2, script that fires at the end of the DLG to turn group hostile modified to add it back:

```
void main() {
	
	object oMando = GetObjectByTag("dan14ab_mand01", 0);
	object oDuro1 = GetObjectByTag("dan14ab_duros01", 0);
	object oDuro2 = GetObjectByTag("dan14ab_duros02", 0);
	object oDuro3 = GetObjectByTag("dan14ab_duros03", 0);
	
	CreateItemOnObject("g_w_vbroswrd01", oMando, 1);
	
	ChangeToStandardFaction(oMando, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(oDuro1, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(oDuro2, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(oDuro3, STANDARD_FACTION_HOSTILE_1);
}
```

**Comment by DarthParametric** [comment]
I'm not sure if this is a consequence of the changes we made or not, but the Mando in question seems to do nothing when combat starts if he isn't targeted first. He'll just stand there and watch you slaughtering his friends.
