### ISSUE TITLE
Tatooine Eastern Dune Sea - Blurry texture at cave entrance

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#117]
The mouth of the Krayt Dragon cave has a strip of polys textured to transition between the dark stone of the cave interior and a lighter brown rock (mostly obscured by another strip of polys graduating to the sand texture via an alpha mask). There is some heavy texture stretching on this strip, causing noticeable bluring of the texture and a harsh seam due to a UV scale mismatch compared to the rest of the interior.

![Tat_Krayt_Cave_Entrance](https://user-images.githubusercontent.com/46890653/57566400-5cb1d300-740f-11e9-9de7-d2ca3f96016c.jpg)

**Comment by DarthParametric** [comment]
![Tatooine_Krayt_Cave_Entrance_Adjustment_After](https://user-images.githubusercontent.com/46890653/57567026-8fab9500-7416-11e9-95b6-91af12a12f64.jpg)

Before and after comparison - http://screenshotcomparison.com/comparison/135445

**Comment by ebmar** [comment]
The end-result is ***awesome***! A definite improvement from the former. Nice catch in the first place!
