### ISSUE TITLE
Kashyyyk Landing Pad - Eli/Matton conversation issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#118]
- [x] Eli and Matton both wear the same green commoner clothes variation.
- [x] In the initial conversation, Matton's line about his crew disappearing is off-screen.
- [x] When handing over the droid head, there are various facing issues.
- [x] You don't _actually_ hand over the droid head. It stays in your inventory until it is destroyed by the OnEnter. Should remove it when showing Matton.
- [x] If you push Matton to kill Eli, the convo ends and he kills Eli in normal play. Conversation with Matton must be then be reinitiated manually. It seems like this should be merged/linked into one continuous scene.
- [x] Ditto if you let Eli run away (per JC below).
- [x] If you let Eli run away, Matton's line after companion interjections is spoken off-screen.
- [x] If Eli tries to leave but can't get past the party, the game softlocks with a permanent fade-to-black (reported by @Salk73 in #228 )
- [x] If you push Matton to kill Eli, the dialogue is inconsistent without Zaalbar in the party, requires added Eli line (reported by @Salk73 in #228 )
- [x] Matton starts with his blaster equipped (per JC below).

**Comment by JCarter426** [comment]
I noticed Matton has his blaster out the whole time, as well. Should unequip on spawn and only equip if he kills Eli.

As for the clothing issue, there is an appearance with Eli's head and the Czerka uniform. A guy wandering around the module already has it, but that can't be helped barring a full NPC fix that someone ought to do one of these days.

**Comment by DarthParametric** [comment]
Here's a WIP of stitching the Eli and Matton conversations together when knocking Eli on the head. Also changed Matton's clothes and added in the extra line for Eli, as per @Salk73's suggestion. Also threw in a TALK_FORCEFUL for @ebmar.

https://www.youtube.com/watch?v=fSE7iXt8Oh8

**Comment by Salk73** [comment]
Looks already good to me, DP.

Good job.

**Comment by DarthParametric** [comment]
Here's the merged scenes when you let Eli go. Not sure if Eli needs a static camera. Doesn't seem like dynamic cameras will show any other angle.

https://www.youtube.com/watch?v=G6bVN8YXHGo

**Comment by Salk73** [comment]
DP,

Does Matton resume conversation with the Player after shooting Eli from a different spot in the edited version? I like the edited version better up to when the dialogue resumes. At that point I feel like the other camera is much more appropriate.

Cool job done there though.

**Comment by DarthParametric** [comment]
No, nothing changed aside from the camera angle. It's easy enough to switch between multiple cameras if needed, but at the moment I just wanted to get a placeholder in and focus on getting the scene functioning as intended before getting too obsessed with aesthetics. I'm just about to push some final changes that clean up some other aspects of the scene, like facing, off-screen lines, speaker/listener issues, and some undesirable dynamic camera angles.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] If you encourage Matton to kill Eli and then push him to the DS route in the following conversation, Juhani's interjection is off-screen.
