### ISSUE TITLE
Kashyyyk Wookiee Chieftan's Hut - Post-Star Map conversation issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#121]
- [x] During the return entrance scene, the party needs a pre-jump and aligned destinations to prevent party members bumping into each other while walking.
- [x] During the return entrance scene, the camera can zoom into a party member's head (at least in DS route). Might need a new static camera.
- [x] Various facing issues with Chuundar when switching back and forth between Zaalbar and the player.
- [x] Chuundar has an equipped weapon. This clips through player when he approaches to give them the blade of Bacca's sword in the DS ending. It might be better to unequip him and only have him re-equip on going hostile. Edit: Alternatively this could be fixed simply by editing k_pkas_takeblade and changing the `ActionTakeItem`.

Added 2019-11-10:
- [x] This is during the first visit, but since it is the same module and DLG, if you leave Zaalbar behind and then choose the "You work with Janos" reply then Zaalbar's interjection faces the player, not Chuundar. Chuundar's subsequent two entries have a camera skip between them, presumably due to switching between the player and Zaalbar.

Added 2021-01-12:
- [x] If you side with Freyyr, there are also multiple facing issues during his post-fight convo due to a lack of speaker/listener tags.
- [x] If you give Freyyr the sword blade and have him appear in the hall, no matter who you side with the post-fight conversation will start with everyone standing wherever they were when combat ended. This can result in lots of camera issues, including clipping through NPC bodies if they are in the way. The post-fight conversation is initiated via Chuundar/Freyyr's UserDefine script.

**Comment by JCarter426** [comment]
I noticed Matton has his blaster out the whole time, as well. Should unequip on spawn and only equip if he kills Eli.

As for the clothing issue, there is an appearance with Eli's head and the Czerka uniform. A guy wandering around the module already has it, but that can't be helped barring a full NPC fix that someone ought to do one of these days.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] Post-resolution when siding with Freyyr, he is left facing off to the side once stunt Zaalbar is destroyed. Needs a facing towards the PC in the party selection screen script.
