### ISSUE TITLE
Kashyyyk Lower Shadowlands - Star Map closes prematurely

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#123]
Because Jolee starts yapping at you as soon as the conversation with the computer ends, the Star Map typically closes before you are free to run around. It seems like there can be some glitches with it. I have had it stuck with the arms open and the central ball in mid-air, but all the VFX stopped. Seems like the best approach would be to extend the delay time before commanding it to play the shutdown animation. Relevant section from k_pkas_openmap that is fired by kas25_comp_01.dlg:

```
int sub4(int intParam1) {
	if ((intParam1 == 0)) {
		return ANIMATION_PLACEABLE_ANIMLOOP01;
	}
	else {
		if ((intParam1 == 10)) {
			return ANIMATION_PLACEABLE_ANIMLOOP02;
		}
		else {
			if ((intParam1 == 20)) {
				return ANIMATION_PLACEABLE_ANIMLOOP03;
			}
			else {
				if ((intParam1 == 30)) {
					return ANIMATION_PLACEABLE_ANIMLOOP04;
				}
				else {
					if ((intParam1 == 40)) {
						return ANIMATION_PLACEABLE_ANIMLOOP06;
					}
				}
			}
		}
	}
	return (-1);
}

void sub3() {
	int nGlobal = GetGlobalNumber("K_STAR_MAP");
	int nLocalBool = GetLocalBoolean(OBJECT_SELF, 10);
	float float1 = 30.0;
	if ((nLocalBool == 0)) {
		ActionPlayAnimation(ANIMATION_PLACEABLE_ACTIVATE, 1.0, 0.0);
		ActionPlayAnimation(sub4(nGlobal), 1.0, 0.0);
		if ((nGlobal == 40)) {
			float1 = 60.0;
		}
		DelayCommand(float1, ActionPlayAnimation(ANIMATION_PLACEABLE_DEACTIVATE, 1.0, 0.0));
	}
}
```

**Comment by JCarter426** [comment]
Yeah, as I recall the model can bug out if it's scripted to close when it's in the middle of another animation. Probably needs to be timed for another full loop before closing.

**Comment by DarthParametric** [comment]
The animation length for ANIMLOOP02/3/4 is 7.86667 seconds. ANIMLOOP06 is 46.6667 seconds. So I'd suggest the values for `float1` in `sub3` need to be changed to something like 62.94 and 93.34 seconds.
