### ISSUE TITLE
Manaan East Central - Hulas: a Duros or a Rodians?

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#125]
Apparently, Hulas `n_duros001.utc` on Manaan East Central `manm26ae` had mixed personalities. He appeared as Rodian despite his `Duros` Tag and also the `Duros` SS reference. But more importantly, this -

> You have forgotten my name? Knowledge is power, but information is useless if you do not make a point to remember it. I am Hulas, a traveler from the world of Duro.

That was from `Entry 1 (Parent: Reply 1)` of his DLG `man26_hulas.dlg`. Perhaps to change his appearance to `Duros` would suit him better? Though that means his `Sound` ResRef on the DLG also have to be changed to Duros, as its current is Rodian.

**Comment by DarthParametric** [comment]
I would guess they changed it because a Rodian suited his character better. A more suitable resolution might be changing the dialogue line to remove the Duro reference. Although that would involve a TLK edit, which would presumably make JC's eye twitch.

**Comment by ebmar** [comment]
> ...more suitable resolution might be changing the dialogue line to remove the Duro reference... though that would involve a TLK edit, which would presumably make JC's eye twitch.

Spot on! Hahah. Well, from a [trusted source](https://starwars.fandom.com/wiki/Duro/Legends) it could very well be that Rodians came from the `world of Duro` also. Though, another minor reason to have him changed to Duros was because there're already **three** other Rodians on the module.

**Comment by DarthParametric** [comment]
Sure, you could potentially have Rodians being born on half the planets in the galaxy probably. But it seems to me like making it either specifically Rodia, or some more generic multi-species planet (like Coruscant, Corellia, etc.) would make more sense to the average player.

**Comment by ebmar** [comment]
> ...making it either specifically **Rodia**, or some more generic multi-species planet (like Coruscant, Corellia, etc.) would make more sense to the average player.

_**That's it**_ - I want one of them fixes, soon! Lol.

**Comment by DarthParametric** [comment]
I'm sure you can draft up an ini config for it then.

**Comment by ebmar** [comment]
Using `append.tlk`? Because I don't know if there's any command to patch the existing TLK.

**Comment by DarthParametric** [comment]
Yes. It would require a new appended TLK string, and the DLG node would need to be pointed to the new StrRef token.

**Comment by ebmar** [comment]
> ...so your token would need to be 21.

Cool - how about this: [Hulas_as_Rodia.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3169021/Hulas_as_Rodia.zip)

I'm not sure about the setup, as it haven't been tested. Here's a glimpse of what's inside:
```
[TLKList]
StrRef21=0
StrRef22=1

...

[man26_hulas.dlg]
!Destination=modules\manm26ae.mod
EntryList\1\Text(strref)=StrRef21
EntryList\1\SoundExists=1
EntryList\148\Text(strref)=StrRef22
EntryList\148\SoundExists=1
```

**Comment by DarthParametric** [comment]
It would need to be

```
[TLKList]
StrRef21=21
StrRef22=22
```

And your append.tlk would need to be using those values. Although we'd have to merge it manually into our append.tlk anyway, so for future reference I would suggest just pasting the string/s directly. Something like:

```
ID=20
SOUND=n_grodian_coml2
STRING=You have forgotten my name? Knowledge is power, but information is useless if you do not make a point to remember it. I am Hulas, a traveler from the world of Rodia

ID=21
SOUND=n_grodian_quel
STRING=A name? There is power in names, yet in the end a name alone means less than nothing. I am Hulas, a traveler from the world of Rodia. And what is your name, human?
```

**Comment by ebmar** [comment]
Ah - much thanks for the elaboration/suggestion! All noted for future reference.

**Comment by JCarter426** [comment]
I vote for changing him to a Duros. We already changed a few species for similar reasons. Only issue is all his VO would have to be swapped out for Duros VO, which I believe has to done manually for each node in K1).

**Comment by DarthParametric** [comment]
That would be far more invasive, and presumably counter to developer intent, since, as I said above, it seems likely they purposely changed him to a Rodian because it suit the character better. I guess we need @Mako88 to weigh in on it.

**Comment by jackerman88** [comment]
Hmm this one is tough...I say we keep him as a Rodian, mainly because there aren’t any Duros bodies that have clothing suited to an assassin (which I would guess may be why they switched him to a Rodian in the first place).

**Comment by Mako88** [comment]
Hmm this one is tough...I say we keep him as a Rodian, mainly because there aren’t any Duros bodies that have clothing suited to an assassin (which I would guess may be why they switched him to a Rodian in the first place).

**Comment by DarthParametric** [comment]
Putting this to bed as beyond the scope of the Community Patches. @ebmar can look at making it as a standalone mod perhaps.

**Comment by ebmar** [comment]
> ...can look at making it as a standalone mod perhaps.

Sure thing! With `GFF2XML` converter on hand, batch replacing the `Sound` wouldn't be much a hassle now [going the Duros' way].
