### ISSUE TITLE
General - Overgained Tach's Grunt/Battlecry

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#127]
I think Tach's grunt/battlecry `streamsounds\c_tach_bat1.wav` heard on the _Shadowlands_ were bit too overgained. The fact that they're frequently heard only make it worse. I had a fix that I use myself which perhaps could act as an improvement: [c_tach_bat1_dbFix.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3176662/c_tach_bat1_dbFix.zip)
What I did is to lower its `master` for about ~2dB.

**Comment by Mako88** [comment]
I like this as a Tier 2/3 fix.

**Comment by DarthParametric** [comment]
It would go under `Annoyance Fixes`, which is currently Tier 2 (but arguably should be Tier 3).

**Comment by Salk73** [comment]
I checked it too and I agree with DP.

We need to lower the volume further.

**Comment by DarthParametric** [comment]
Per AFP's robot ears, the adjustment has been changed to -10dB. Testing in-game seems like it is sufficiently reduced to not be ear splitting whilst still retaining the original developer intent. Further reduction (or outright removal) is the province of standalone mods.

[c_tach_bat1_-10dB.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3445358/c_tach_bat1_-10dB.zip)
