### ISSUE TITLE
Manaan - Black line in Ahto City backdrop

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#128]
I'm experiencing a slight graphical issue with Ahto City backdrop which there's a visible black dotted line on/above the vanilla `LMA_bboard01` texture.
![LMA_bboard01_Issue](https://user-images.githubusercontent.com/50026566/57693185-ce3d8b80-7672-11e9-98ac-78dca2a957cd.jpg)
There seem to be a fix for this by creating a `LMA_bboard01.txi` with this parameters init -
```
blending punchthrough
clamp 3
```
and simply put it to the _Override_ folder. I'm not invented the parameters -so does deserve any credits- as I reiterate them from **MadDerp**'s "[Widescreen Cockpit and Racing Track on Manaan](https://www.nexusmods.com/kotor/mods/1211)". Though I guess K1CP could re-implement it as how they see fit.

**Comment by DarthParametric** [comment]
I'm not sure if this is really necessary as a forced fix when many people don't get the problem in the first place. I'd say release it as a standalone mod for those that want/need it.

**Comment by ebmar** [comment]
> ...not sure if this is really necessary as a forced fix when many people don't get the problem in the first place.

Sure, that's what I thought after reading threads about `clamp`/similar stuffs and hearing that you're not getting one.

> I'd say release it as a standalone mod...

Thanks for the input - though I don't think that's necessary as [there's one already](https://www.nexusmods.com/kotor/mods/1211).

**Comment by DarthParametric** [comment]
Does it actually fix this specific problem? Is that same texture used on the swoop track?

**Comment by ebmar** [comment]
Yes, the mod contains high-res `LMA_bboard01` with a `clamp 3` TXI, which texture used for the backdrop both in Ahto City and the swoop track.

**Comment by DarthParametric** [comment]
Ah well then. We can refer Sniggles to it if it isn't already part of his mod build I guess.
