### ISSUE TITLE
Lower City bounty hunter should bark instead of cut

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#133]
One of the Twi'lek bounty hunters in the Lower City cantina speaks one-liners in full cutscene mode rather than bark bubbles. This is the guy by the wall who speaks English, not the one standing next to Zax.

**Comment by ebmar** [comment]
This seem to fix it, and yeah - it plays better to have him `bark than cut`, hahah:
```
[tar03_bounhun31.dlg]
!Destination=modules\tar_m03ae.mod
ConversationType=0
```

**Comment by DarthParametric** [comment]
He's obviously an android in disguise.
