### ISSUE TITLE
Manaan Ahto West - Elora conversation issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#135]
- [x] Party needs a jump.
- [x] In the initial convo block, Jolee keeps resetting his position on every reply (twisting in place slightly).
- [x] Jolee doesn't properly face Elora when speaking to her. His body still appears to be angled towards the player. Edit: This appears to specifically be an issue when reinitiating DLG with Elora and falling through to E0. On Jolee's line ` We'll get to the bottom of this and help Sunry... somehow` he pivots in place to face away from her. Speaker/Listener tags and scripted facing doesn't seem to resolve the issue (the former actually causes more problems). The only practical solution is to make the fall-through E0 unique and have it exit directly afterwards.
- [ ] ~Elora's intro line about being made Arbiter repeats on subsequently initiating conversations with her.~ Edit: There's not really much else to work with to provide an alternate intro to that branch. I think we'll just have to leave it as-is.
- [x] ~If you have already met Jolee's messenger, the initial conversation with Elora is extremely brief. Despite knowing about the case, Jolee hasn't seen her for 20 years. Seems like there should be something more there if it can be derived from the non-messenger section.~ Edit: Not sure what I was on about here. There's only a single branch for Jolee being in the party. It's the same regardless of whether he has spoken to Davin or not. Edit 2: Ah, this is caused by an added starting conditional (`cp_man_n_jordo`) that gates off half of that branch if Jolee hasn't spoken to Davin. Must be from an early version of K1CP given that there's no included source. I think that it is better off removed and reverting to the vanilla structure of that branch. Edit 3: While this script was in tslpatchdata, it wasn't being installed, so the gated off branch could never evaluate true.

**Comment by th3w1zard1** [comment]
So from what I'm understanding, this needs:
> * [ ]  Party needs a jump.
A DLG call to a custom script to jump the party. Not sure why you think the party needs a jump though? Elora greets the party immediately when entering the module for the first time.
> * [ ]  In the initial convo block, Jolee keeps resetting his position on every reply (twisting in place slightly).
Haven't experienced this, but sounds like this needs a Camera Angle set in the DLG?
> * [ ]  Jolee doesn't properly face Elora when speaking to her. His body still appears to be angled towards the player.
Same?
> * [ ]  Elora's intro line about being made Arbiter repeats on subsequently initiating conversations with her.
How to reproduce this?
> * [ ]  If you have already met Jolee's messenger, the initial conversation with Elora is extremely brief. Despite knowing about the case, Jolee hasn't seen her for 20 years. Seems like there should be something more there if it can be derived from the non-messenger section.
Sounds like reusing other dialog entries from other replieslist is necessary to create a fluid dialog tree.

Am I on the right track here?

**Comment by th3w1zard1** [comment]
[000221 - Game220.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/13253489/000221.-.Game220.zip)
A save file right before entering the module she approaches you for the first time.

**Comment by DarthParametric** [comment]
> Elora greets the party immediately when entering the module for the first time.

There's a [trigger OnEnter](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Data/scripts.bif/k_pman_init02.nss) that initiates a conversation with her, assuming she has been spawned by the [module's OnEnter](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Data/scripts.bif/k_pman_26a_area.nss) and you haven't spoken to her before. That doesn't herd the party though. Try leaving the PC at the entrance and running a companion up to her in solo mode. Subsequent conversations with her are initiated normally. In either case, positioning the party will allow for alleviating subsequent facing issues - primarily with Jolee - mentioned in the other points.

> Haven't experienced this, but sounds like this needs a Camera Angle set in the DLG?

It's a speaker/listener issue. It's heavily contingent on the initial party positioning, thus it's variable. The ideal arrangement for a conversation with sizeable companion interjections is to make sure that both the PC and the NPC are in an arc in front of them, to minimise the amount of turning in place they do to face the speaker.

> Elora's intro line about being made Arbiter repeats on subsequently initiating conversations with her.

I'd have to look at the DLG to refresh my memory of it. As far as testing it goes, just keep reinitiating a conversation with her over and over, also after progressing the plot stage. It would be easy enough to use a starting conditional to check and set a local boolean on her for having mentioned it. That would likely require a copy of a subsequent entry to fall through to.

> Sounds like reusing other dialog entries from other replieslist is necessary to create a fluid dialog tree.

I'm not sure how practical it is, but a starting point would be comparing the branches dictated by whether Jolee has talked to Davin or not.

**Comment by DarthParametric** [comment]
Per @Salk73 there might be some spurious config data due to editing of prior versions. Need to generate a clean DLG for differencing.
