### ISSUE TITLE
Manaan Ahto West - Courtroom issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#136]
- [x] In the initial Sith vs Republic court case cutscene, the party could use a jump.
- [x] In the initial Sith vs Republic court case cutscene, the Sith officer is facing the Republic officer during first line. Needs to face the judges instead. Edit: This is his spawn-in rotation. Needs a GIT edit. The judge is the same.
- [x] In the initial Sith vs Republic court case cutscene, the first shot of the Republic officer is a wide shot. Since the scene uses static cams, it should have a camera switch to the close-up angle halfway through his line.
- [x] In the initial Sith vs Republic court case cutscene, when the judge switches facing towards the end, it needs a switch back to the wide camera angle.
- [x] In the initial Sith vs Republic court case cutscene, the Sith and Republic officers don't leave after their case is finished (although they are finally destroyed at the Sunry trial). Perhaps move them back to stand near the seating area.
- [x] Talking with Judge Shelkar (central judge) to become Sunry's arbiter, Jolee's interjections are off-screen. Probably jump party in place. Edit: Also needs a cam angle adjustment. Also for other party member interjections (Bastila and Carth).
- [x] The other judges will need the same treatment for their individual DLGs.
- [x] The desk for Judge Jhosa (far right) clips into the desk next to it. Needs a GIT edit.
- [x] Post-Sith base trial. The sequence of the player walking towards the judges seems like it has a few brief switches to other camera angles.
- [x] Post-Sith base trial. Player needs to have Force Speed stripped for their initial walk up.
- [x] Post-Sith base trial. If the player chooses to defend themselves. the judge intro sequence has a wrong camera angle (E19).
- [x] Post-Sith base trial. Arbiter faces player when choosing "Allow him to continue / Interrupt" in a wide shot. Switch to angle 1.
- [x] Post-Sith base trial. Facing issues with judges not facing player. Edit: When defending themselves? Edit 2: They face each other on certain lines. Could be that, but those are working as intended. Edit 3: They could be given locked facings as-in the Sunry trial.
- [x] Post-Sith base trial. Arbiter is visibly destroyed after trial is over.
- [x] Post-Sith base trial. At completion, player is jumped into the hallway but party members are standing in front of judges.
- [x] Post-Sith base trial. At completion, the judges should be refaced.
- [x] ~Post-Sith base trial. At completion, the Rep and Sith from earlier are back in front of judges.~ Edit: This is needed in case you haven't triggered their scene before. But it looks like they jump to the wrong positions (switched).
- [x] Sunry trial. Player is frozen at trial start.
- [x] Sunry trial. Needs hide weapons/mask flags enabled.
- [x] Sunry trial. Witnesses in the background have their backs to the judges.
- [x] Sunry trial. Some of the camera angles used for the witnesses walking up aren't very good.
- [x] Sunry trial. Some of the camera angles used for the Sith prosecutor when questioning witnesses are wrong. Also for the start of his closing arguments.
- [x] Sunry trial. Facing issues with judges looking at each other. Edit: Not really seeing any issues, but they get a facing and locked orientation which has been tweaked.
- [x] Sunry trial. During Gluupor's testimony, one of the judges has an interjection that uses the wide shot instead of their cam.
- [x] Sunry trial. Party member interjections can fail to happen due to distance from the PC (see #711).
- [x] Sunry trial. If Sunry is found guilty, Elora ends up mostly out of shot due to playing the horror animation. There's no existing static camera for her. Edit: This is partially addressed. I've given her a dynamic camera angle 3, which kind of works for at least one shot. All depends on where the listener is in relation to her.
- [x] Sunry trial. If Sunry is found guilty, when he is walking out the guard visibly walks in place in the doorway before disappearing on-screen.
- [x] Sunry trial. If Sunry is found guilty and Jolee is present, his line uses a wide shot not a close-up.
- [x] Sunry trial. After the end the player is left standing in front of the judges (unlike post-Sith base trial). Edit: This seems fine, but the whole party needs a jump since the two party members are at the back of the room.

See also #96

**Comment by Salk73** [comment]
Something to add here:

There is the wrong camera ID for E19. It should be 6 rather than 7.

**Comment by th3w1zard1** [comment]
>In the initial Sith vs Republic court case, the Sith officer is facing the Republic officer during first line. Needs to face the judges instead.

Already has a LISTENER tag?
![image](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/2219836/cb96b23a-1c06-4722-84d6-3deb5db18af5)

**Comment by DarthParametric** [comment]
You'd need to check which particular judge that is. May need switching to a different one. Or it may need a scripted facing to force it.

**Comment by DarthParametric** [comment]
> There is the wrong camera ID for E19. It should be 6 rather than 7.

@Salk73: Is this in the Sith Base or Sunry trial DLGs?

**Comment by Salk73** [comment]
Unfortunately I'm unable to access my computer and answer. The emergency will probably last for one more week.

**Comment by DarthParametric** [comment]
Seems this is for man26_selarb.dlg, the post-Sith Base trial. E19 has man26_seljud1 as the speaker (Judge Shelkar) but cam angle 7 is for man26_seljud3 (Judge Naleshekan).

**Comment by DarthParametric** [comment]
1.10.0 beta test 2 observations:

- [ ] Seems that party members may not obey their jump commands for the post-Hrakert Rift trial and end up next to the player. Was their AI disabled as it is for the Sunry trial?
