### ISSUE TITLE
Manaan Ahto East - Sith Embassy/Base entrance issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#139]
- [ ] ~Attempting to initiate dialogue with the Sith diplomat outside can cause the player to run around behind the desk. Might be best to trigger the conversation as soon as the player approaches the door.~
- [x] There is still a Sith war droid outside when exiting, even though they should have entered when the Security Officer raised the alarm inside the base. Edit: There are 4 droids outside the base before entering. 4 droids come inside with the diplomat during the foyer fight. A new Sith droid is spawned outside the front door after the base is locked down. This droid should only be spawned after the trial, not straight away.
- [x] Exiting the base, there are party alignment issues with party members possibly ending up in front of PC (and obscuring the cutscene with the Selkath).
- [x] The Selkath war droids that escort the player away are white. Maybe switch to another variant to differentiate them from the Sith droids.
- [x]  One of the Selkath war droids has a duplicate tag, which means it doesn't get destroyed properly at the end of the arrest cutscene.
- [ ] ~After the arrest, the module OnEnter sets the base door to be unlocked, which seems like an error. It should be permanently sealed, since the player faced a death sentence for the first incursion.~ Edit: Seems like this was a deliberate choice to allow the player to complete the Shasa quest.

**Comment by Salk73** [comment]
My bad about the duplication.

One thing to note is that the droids you thought were the Sith Droids are actually part of the escort. They are in fact called: man26_drdcut02.utc, man26_drdcut03.utc,  man26_drdcut04.utc, and man26_drdcut05.utc. I agree with you that they should have a different color. Any suggestion?

I can do the recoloring.
