### ISSUE TITLE
Manaan Ahto East - Sith "toll" issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#140]
* Opening line from the Sith that accosts you about paying a toll needs camera angle 1. Maybe also move her sideways a bit, directly opposite entrance?
* There appears to be a random "swoop fan" mook in the way. Incorrect spawn position in GIT?

**Comment by ebmar** [comment]
> ...move her sideways a bit, directly opposite entrance?

Or, switch her position with one of her fellas? Particularly the one closer with the entrance.

> ...a random "swoop fan" mook in the way.

Lol yeah, seriously. This module sucks so bad - of all the planet, I think it's worst. Better to move her to inside the _Swoop Lounge_, I think. I already have the co-ords; I'll have an update soon, if you don't mind.

**Comment by ebmar** [comment]
Apparently she share the same UTC with her clone; `man26_swoop002` - so we will want to specifically move this one:
```
ID=4
StructIndex=40
TemplateResRef=man26_swoop002
XPosition=-40.2208633422852
YPosition=40.3691062927246
ZPosition=57.5000877380371
XOrientation=0
YOrientation=1
```
to having this co-ords, for example:
```
ID=4
StructIndex=34
TemplateResRef=man26_swoop002
XPosition=-90.1361770629883
YPosition=37.0455093383789
ZPosition=56.375
XOrientation=0.364309996366501
YOrientation=0.931280016899109
```
and the result will be like this -
![SwFan_Repositioned](https://user-images.githubusercontent.com/50026566/57761670-2c787600-7728-11e9-8a0f-d42b446ab332.jpg)

**Comment by DarthParametric** [comment]
```XPosition=-90.1361770629883
YPosition=37.0455093383789```

While that certainly would move her out of the way, I'm not sure that dumping her in the ocean is the right approach.
![Manaan_Ahto_East_Swoop_Fan_Move](https://user-images.githubusercontent.com/46890653/57791897-2b276780-7781-11e9-840f-920e2c9e7139.jpg)

**Comment by DarthParametric** [comment]
Ah, I see the problem. `-90` not `90`. Whoops, my bad.

**Comment by DarthParametric** [comment]
Btw, are those orientations right? Seems like it should be reversed - i.e. 0.93042, 0, 0, 0.3665 which is 43 degrees.

**Comment by ebmar** [comment]
> ...are those orientations right? Seems like it should be reversed...

Yes! My bad. The X seems to be right, the Y that was wrong. It must've been -
```
YOrientation=-0.931280016899109
```
Dang, I must have deleted the `-` while cleaning those extraneous-info stuffs.

**Comment by DarthParametric** [comment]
OK -43 degrees, but it still should be reversed. If those are numbers from an armband, it is clearly calculating it wrong.

**Comment by DarthParametric** [comment]
Config:

```
[m26ab.git]
!Destination=modules\manm26ab.mod
Creature List\38\XPosition=-90.1361770629883
Creature List\38\YPosition=37.0455093383789
Creature List\38\ZPosition=56.375
Creature List\38\XOrientation=0.364309996366501
Creature List\38\YOrientation=-0.930419981479645
[man26_sithyell.dlg]
!Destination=modules\manm26ab.mod
EntryList\22\CameraAngle=1
```

We'll list this as one of yours (with the angle change as a bonus).

**Comment by ebmar** [comment]
> We'll list this as one of yours...

Ah, thanks - appreciate it [and _the_ bonus, hahah]! Dang, looking at the INI I thought providing the UTC reference was suffice but it seem GIT only uses `CreatureList` for it. I should've provide the full config in the first place. Noted for future reference. Again, thanks!
