### ISSUE TITLE
Manaan Sith Base - Various issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#141]
- [x] The player can end up behind Security Officer at the front desk if entering the base through the front door and being thrown straight into a conversation with her
- [ ] ~The tortured Selkath is already dead when speaking the line about passing on his trinket to Shasa.~
- [x] Bad lightmapping on the floor of the Dark Jedi Master's room, right where he is standing.
- [ ] ~If you tell Shasa that you think the Sith have the right idea, you can't tell her about the tortured Selkath if you find him afterwards.~

Edit: Additional items from ebmar -
- [x] The Sith Diplomat `man27_sithdip.utc` is seen entering the scene at the front desk with a sword in his hand, but in the next shot the sword is removed.
- [x] The Sith Captain `man27_sithcap.utc` uses the `Sith_Soldier` soundset instead of `Sith_Commoner_Male`, despite using the Sith Officer appearance. 
- [x] The practice droids with shared UTC `g_probedroid002.utc` use the `Droid_War_01` appearance but the `Droid_Probe` soundset. Their Tag/ResRef suggests original developer intent was to use the `Droid_Probe` appearance.

**Comment by ebmar** [comment]
I'd like to add a reference image particularly for this one:
> - The player can end up behind Security Officer at the front desk if entering the base through the front door and being thrown straight into a conversation with her
![SB_Party_Jump](https://user-images.githubusercontent.com/50026566/57981962-ba29cd80-7a68-11e9-8c37-2c240a4348ba.jpg)

and a new entry:

- The Sith Diplomat `man27_sithdip.utc` seen entering the scene with a sword on his hand, but with the next scene the sword was removed. I think it has something to do with `UnequipItems` flag set as active on the relevant DLG `man27_sithlieu.dlg`.
![SD_Equip_Glitch](https://user-images.githubusercontent.com/50026566/57982436-d8df9280-7a6f-11e9-8ff6-0981c3855b70.jpg)

**Comment by DarthParametric** [comment]
All your party members are disarmed as well.

**Comment by ebmar** [comment]
> All your party members are disarmed as well.

Well, _that_ - was roleplay intended, hahah. As for the disarmed cutscene; I think they wanted to give the impression we're entering the base with weapons down, I catch that - or as a workaround for them to straightaway attack with their weapons on when the cutscene aborted/ended.

**Comment by DarthParametric** [comment]
Fixed up the lightmaps in the training room.

![Manaan_Sith_Base_Sith_Master_Room_LMs_01](https://user-images.githubusercontent.com/46890653/57983690-50c1b300-7a98-11e9-9bdf-07fd7f68dcd8.jpg)

![Manaan_Sith_Base_Sith_Master_Room_LMs_02](https://user-images.githubusercontent.com/46890653/57983691-53bca380-7a98-11e9-8ead-9c9a623a9982.jpg)

![Manaan_Sith_Base_Sith_Master_Room_LMs_03](https://user-images.githubusercontent.com/46890653/57983693-561efd80-7a98-11e9-9bdd-30c53c8ea40d.jpg)

**Comment by ebmar** [comment]
- Sith Captain `man27_sithcap.utc` which stationed in the _Flow Control Room_ use `Sith_Soldier` SS instead of `Sith_Commoner_Male`, spite the fact his appearance being generic Sith Officer. Potential fix:
```
[man27_sithcap.utc]
!Destination=modules\manm27aa.mod
SoundSetFile=65
```
- Practice Droids with shared UTC `g_probedroid002.utc` having their appearance as `Droid_War_01` albeit their `Droid_Probe`'s SS. Should their appearance match the SS or the opposite? Because both seem to work and actually looking at their `Tag` - their intention seem to be having `Droid_Probe` appearance in the first place.

**Comment by DarthParametric** [comment]
Revised the training room lightmap and plugged some gaps in the upper walls/ceiling reported by @ebmar.

![DP_TR_HiResLM_Preview](https://user-images.githubusercontent.com/46890653/83775055-d925ec80-a6c9-11ea-95f9-e49b74731413.jpg)

(Picture stolen from ebmar)

**Comment by DarthParametric** [comment]
It's not practical to address the dying Selkath issue. The model lacks any talk injured/pause injured animations, which is presumably why Bioware just spawned them in dead.

Additionally, the Shasa DLG would need fairly extensive work to allow for handing over the locket in the pro-Sith branch. The conversation is really predicated on having chosen the "From my point of view the Sith are evil" route in the initial conversation. There are references to the player finding evidence to support this that wouldn't make sense. 

I think we'll call the issue closed with the already implemented changes.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] In the fight with the receptionist and droids, the party members need a `GN_DetermineCombatRound`.

**Comment by DarthParametric** [comment]
1.10.0 beta test observations:

- [ ] The party jump for the steam vents is a little off, and the player still faces off to one side (looking at the placeable)
- [ ] The vents have a number assigned in the feedback window (see pic below).

![Manaan_Sith_Base_Steam_Vent_Names](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/46890653/b14e234f-33fa-43fd-8945-55cd5c53dda3)

**Comment by DarthParametric** [comment]
1.10.0 beta test 2 observations:

- [ ] Shasha scene isn't triggering correctly, failing to commence before the fade lifts. Seems to be the same issue as #272 with ambient anims delaying the conversation from initiating.
- [ ] The fade for the vent door opening scene also appears to be lifting too quickly.
