### ISSUE TITLE
Manaan Hrakert Station - Various issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#142]
- [x] The Twi'lek merc you meet after getting off the sub goes out of frame during the "They swarmed out and over us" line due to playing the horror(?) animation. 
- [x] Many/most insane Selkath have droid soundsets. Also pretty much every other UTC as well.
- [ ] ~Some insane Selkath attack with fists (flippers?). Not sure if it is intentional or not.~ ❌ Seems this is intentional.
- [x] If you have Bandon appear here, one of his Dark Jedi mooks ignites their saber at start of the conversation, before subsequently extinguishing it. They are spawned in hostile, thus triggering the saber before the covo kicks in. Start them all neutral and turn them hostile the same as Bandon? Maybe even have them all with ignited sabers the whole time.

**Comment by DarthParametric** [comment]
Looking at the script that fires at the end of Bandon's DLG, it is already set up to turn his Dark Jedi lackeys hostile, so I guess they were actually intended to be spawned neutral. An easy fix.

```
	int int1 = 0;
	object oLackyA = GetObjectByTag("g_darkjedi02", int1);
	object oLackyB = GetObjectByTag("g_darkjedi02", int1);
	
	while ((GetIsObjectValid(oLackyA) || GetIsObjectValid(oLackyB))) {
		if (GetIsObjectValid(oLackyA)) {
			ChangeToStandardFaction(oLackyA, 1);
			DelayCommand(0.5, AssignCommand(oLackyA, ClearAllActions()));
			DelayCommand(0.5, AssignCommand(oLackyA, sub1(OBJECT_INVALID)));
		}
		if (GetIsObjectValid(oLackyB)) {
			ChangeToStandardFaction(oLackyB, 1);
			DelayCommand(0.5, AssignCommand(oLackyB, ClearAllActions()));
			DelayCommand(0.5, AssignCommand(oLackyB, sub1(OBJECT_INVALID)));
		}
		(int1++);
```

**Comment by DarthParametric** [comment]
The merc conversation is problematic. While the dynamic camera will happily generate wide shots throughout the convo, trying to force angle 3 on the horror animation line didn't have any result, presumably because it didn't like the  proximity of a party member or a wall, etc. Possibly the only guaranteed fix would be forcibly jumping the party and using a static camera.

**Comment by DarthParametric** [comment]
The jumped party has a slight issue. The righthand party member just ever so slightly clips through the camera in the over-the-shoulder shot behind the player. They need to me moved back a foot or so.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
As an addendum to the Bandon script edit, the party members need a `GN_DetermineCombatRound` to prevent them standing around doing nothing.

**Comment by LaIngobernable** [comment]
The PC also looks down at the floor while talking to the whimpering locker. While there's no face for them to look at, it feels like an odd way to talk to the guy.

**Comment by DarthParametric** [comment]
The looking at the floor thing is an artefact of using placeables as the DLG owner. 

The door is closed by the module's OnEnter. There's no check for it, so it closes every time you re-enter the module (including from loading a save). It would be easy enough to gate it behind a plot state check. Although interestingly Bandon isn't spawned by the OnEnter, so presumably that's a trigger handling that. The door closing could also be switched to that instead.
