### ISSUE TITLE
Leviathan Prison Block - Various issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#145]
- [x] Post-interrogation, one of Bastila's later lines is facing Carth, not the player. (can't remember which it is - one towards end). Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/238b9139e37a685566f9c31f35730cf64160e8e5
- [x] When the big three are released, Bastila's last line to Canderous is facing the player. Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/66d1a15ecc75bfcb16ab75569c9b5c5d90defce4
- [x] Choosing Canderous to break everyone out results in him vibrating in place on his "_Don't you worry about that_" line. (Resolved in [All Hands on Deck for the Leviathan Prison Break](https://deadlystream.com/files/file/2097-all-hands-on-deck-for-the-leviathan-prison-break/)) Should be fixed by https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/d56bf710d80a7a800fd52fc6c6682638402e76d2 Edit: Adjusted in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/66d1a15ecc75bfcb16ab75569c9b5c5d90defce4

❌ ~The Sith Trooper Captain probably needs a different texure variant to distinguish his rank. Red like guy in the Taris Undercity?~ Edit: Addressed by [standalone mod](https://deadlystream.com/files/file/2097-all-hands-on-deck-for-the-leviathan-prison-break/).
❌ ~If you pick HK-47 for the rescue, his initial cutscene has an extended animation looping. He should be deactivated and then do the animation while starting up.~ Edit: Addressed by [standalone mod](https://deadlystream.com/files/file/2097-all-hands-on-deck-for-the-leviathan-prison-break/).
❌ ~Post-escape, Bastila and Carth get their gear re-equipped, but not the player. This is probably to make sure the player gets all their inventory items back by looting all the containers, but I'd prefer to just give it all to them directly.~ Edit: Addressed by [standalone mod](https://deadlystream.com/files/file/2097-all-hands-on-deck-for-the-leviathan-prison-break/).

1.9.0 beta test observations:
- [x] The player needs to be faced towards Saul at the start of the interrogation scene. Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/238b9139e37a685566f9c31f35730cf64160e8e5
- [x] The Starboard Cell Block Key (`lev09_starcellkey`) remains in inventory post-jail break. Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/168c08c6c76173dfbeffe29367c0735f14454d82
- [x] The Sith Passcard (`lev40_detcard`) remains in inventory post-jail break. Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/168c08c6c76173dfbeffe29367c0735f14454d82
- [x] The ICE Breaker (`tar09_icebreaker`) remains in inventory post-jail break if not used. Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/168c08c6c76173dfbeffe29367c0735f14454d82
- [x] The elevator options include "Bridge", but that should be "Command Deck" instead. Edit: Ditto for the elevator terminal on the Command Deck itself. Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/b050af97c1bb4b7354d12fe27572a82ce9ddc5c5

❌ ~Bastila mispronounces Vandar's name (sounds kind of like "ven-duh")~ _Not fixable._

Additional:
- [x] The fade-out at the end of the torture scene needs to be extended slightly to cover the transition to the jail breaker. Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/238b9139e37a685566f9c31f35730cf64160e8e5
- [x] Saul has some facing issues when switching between Bastila's interjections and addressing the player. Fixed in https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/238b9139e37a685566f9c31f35730cf64160e8e5

**Comment by DarthParametric** [comment]
This post-escape equipment one is presumably a no go. The naked Bastila and Carth are fake, hence why they magically get their equipment back. The fakes are destroyed and the real ones added back. I suppose the PC could probably be faked with `DuplicateHeadAppearance` but that's probably too much screwing around.

**Comment by JCarter426** [comment]
Yeah, I don't think there's any way to fake the player on account of how they have to respond to dialogue. We could, however, move the player's equipment to invisible containers and then reequip to the correct inventory slots. That's what's done for some cutscenes.

**Comment by DarthParametric** [comment]
If we are going to do that, then it would be best to also add back the entire inventory that has been dumped in those containers in the room the party runs to.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] The player needs to be faced towards Saul at the start of the interrogation scene.
- [ ] Bastila mispronounces Vandar's name (sounds kind of like "ven-duh"

**Comment by LaIngobernable** [comment]
On my end, everything but the dialogue text goes black during the response selection after "Now, I will ask again - on what mission did the Jedi Council send you?" during the interrogation. Reloaded a save and happened again.

**Comment by DarthParametric** [comment]
I believe this is a vanilla issue. There are a number of player reply nodes in the torture scene (lev40_saul403.dlg) that are missing the static camera assignment, which I discovered (and fixed) during the testing of my recent _All Hands on Deck_ mod. I planned to add those elements to K1CP in due course.
