### ISSUE TITLE
Subtitle mismatches

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#148]
This is on hold for v1.8, given we don't want to be appending half the TLK or outright replacing it. For now this is just a repository for noting these instances of incorrect subtitles so they can be addressed at some point in the future (either when we can edit dialog.tlk directly, or if someone else decides to release a standalone TLK replacement).

__**General**__
- [ ] Canderous' line after `I weep for my past` in his personal quest chain has incorrect subtitles. Should be "_We will never again speak of this_", not "_We'll never speak of this again_". StrRef = 2405
- [ ] In Bastila's first prompted dialogue, the line `Perhaps, but the Force works through all of us to some degree or another. There are some individuals outside the Jedi Order that we considered 'Force Sensitive'`, has incorrect subtitles. it should be "_consider_" not "_considered_". StrRef = 31461
- [x] ~Canderous' line about working for Davik `Jedi were a better challenge, but they hardly ever poked around in the Under City.` has no visible subtitle. Also should be "_Undercity_". StrRef = 2256~ _**Invisible fix discovered by Gimmick5000**_
- [ ] Canderous' line `....This is unbecoming of a warrior!...` doesn't match the VO. It should be "_unbecoming a warrior_". StrRef = 2265

__**Taris Upper City South Apartments**__
- [ ] Janitor's opening line. VO is `I just cleaned those floors_" but subtitle is "_I just cleaned these floors`.
- [ ] Janitor's line about how to get to the Cantina. VO says `It'll take you out to the upper streets` but the subtitle is `It'll take you out to the Upper City streets`.
- [ ] Janitor's line on DLG exit. VO says `The building doesn't clean itself, you know` but the subtitle is `This building doesn't clean itself, you know`.

__**Taris Lower City**__
- [ ] First convo with Canderous outside Lower City Apartments. `Gadon keeps his hidden Beks in line...`. "_Hidden_" should be capitalised. StrRef = 23980
- [ ] Line from Sith Lower City elevator guard when checking your papers - VO doesn't match subtitles. StrRef = ??

__**Taris Lower City Cantina**__
- [ ] Spelling mistake in Canderous' line `...I haven't heard about anyone breaking into the military base yet`. Subtitle has it spelled "_miliarty_".

__**Taris Lower City Apartments B**__
- [ ] When confronting Selven, her line `No, I'm the one with the blaster pointed at you` ends with `What are you doing here?` but the subtitles say `Now - what are you doing here?`.

__**Taris Undercity**__
- [ ] Convo with Canderous, post-Rakghoul attack line `But the Lower City gangs got here first. Anything worthwhile in those Republic pods is probably in their hands now. Davik won't like that.` VO doesn't match subs. StrRef = 25130

__**Ebon Hawk**__
- [x] ~Jolee's `...during our rather rapid descent...` line has no visible subtitles. StrRef = 10054~ _**Invisible fix discovered by Gimmick5000**_

__**Dantooine Jedi Enclave**__
- [ ] After dealing with Juhani, Vandar's line `Your training is now complete, young Padawan.` doesn't match the VO. He doesn't say "young". StrRef = 6809

**Comment by ebmar** [comment]
**Manaan Ahto West**

- Mandalorian Mercenary/Ergeron had some redundant words on one of his line -

> Maybe that Iridorian skullslacker at the bar, or the Echani nerfherder cowering in the corner **~~is available~~**.

He stopped talking at `the corner`. `StrRef=17462`
