### ISSUE TITLE
Dantooine ruins facing issues

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#152]
Bastila suffers some facing problems when speaking to the Ancient Droid in the ruins. If I was quick enough taking screenshots, they're on these nodes:
![swkotor 2019-05-16 16-20-59-99](https://user-images.githubusercontent.com/46898647/57926237-c8b19280-7878-11e9-8cc8-4eda45393cdd.png)
![swkotor 2019-05-16 16-21-12-02](https://user-images.githubusercontent.com/46898647/57926245-c9e2bf80-7878-11e9-95b3-5b3692d4c05d.png)

**Comment by DarthParametric** [comment]
This is really already encompassed by #105. I'm also not entirely sure there is actually any issue depicted in the screenshots, but the conversation has been edited as part of the fixes for 105.
