### ISSUE TITLE
Elise calmly walks away

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#153]
Elise calmly walks away after being told her "husband" is dead and the party stands there patiently and awkwardly as she does once the AI has figured out the pathing. Should be set to run away like NPCs normally do.
![swkotor 2019-05-16 15-52-15-30](https://user-images.githubusercontent.com/46898647/57926419-32ca3780-7879-11e9-9fc7-6a1756bcdff4.png)

**Comment by DarthParametric** [comment]
Hilariously, she sprints if you bring her sexbot back. 

I was going to suggest changing that one to walk, because the droid can't keep up.

**Comment by ebmar** [comment]
> Elise calmly walks away after being told her "husband" is dead...

> ...she sprints if you bring her sexbot back.

How about making a fade to black transition at the end of dialogue? I think it'd makes more sense if she going home _with_ her speeder, not running/walking back to the Enclave.

**Comment by DarthParametric** [comment]
She has to go to the Enclave under certain circumstances. She can shack up with some bloke there I believe.

**Comment by DarthParametric** [comment]
Elise still runs away faster than the droid can follow if you finish the quest by returning it to her. I thought that was supposed to be changed? Or was it only the walking away when you destroy it?

**Comment by JCarter426** [comment]
I thought I did both, so I'll take a look.
