### ISSUE TITLE
Sandral-Matale Feud - I am altering the deal

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#154]
The player has the option to claim that Ahlan Matale offered a reward for rescuing Shen even if no such conversation took place. There's probably already a global that checks this, so this node would just need a conditional for it.
![swkotor 2019-05-16 15-32-09-60](https://user-images.githubusercontent.com/46898647/57926568-9fddcd00-7879-11e9-860d-32f3aeca9eef.png)

**Comment by DarthParametric** [comment]
Maybe if you talk to him in the Jedi Enclave? Can you talk to him at his estate? I though the droid tells you to piss off.

**Comment by JCarter426** [comment]
Might be cut content. I remember seeing some dialogue about the reward before, but before you finish your trials he refuses to speak to you, and then after there's no sign of him in the enclave.

**Comment by JCarter426** [comment]
Ah, I figured out that mystery. You can talk to him at his estate (danm14ab) if you haven't gone into the Sandral estate yet. This scene sets the global boolean `DAN_AHLAN_DONE` as soon as he comes out of the estate so I suspect a conditional with that should do the job.
