### ISSUE TITLE
Manaan Ahto East - Clipping Swoop Records Panel

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#155]
There's a Swoop Records Panel `comppnl001.utp` inside Swoop Registration in Manaan Ahto East `manm26ab` which clips to the wall, as seen here -
![AESR_Clipping_PLC](https://user-images.githubusercontent.com/50026566/57948864-f9dba280-790c-11e9-9429-29fc8801c770.jpg)
A fix for it; as I preferred:
```
[m26ab.git]
!Destination=modules\manm26ab.mod
Placeable List\17\Bearing=3.74468994140625
Placeable List\17\X=-53.0584602355957
Placeable List\17\Y=27.4868297576904
```
which will reposition the panel to be here -
![AESR_Clipping_PLC_Fix](https://user-images.githubusercontent.com/50026566/57948989-517a0e00-790d-11e9-8a40-27c3b6ca601e.jpg)

**Comment by DarthParametric** [comment]
If you are going to change the angle that much, I'd shove it back into the corner a bit more.
