### ISSUE TITLE
Global -  A couple of Mark IV had their Sound Set wrong

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#159]
Apparently a couple of Assault Droid Mark IV had their SS as `Bantha`, and they seem to use global `templates` for their UTC - which is `g_assaultdroid03`, means that they have no reference on the Sith Base module `manm27aa`.

So there are two fixes which will work but need a hard-copy of [g_assaultdroid03.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3195459/g_assaultdroid03.zip) with the installation:

1. Module injection:
```
[g_assaultdroid03.utc]
!Destination=modules\manm27aa.mod
SoundSetFile=5
```

2. Override:
```
[g_assaultdroid03.utc]
SoundSetFile=5
```

Also see #141 for `Various Issues`.

**Comment by DarthParametric** [comment]
There's no point doing a specific Manaan fix if it's a global template problem. Best to do it once and do it right.

**Comment by ebmar** [comment]
Ah, so with the `Override` install then.

**Comment by JCarter426** [comment]
Looks like the problem is common to all g_assaultdroid and g_assassindrd templates.

**Comment by DarthParametric** [comment]
It's all droids, period. They are all set to the Bantha soundset (although interestingly not the turrets, though the ones in the Lehon Temple were set to Bantha). Probably around a dozen or so UTCs in total.
