### ISSUE TITLE
Korriban Academy entrance - Belaya still attacks with fists

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#161]
Might be easier to just equip her saber from the get-go.

**Comment by JCarter426** [comment]
Wasn't this one of the older fixes?

**Comment by DarthParametric** [comment]
Yes, hence the "still".

**Comment by DarthParametric** [comment]
Decompiling the NCS, it looks like it is still the vanilla script, not the edited version with the addition of `ActionEquipMostDamagingMelee`. Whoops.
