### ISSUE TITLE
Korriban Tomb of Tulak Hord - Various issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#165]
- [x] The ancient computer terminal seems to take ages to work. Long delays between the initial screen and the options popping up, and between clicking an option and anything happening.
- [x] Mekel dies before the lightning hits him.
- [x] The party doesn't fully enter the corridor past the computer before getting gassed.
- [x] A party member may fail to be jumped into the chamber for the Jorak Uln scene.
- [x] Party members in the background during the torture scene may stop playing the stunned animation on certain nodes.
- [x] Droid companions lack the stunned animation other companions use.
- [x] The screams for the player and Mekel when tortured are the background scream SFX and are too soft/quiet.
- [x] There are some facing issues when Jorak is talking to Mekel but facing the player

**Comment by ebmar** [comment]
> Ancient computer terminal seems to take ages to work. Long delays between the initial screen and the options popping up, and between clicking and option and anything happening.

Apparently the `Skippable` flag in the terminal's DLG `k38b_plc_console.dlg` being disabled, and that is why the transition between nodes take ages to go through. I have tried with turning on the flag, but it seem to me there's an issue with the opening door animation, which why I think it was intended that they disabled the flag in the first place.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] The DLG needs to have the hide weapons/masks flags enabled.
