### ISSUE TITLE
Unknown World Central Beach - Various issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#168]
- [x] The post-Bastila scene on beach is screwy for the DS route. There are two separate scenes between Carth running away and dealing with Mission with a quest notification pop-up in between them. 
- [x] During the Mission element, the the PC moves off camera, causing some bad super zoomed in framing if you tell Zaalbar to kill her. 
- [x] Canderous seems to be disarmed, while everyone else still has their weapons. Edit: All party members need an anim set in the first node in order to force the hidden weapons flag to apply to them.
- [x] Per [226](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/226), party members may activate an equipped energy shield when Zaalbar is forced to attack Mission.
- [x] If you have Zaalbar kill Mission you get her gear back, but if you kill both you don't get gear from either of them.
- [x] In the LS version, most of the nodes need the addition of Listener tags plus some facing scripts.
- [x] The end of the LS version lacks the shot the DS version has of the party running to the Hawk.
- [x] Sloppy NPC herding in initial Rakata encounter (per ebmar - see below).
- [x] Delay in NPCs turning hostile post-cutscene in initial Rakata encounter (per ebmar - see below).
- [x] The player constantly faces the invisible placeable in initial Rakata encounter, even if scripted otherwise, since the Listener fields of the DLG are all empty.
- [x] Need to add provision for re-entering the beach post-showdown and potentially getting duplicate items.

**Comment by ebmar** [comment]
- [ ] Upon arriving the first time we're encountered by a group of Rakatan. Appears to me that when they approach the party members they're weirdly stuffed onto each other. Apparently all of them were assigned to a single waypoint, which tag is `missionend`. A suitable fix presumably is to assign each Rakatan to a destined location individually. I've got this setup on my end which appears to be working -
```
//:://////////////////////////////////////////////////////////////
//:: k_punk_nfight05
//:://////////////////////////////////////////////////////////////
/*
	Fired by newfight.dlg in unk_m41aa [Unknown World - Central Beach]

	This script fires with E5 of the DLG. It commands the Rakatan to
	RUN to an *individually* assigned waypoints. Original script
	assigned them all to a single point which makes them stuffed
	onto each other upon arriving the destined location.
*/
//:://////////////////////////////////////////////////////////////
//:: Created By: BioWare
//:: Modified By: ebmar
//:: Modified On: September 09, 2019
//:://////////////////////////////////////////////////////////////

void main()
{
	// Creatures
	object oRakata1 = GetObjectByTag("unk41_blk4");
	object oRakata2 = GetObjectByTag("unk41_blk1");
	object oRakata3 = GetObjectByTag("unk41_blk3");
	object oRakata4 = GetObjectByTag("unk41_blk2");
	object oRakata5 = GetObjectByTag("unk41_blk5");
	
	// Locations/Waypoints
	object oWP_Rakata2 = GetObjectByTag("missionend");
	object oWP_Rakata1 = GetObjectByTag("playermiss");
	object oWP_Rakata3 = GetObjectByTag("zaalbarend");
	object oWP_Rakata4 = GetObjectByTag("final1wp2");
	object oWP_Rakata5 = GetObjectByTag("playerend");
	
	// Pause the conversation for the following commands to takes effect
	ActionPauseConversation();
	
	// Commands the Rakatan to RUN to the assigned waypoints
	AssignCommand(oRakata2, ActionForceMoveToObject(oWP_Rakata2, TRUE));
	AssignCommand(oRakata1, ActionForceMoveToObject(oWP_Rakata1, TRUE));
	AssignCommand(oRakata3, ActionForceMoveToObject(oWP_Rakata3, TRUE));
	AssignCommand(oRakata4, ActionForceMoveToObject(oWP_Rakata4, TRUE));
	AssignCommand(oRakata5, ActionForceMoveToObject(oWP_Rakata5, TRUE));
	
	// Do nothing for 'fSeconds' seconds and then resume the conversation
	ActionWait(1.5);
	ActionResumeConversation();
}
```

**Comment by ebmar** [comment]
- [ ] Apparently there's a brief moment of confusion when the first group of Rakatan supposed to be hostile towards the party members. The original script delays the `ChangeToStandardFaction` function -which should make the Rakatan go hostile- for about 0.3 seconds, so we may see them being neutral for a quick glimpse . That bothers me, so I pointed that as an issue and having a suitable fix which seem to be working on my end -
```
//:://////////////////////////////////////////////////////////////
//:: k_punk_nfight06
//:://////////////////////////////////////////////////////////////
/*
	Fired by newfight.dlg in unk_m41aa [Unknown World - Central Beach]

	This script fires with R5 of the DLG. It turns the Rakatan to
	be *hostile* towards the party members. It originally has a
	0.3 seconds delay upon firing the script - this modification
	eliminates that.
*/
//:://////////////////////////////////////////////////////////////
//:: Created By: BioWare
//:: Modified By: ebmar
//:: Modified On: September 09, 2019
//:://////////////////////////////////////////////////////////////

void main()
{
	// Creatures
	object oRakata1 = GetObjectByTag("unk41_blk4");
	object oRakata2 = GetObjectByTag("unk41_blk1");
	object oRakata3 = GetObjectByTag("unk41_blk3");
	object oRakata4 = GetObjectByTag("unk41_blk2");
	object oRakata5 = GetObjectByTag("unk41_blk5");
	
	// Turns the Rakatan to be *hostile* towards the party members
	ChangeToStandardFaction(oRakata2, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(oRakata4, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(oRakata3, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(oRakata1, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(oRakata5, STANDARD_FACTION_HOSTILE_1);
}
```

**Comment by Salk73** [comment]
DP,

do you think you could be so kind as to upload a video of the evil ending with Zaalbar persuaded into killing Mission?

Also, I might be wrong but wouldn't we need a RemoveAvailableNPC() for Cart as well after he runs away?

**Comment by DarthParametric** [comment]
Carth is removed from the party table on E23 of unk41_carth.dlg by `k_punk_carthrem`. It's untouched by these changes.

As to the video, not at the moment. I just cleaned out my install for the first 1.9 beta test. I still need to test the Carth romance lines in that scene though, so if I can get an appropriate save from someone I can probably cap a video at that point.

**Comment by Salk73** [comment]
Yes, I noticed later that there is already a script that removes Carth from the party.

I have manually incorporated the changes into my game and wanted to run a few tests, hoping that I haven't done any mistake by reading the TSLPatcher changes for this massive fix.

Testing the evil path, I got to fight and kill both Zaalbar and Mission. Unlike the get-Zaalbar-to-kill-Mission route, there is not going to be nice permanent bodies for the two former party members and I do think it would be a good touch to do there what you have done already for Mission.

On top of that, if you disembark the Ebon Hawk you will find the remains. Collecting them will get you duplicates of their equipment that you duped earlier via script.

**Comment by DarthParametric** [comment]
Hrm. I never tested leaving the Hawk again. Never even crossed my mind, since I just naturally assumed everyone would beeline to the Star Forge. But I guess you could technically still need to find the hyperdrive parts. I guess I'll have to account for that edge case.

**Comment by Salk73** [comment]
Yes, most players won't ever disembark again at that point but better be safe than sorry.

I also may have found a glitch: after dispatching Zaalbar and Mission there should be the same cutscene you got after getting Zaalbar to kill Mission. That is, Bastila telling you "Well done, Lord Revan. You are as ruthless as Malak ever was! Quickly, now. We have to get to the Star Forge and destroy the usurper!" but in my case it never triggers.

**Comment by DarthParametric** [comment]
I also noticed that I forgot to add an orientation adjustment to one of the static cameras for better framing in the Zaalbar killing Mission route.

**Comment by Salk73** [comment]
I made a few more tests and there is a couple of things:

1) In my testing, there doesn't seem to be any increase of movement speed for the party members, despite the changes to the finale01 script.

2) The cutscene of Zaalbar killing mission does not look so good yet. There is a missing camera due to the .git file being not updated but ignoring that and focusing just on the stunt animations, is it supposed to look like it is in this short video? https://youtu.be/SqKagkRFfHw

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] For the initial Rakata scene, the party needs a `ClearAllEffects` and possibly a reduction in the length of pause during the shot of the party moving into position.
- [ ] The Rakata turning hostile script needs the addition of a `GN_DetermineCombatRound` for PM1 and 2.
