### ISSUE TITLE
Ebon Hawk - Unknown World post-landing conversation issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#174]
- [x] The player walks in while Carth is talking, but doesn't turn to face him (or the rest of the party)
- [x] Carth's line about the Republic fleet not having protection against the energy field, he turns to face the PC halfway through the line
- [x] Scripts used for facing throughout the DLG incorrectly use template ResRefs instead of Tags (reported by @ebmar)
- [x] The PC switches facing between Jolee and Carth towards the end of the scene
- [x] The scene uses an invisible placeable as the listener for several nodes, which causes the speaker heads to be angled down due to its low height
- [x] The DLG settings are set to hide weapons, but not headgear
- [x] Zaalbar and HK are not active participants in the cutscene (except for an optional line from Zaalbar about Gizka), so their weapons are are not hidden like the rest of the party

Vanilla scene (with missing Jolee subtitle fix) - https://www.youtube.com/watch?v=zDAv0UGqCyg
Edited scene (Light Side version) - https://www.youtube.com/watch?v=s5n4psOy9gE

**Comment by ebmar** [comment]
- [ ] The `k_punk_faceall` fired by R26 in `unk41_carth.dlg` has incorrect tags called by the `GetObjectByTag`, which makes the function not working as it should. Below is a suitable fix which I think should restore the function intention, and it also include validity checks for Bastila and Juhani -
```
//:://////////////////////////////////////////////////////////////
//:: k_punk_faceall
//:://////////////////////////////////////////////////////////////
/*
	Fired by unk41_carth.dlg in ebo_m41aa [Ebon Hawk - Unknown World]

	This script fires with R26 of the DLG. It happens when the Ebon
	Hawk crash landed on the Unknown World.
*/
//:://////////////////////////////////////////////////////////////
//:: Created By: ebmar [based on BioWare's implementation]
//:: Created On: September 03, 2019
//:://////////////////////////////////////////////////////////////

void main()
{
	// Creatures
	object oPC = GetFirstPC();
	object oCanderous = GetObjectByTag("Cand");
	object oBastila = GetObjectByTag("Bastila");
	object oCarth = GetObjectByTag("Carth");
	object oMission = GetObjectByTag("Mission");
	object oJuhani = GetObjectByTag("Juhani");
	object oJolee = GetObjectByTag("Jolee");
	object oHK47 = GetObjectByTag("HK47");
	object oZaalbar = GetObjectByTag("Zaalbar");
	object oT3M4 = GetObjectByTag("T3M4");
	
	// Do validity checks to the party members' presence and commands them to face the FirstPC
	if(GetIsObjectValid(oCanderous))
	{
		AssignCommand(oCanderous, ClearAllActions());
		AssignCommand(oCanderous, SetFacingPoint(GetPosition(oPC)));
	}
	if(GetIsObjectValid(oBastila))
	{
		AssignCommand(oBastila, ClearAllActions());
		AssignCommand(oBastila, SetFacingPoint(GetPosition(oPC)));
	}
	if(GetIsObjectValid(oCarth))
	{
		AssignCommand(oCarth, ClearAllActions());
		AssignCommand(oCarth, SetFacingPoint(GetPosition(oPC)));
	}
	if(GetIsObjectValid(oMission))
	{
		AssignCommand(oMission, ClearAllActions());
		AssignCommand(oMission, SetFacingPoint(GetPosition(oPC)));
	}
	if(GetIsObjectValid(oJuhani))
	{
		AssignCommand(oJuhani, ClearAllActions());
		AssignCommand(oJuhani, SetFacingPoint(GetPosition(oPC)));
	}
	if(GetIsObjectValid(oJolee))
	{
		AssignCommand(oJolee, ClearAllActions());
		AssignCommand(oJolee, SetFacingPoint(GetPosition(oPC)));
	}
	if(GetIsObjectValid(oHK47))
	{
		AssignCommand(oHK47, ClearAllActions());
		AssignCommand(oHK47, SetFacingPoint(GetPosition(oPC)));
	}
	if(GetIsObjectValid(oZaalbar))
	{
		AssignCommand(oZaalbar, ClearAllActions());
		AssignCommand(oZaalbar, SetFacingPoint(GetPosition(oPC)));
	}
	if(GetIsObjectValid(oT3M4))
	{
		AssignCommand(oT3M4, ClearAllActions());
		AssignCommand(oT3M4, SetFacingPoint(GetPosition(oPC)));
	}
}
```
I change the `GetPCSpeaker` function to `GetFirstPC`, just to make sure. Not certain if it was legit, though it works.

**Comment by DarthParametric** [comment]
You don't really need to bother with the validity checks, since nothing will happen if they aren't there.

**Comment by ebmar** [comment]
Yeah, I guess that should be more efficient, hahah. I was testing if it works with validity checks, and didn't bother on changing when it does.

**Comment by DarthParametric** [comment]
Only HK and Juhani are optional in that scene. Everyone else will always be present. Speaking of which, you can take out Bastila, since she will never be in the scene.

**Comment by DarthParametric** [comment]
He's the scene with the incorrect tags in the facing scripts corrected. Still lots of little issues.

https://www.youtube.com/watch?v=FBXuUpR6xDg

**Comment by ebmar** [comment]
> The player walks in while Carth is talking, but doesn't turn to face him (or the rest of the party)

I think there are two alternatives for that -

1. Merge the script that comes with `k_punk_pcwalk` to `k_punk_cut02`, and remove the former from the entry - it works
2. If intent to go with the default setup, ones should try to make the PC rotate their orientation to the `"centerface"` invisible placeables; as seen around `0:14` mark in the video. The script which is `k_punk_pcwalk` has the needed function but it fails to work. Strangely, it works if it transferred to the initial node and merge it with `k_punk_cut02`

**Comment by DarthParametric** [comment]
Here's the edited scene, although the Light Side version so it's not a totally 1:1 comparison with the vanilla video - https://www.youtube.com/watch?v=s5n4psOy9gE
