### ISSUE TITLE
Star Forge Republic Command Ship stunt module - Vandar stunt animation issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#178]
In the final DS Republic fleet scene, Vandar's stunt anims seem to have problems. His eyes are shut as he is speaking to Dodonna and only one arm is behind his back, the other at his side.

Module is STUNT_54a.

**Comment by DarthParametric** [comment]
Looking at the stunt model in Max, it's fine. Comparing this Vandar stunt model (M01aa_C04_char01) to the one used in the previous stunt module (M01aa_C03_char01), the difference would appear to be that M01aa_C04_char01 has N_Yoda as the supermodel, with an anim scale of 0.278, while M01aa_C03_char01 has S_Male02 as the supermodel, also with an anim scale of 0.278. I guess I'll change that and see if it makes a difference.

**Comment by DarthParametric** [comment]
I tested the vanilla version on a different machine. Interestingly, Vandar had proper eye animation this time, but he still only put one arm behind his back in the last shot:

![Vandar_One_Arm](https://user-images.githubusercontent.com/46890653/58074714-44993b00-7be9-11e9-871b-3c2ac11e075f.jpg)

Changing the supermodel does indeed appear to fix the issue:

![Fully_Armed_and_Operational_Vandar](https://user-images.githubusercontent.com/46890653/58074909-b4a7c100-7be9-11e9-86b2-f923d0352764.jpg)

**Comment by ebmar** [comment]
> Changing the supermodel does indeed appear to fix the issue...

Dang, that little details that changed the game. Nice catch! :clap:
