### ISSUE TITLE
Sith Elite Troopers in Manaan hangar

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#183]
[video](https://www.dropbox.com/s/4ghn7b1trhp9lg3/Force%20Jump%20%2B%20Sneak%20Attack.avi?dl=0)
These guys have the appearance of officers but with the helmeted trooper soundsets. I'm thinking they could use an appearance change like Calo's Korriban goons.

**Comment by ebmar** [comment]
These alternatives seem to fixed them -

1. Silver armored Sith Elite Trooper & red armored Sith Grenadier:

```
[g_sithtroop003.utc]
!Destination=modules\manm26ad.mod
Appearance_Type=261

[g_sithtroop007.utc]
!Destination=modules\manm26ad.mod
Appearance_Type=44
```
2. Red armored Sith Elite Trooper & silver armored Sith Grenadier:
```
[g_sithtroop003.utc]
!Destination=modules\manm26ad.mod
Appearance_Type=44

[g_sithtroop007.utc]
!Destination=modules\manm26ad.mod
Appearance_Type=261
```
Though on my end I assigned Elites with silvers, and Grenadiers with reds.

**Comment by DarthParametric** [comment]
It should be noted that these need the `!Filename=` treatment, since they use generic ResRefs already in use.
