### ISSUE TITLE
Manaan Sith Base - Sith Troopers unideal placement

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#184]
![FCR_STrooper_Idle_CoOrds](https://user-images.githubusercontent.com/50026566/58385368-79f2be00-8019-11e9-8f3c-e49e6fec4af1.PNG)

- [x] There're two in-convo Sith Troopers `#1` that didn't seem to going hostile when we entered the _Flow Control Room_ from the front door `#3`. It seem the problem is their placement which makes the entering party out their line of sight.
A solution which seem to work without messing [too much] with the other door's `#4` hostile-trigger is to move them to this location -
```
[m27aa.git]
!Destination=modules\manm27aa.mod
Creature List\41\XPosition=158
Creature List\41\YPosition=-23.2999992370605
Creature List\42\XPosition=158
Creature List\42\YPosition=-21.5
```

While at it; apparently a Sith War Droid `man27_room1.utc` `#2` at the same room need a waypoint, as it was intended to do so - which is not. As seen on the map I've drawn a possible waypoint [if that how a waypoint works?] that could be working. Didn't seem likely for a control room to not have a patrol around.

- _Visit #141 for `Various Issues`._

**Comment by DarthParametric** [comment]
They presumably did not patrol the droid through the room because doing so would force it to open doors. That is not desirable, so it needs to stick to hallways.

**Comment by DarthParametric** [comment]
Moved the second trooper to the other side:

```
[m27aa.git]
!Destination=modules\manm27aa.mod
Creature List\41\XPosition=158.0
Creature List\41\YPosition=-23.3
Creature List\42\XPosition=158.0
Creature List\42\YPosition=-14.42
```
