### ISSUE TITLE
Manaan Sea Floor - Missing Firaxa's Sound Set

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#185]
Apparently none of them Firaxas on the Sea Floor `manm28ab` had an active Sound-Set. Here are several possible fixes that I believe covered most of the Firaxas within the module -
```
[c_firixa001.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13

[man28_firixa.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13

[man28_firixa01.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13

[man28_firixa02.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13

[man28_firixa03.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13

[man28_firixa04.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13

[man28_firixa05.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13

[man28_firixa06.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13

[man28_firixa07.utc]
!Destination=modules\manm28ab.mod
SoundSetFile=13
```
Though -the way I hear it- the SS in general need some tweak around, particularly to better reflect the underwater-travelled sound. But I think it fits one of CP's scope which is restoring dev's intention in the first place.

**Comment by DarthParametric** [comment]
Given that they didn't use them, I'd assume developer intent was they weren't appropriate. Seems like another candidate for a standalone mod to me.
