### ISSUE TITLE
Ending cutscene for Light Side - Multiple issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#186]
There are a few minor issues in this scene. Some due to widescreen framing issues, others due to stunt animations.

- [x] The module is using unique low res textures for everything, even though the assets are reused. Probable Xbox-specific performance related change.
- [x] Zaalbar has animations for two vocalisations at the start of the scene, but only a single SFX plays. 
- [x] The second time Zaalbar vocalises (towards the end in a wide shot) he has three distinct barks, but only animates for two.
- [x] Dodonna blocks the Council in a number of shots.
- [x] Bastila seems to constantly change position between shots, including being absent altogether from at least one shot.
- [x] Jolee and Mission both disappear from some of the wide shots.
- [x] HK-47 has his arms out in an awkward A-pose instead of relaxed against his body.
- [x] HK-47 is obscured or missing in certain wide shots.
- [x] Juhani is obscured in one wide shot.
- [x] Canderous' arm clips into Zaalbar during one wide shot.
- [x] Dodonna and one of the Council members can be seen floating off the ground in the background of the Vandar wide shots.
- [x] T3-M4/HK/Juhani/Mission/Jolee/Carth visibly float above the ground in at least one shot.
- [x] Carth has his meme-tastic derp smile.
- [x] In the final shot, it looks like the PC rises out of the ground. Edit: Appears to be related to stunt model's cutscenedummy / rootdummy position? Partially resolved/mitigated.
- [x] Many shots have dead space at the sides due to being originally framed for 4:3, but now appearing in 16:9 / 16:10.
- [x] Some characters appear to be static in certain wide shots.
- [ ] :x: ~When turning to face Dodonna, the player seems to oddly step sideways instead of turning on the spot.~

Module is STUNT_57.

**Comment by DarthParametric** [comment]
The HK arm issue appears to be caused by the stunt model having an incorrect hierarchy. Curiously though, the problem was the head being a direct child of the neck rather than having a dummy in between. The arm bones were actually OK, but apparently the hierarchy change was enough to cause them not to inherit any animation.

**Comment by DarthParametric** [comment]
Some minor camera adjustment masks the floating Dodonna/Council:

![LS_Cutscene_Adjustment](https://user-images.githubusercontent.com/46890653/59086292-ac1eec80-8944-11e9-8fe2-191ba55aa0cc.jpg)

**Comment by DarthParametric** [comment]
Carth has been de-memed:

![Carth_Smile_Meme_Removal](https://user-images.githubusercontent.com/46890653/59086350-d40e5000-8944-11e9-93a2-31da5e4700a3.jpg)

**Comment by DarthParametric** [comment]
Thoughts @JCarter426 @Mako88 ?

https://www.youtube.com/watch?v=BC-MJtIzN3s

**Comment by JCarter426** [comment]
Looks good.
If you upload the ASCII files, I can take a look at why that transition at the end still happens, at some point. But it's far less noticeable than the original anyway.

**Comment by DarthParametric** [comment]
Final (hopefully) version - https://youtu.be/AssYEa9wXSY
