### ISSUE TITLE
Republic is defeated cutscene - various issues

### ISSUE THREAD

**Issue by Kexikus** [KOTORCommunityPatches/K1_Community_Patch#187]
In the cutscene right after defeating Malak in a DS ending there are some issues:

- [x] As usual with republic ships, there are some holes around the door next to Dodonna
- [x] The Republic soldier sitting next to Vandar is sitting in the air. See pic below.

![pS3M2SNl](https://user-images.githubusercontent.com/46890653/59157122-8a5e6a80-8ae8-11e9-84c7-64da51fc3c7c.png)

Module is STUNT_54a.

**Comment by DarthParametric** [comment]
The door issue should already be addressed via the inclusion from JC's Minor Fixes mod. It edits the layout to add in the room behind the door which includes the door frame surrounds.

**Comment by DarthParametric** [comment]
Seated officer stunt model adjusted to plant him in the seat:

![Stunt_Endar_Spire_Seated_Officer_Fix](https://user-images.githubusercontent.com/46890653/59158306-a91a2c80-8afb-11e9-9b15-ae652752984b.jpg)
