### ISSUE TITLE
Korriban Valley of the Dark Lords - Cliff side bad UV appearance

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#191]
- [Initially reported by **djh269** on DeadlyStream](https://deadlystream.com/topic/5385-a-problem-with-the-vanilla-model-texture-for-the-valley-of-the-dark-lords-module/)

- [ ] Apparently there's an issue with the cliff side's appearance of the *Valley of the Dark Lords*﻿ in Korriban -
![VotDL_Cliff_UVW_Issue](https://user-images.githubusercontent.com/50026566/60726372-91e92600-9f65-11e9-8669-5e0dbcf1971a.jpg)

The relevant area model should be `m36aa_01`; as referenced from [DarthParametric's post](https://deadlystream.com/topic/5385-a-problem-with-the-vanilla-model-texture-for-the-valley-of-the-dark-lords-module/?do=findComment&comment=56384).

- #163 for `Various Issues`

**Comment by DarthParametric** [comment]
![Korriban_VOTDL_UV_Fix](https://user-images.githubusercontent.com/46890653/60792767-a9b0ec00-a1a9-11e9-8a09-45588437ffe2.gif)

Made a more refined version than the one in the linked DS post, since that was a bit of a kludge.

**Comment by ebmar** [comment]
Wow, that looks amazing, **DP**! A definite improvement from the former. Hats-off. :100: :+1:

**Comment by DarthParametric** [comment]
Should be continuous UVs across the visible faces now, since the distorted UVs were originally part of a separate island in the vanilla mesh.
