### ISSUE TITLE
Korriban Tomb of Ajunta Pall - Ajunta Pall's sword plot

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#192]
This has been an *issue* for me because I feel something is wrong with it.

So, in the DLG `kor37_freedonnad.dlg` Ajunta Pall talked about -

- E18
> There are... three blades within my sarcophagus. Only one is truly my sword, but it has been so long... I do not remember which.

and the next node which is -

- E19
> Find the sword that is mine and... place it on the statue. If it is truly mine, then it is yours.

but, we happened to get the blades earlier because the conversation triggers after we acquired them. With stripping the `k37_opensarc.ncs` from `kor37_sithsarc.utp`'s `OnOpen` and put it to `kor37_dr_tomb.utd`'s instead will trigger it just before we acquire the blades. The flow of cutscene/conversation could be remedied by triggering the `k37_trg_ajunta.utt` along with the fade-in/out sequence.

I also suspect that the way they do a fade-in/out sequence with the original means there should be an interjection just what we saw with *Rancor VS Grenade feat. Synthesized Odor* on Taris - Upper Sewers - aside of to mask the party jumping and Ajunta Pall's spawn-in.

**Edit**: a reconstruction close to the idea above, with additional adjustments for the rest - https://www.youtube.com/watch?v=QJAohy55KdQ

**Comment by DarthParametric** [comment]
There's nothing mechanically wrong with the scene as it exists. What you propose is entirely down to personal preference and isn't really something for the Community Patch. It's the sort of thing that belongs in a standalone mod.

**Comment by ebmar** [comment]
> There's nothing mechanically wrong with the scene as it exists.

Cool. And yes, nothing really is broke in the first place. Granted, it was all about personal nit-pick-preference ones must say. Cheers! :beers:
