### ISSUE TITLE
Dantooine Grove - Juhani attacks stunned party members

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#195]
I noticed that Juhani diverted her attacks against one of the immobilized NPCs after using Force Push against Player, probably changing default target. After engaging her again, she had once more switched her target while in melee with Player (in my case, it was Carth, to the left of the screen).

I believe it is possible to make her ignore the other two Party Members.

If you like I can try and figure it out. If any of  you is faster at that, please feel free to resolve the issue.

**Comment by DarthParametric** [comment]
Not sure how practical it is, since they are just stunned. They are still alive and considered hostile by Juhani.

**Comment by DarthParametric** [comment]
You could try swapping out her OnHeartbeat for something like this:

```
void main()
{
	object oEnemy = GetAttackTarget(OBJECT_SELF);
	object oPC = GetFirstPC();
	
	if ((GetIsInCombat()) && (oEnemy != oPC))
		{
			ClearAllActions();
			ActionForceMoveToObject(oPC, TRUE, 1.0, 60.0);
			ActionAttack(oPC);
		}
}
```
It won't stop her initiating attacks against the party members, but if she does it will make her stop and attack the PC.

**Comment by Salk73** [comment]
I will give it a try.

**Comment by DarthParametric** [comment]
I doubt you can change the party member's faction, especially not when they are still in the party.

**Comment by JCarter426** [comment]
It should be possible once they've been removed from the party. That also would make the custom module OnDeath script unnecessary, so I wonder why they didn't do that. I'll see if that works, though.

**Comment by Salk73** [comment]
No, it doesn't decompile for me either unfortunately.

I thought I could remove the party members and change their faction inside k_pdan_juhani32.ncs and k_pdan_juhani33.ncs but I was unable to.

**Comment by Salk73** [comment]
Well, with an ugly hack I fixed this locally although I would like to know if any of you knows how to replicate the force field VFX around the paralyzed party members.

Original: https://youtu.be/zrPv41xS70o
Revised: https://youtu.be/NwDdXL62pKU

**Comment by Salk73** [comment]
In the end, everything is fixed here. I did need to create four more triggers to stop the Player from leaving the area and I realize it is a clumsy and inelegant solution. But if there is need for the material produced for this fix, I can provide it of course.

Just let me know.

**Comment by DarthParametric** [comment]
Sounds a bit too hacky for my tastes. But post the files and @Mako88 and @JCarter426 can weigh in with their 2c.

**Comment by Salk73** [comment]
Okay.

Here's a showcase video: https://youtu.be/yd0JyytNxew

I created two custom scripts:

k_pdan_juhani98 which is fired by this line:

DelayCommand(5.0, ExecuteScript("k_pdan_juhani98", OBJECT_INVALID, -1));

added to k_pdan_juhani32.

void main(){
  effect eSFX = EffectVisualEffect(VFX_DUR_HOLD);
  if (IsNPCPartyMember(1)) {
    object oCand = GetObjectByTag("Cand");
    SaveNPCState(1);
    RemovePartyMember(1);
    ChangeToStandardFaction(oCand, 5);
    AssignCommand(oCand, ActionPlayAnimation(19, 1.0, -1.0));
    ApplyEffectToObject(2, eSFX, oCand);
  }
  if (IsNPCPartyMember(2)) {
    object oCarth = GetObjectByTag("Carth");
    SaveNPCState(2);
    RemovePartyMember(2);
    ChangeToStandardFaction(oCarth, 5);
    AssignCommand(oCarth, ActionPlayAnimation(19, 1.0, -1.0));
    ApplyEffectToObject(2, eSFX, oCarth);
  }
  if (IsNPCPartyMember(6)) {
    object oMission = GetObjectByTag("Mission");
    SaveNPCState(6);
    RemovePartyMember(6);
    ChangeToStandardFaction(oMission, 5);
    AssignCommand(oMission, ActionPlayAnimation(19, 1.0, -1.0));
    ApplyEffectToObject(2, eSFX, oMission);
  }
  if (IsNPCPartyMember(7)) {
    SaveNPCState(7);
    object oT3M4 = GetObjectByTag("T3M4");
    RemovePartyMember(7);
    ChangeToStandardFaction(oT3M4, 5);
    AssignCommand(oT3M4, ActionPlayAnimation(19, 1.0, -1.0));
    ApplyEffectToObject(2, eSFX, oT3M4);
  }
  if (IsNPCPartyMember(8)) {
    SaveNPCState(8);
    object oZaalbar = GetObjectByTag("Zaalbar");
    RemovePartyMember(8);
    ChangeToStandardFaction(oZaalbar, 5);
    AssignCommand(oZaalbar, ActionPlayAnimation(19, 1.0, -1.0));
    ApplyEffectToObject(2, eSFX, oZaalbar);
  }
}

and k_pdan_juhani99 which is fired every time dan14_juhani.dlg ends.

void sub1(object oPartyMember, int nPartyNumber);

void sub1(object oPartyMember, int nPartyNumber) {
     AddPartyMember(nPartyNumber, oPartyMember);
     AssignCommand(oPartyMember, ClearAllEffects());
     SetCommandable(1, oPartyMember);
     SetLocalBoolean(oPartyMember, 62, 0);
}

void main() {
 vector vGrove = Vector(441.385559082031, 380.158782958984, 62.5314636230469);
 location lGrove = Location(vGrove, 180.0);
 object oJuhani = GetObjectByTag("dan14_juhani");
 object oPC = GetFirstPC();
 if((GetGlobalNumber("DAN_JEDI_PLOT") < 4) && (GetStandardFaction(oJuhani) == 5)) {
  if(!GetLocalBoolean(oJuhani, 53)) {
   object oPC = GetFirstPC();
   object oCand = GetObjectByTag("Cand");
   object oCarth = GetObjectByTag("Carth");
   object oMission = GetObjectByTag("Mission");
   object oT3M4 = GetObjectByTag("T3M4");
   object oZaalbar = GetObjectByTag("Zaalbar");
   SetLocalBoolean(oJuhani, 53, 1);
   NoClicksFor(3.0);
   SetGlobalFadeOut(0.0, 0.0, 0.0, 0.0, 0.0);
   SetGlobalFadeIn(1.0, 2.0, 0.0, 0.0, 0.0);
   SetCommandable(0, oPC);
   AssignCommand(oJuhani, ActionJumpToLocation(lGrove));
   AssignCommand(oJuhani, ActionPlayAnimation(3, 1.0, (-1.0)));
   if(GetIsObjectValid(oCand)) {
     DestroyObject(oCand, 0.0, TRUE, 0.0);
     object oNewCand = SpawnAvailableNPC(NPC_CANDEROUS, GetLocation(oPC));
     sub1(oNewCand, 1);
   }
   if(GetIsObjectValid(oCarth)) {
     DestroyObject(oCarth, 0.0, TRUE, 0.0);
     object oNewCarth = SpawnAvailableNPC(NPC_CARTH , GetLocation(oPC));
     sub1(oNewCarth, 2);
   }
   if(GetIsObjectValid(oMission)) {
     DestroyObject(oMission, 0.0, TRUE, 0.0);
     object oNewMission = SpawnAvailableNPC(NPC_MISSION, GetLocation(oPC));
     sub1(oMission, 6);
   }
   if(GetIsObjectValid(oT3M4)) {
     DestroyObject(oT3M4, 0.0, TRUE, 0.0);
     object oNewT3M4 = SpawnAvailableNPC(NPC_T3_M4, GetLocation(oPC));
     sub1(oNewT3M4, 7);
   }
   if(GetIsObjectValid(oZaalbar)) {
     DestroyObject(oZaalbar, 0.0, TRUE, 0.0);
     object oNewZaalbar = SpawnAvailableNPC(NPC_ZAALBAR, GetLocation(oPC));
     sub1(oNewZaalbar, 8);
   }
   DelayCommand(2.9, ActionDoCommand(SetCommandable(1, oPC)));
  }
  else {
   AssignCommand(oJuhani, ActionPlayAnimation(3, 1.0, (-1.0)));
  }
 }
}

then I created four new triggers (abort1.utt, abort2.utt, abort3.utt, abort4.utt with their necessary files abort.dlg, k_trg_transfail2.ncs and k_pdan_transabt.ncs).

Lastly, I added the triggers and waypoints to m14ac.git. The files can be downloaded here: https://drive.google.com/open?id=1f_jHLzrZUjnZky6elWFeBb2UlvwkBR2l

**Comment by DarthParametric** [comment]
Wrap your code blocks in three backticks either end (with line breaks).

You could simplify that first script by using the Include functions we added for getting the current party members.

**Comment by Salk73** [comment]
Thanks for the tips.

Yes, I could have used the function in your include to save a few lines of code but it would make little difference.

**Comment by Mako88** [comment]
I like the idea in principle. I feel like it's a lot of files for the change it makes, so if it would be possible to reduce the footprint of the changes, that'd be ideal.

I also think changing the wording when trying to leave the area would be good. Maybe something more like "You need to resolve the situation with Juhani" rather than "defeat her in battle".

**Comment by Salk73** [comment]
The wording can be changed easily of course. 

There is a way to cut considerably the amount of files too. It is possible to create one single trigger around the grove area and have an OnExit script keeping you from leaving that area as opposed to one for each single exit. I like the latter solution better but I agree it's lots of file for a small change.

**Comment by DarthParametric** [comment]
The proposed solution is far too intrusive for inclusion in the Community Patch.
