### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by gnutix** [KOTORCommunityPatches/K1_Community_Patch#198]
Today I've just discovered this amazing project and the Steam Play + Proton combo (that finally allows me to play this game on my Linux setup).

However, looking at the README, I see instructions based on an "installer.exe". How about installing it for Linux ? Is it possible ?

And if you've got instructions for installing `K1R 1.2` on Linux too, that would be awesome. :)

**Comment by JCarter426** [comment]
Like most KOTOR mods, the Community Patch installs with TSLPatcher, which was made not by us, but by a kind Swedish lady who hasn't been seen for many moons and there is no official Linux version of it. Your best bet would be to try running it through Wine or on a virtual machine.

**Comment by gnutix** [comment]
Thanks for the suggestion. Apparently I'm not the first one to need it : https://www.reddit.com/r/kotor/comments/54z3od/tsl_patcher_with_kotor_2_for_linux/

Apparently [@Fair Strides](https://deadlystream.com/profile/9107-fair-strides/) had access to TSLPatcher's source code (and said it'd be hard to do a Mac/Linux port) : https://deadlystream.com/topic/4098-using-tsl-patcher-without-kotor-on-desktop/?tab=comments#comment-42548

**Comment by JCarter426** [comment]
Yeah, Fair Strides provided the updated version that the Community Patch uses and was working on more updates, but he's busy being a real programmer or something silly like that.

**Comment by gnutix** [comment]
For anyone looking for a solution, [here it is](https://deadlystream.com/topic/7291-install-k1rk1cp-that-use-tslpatcher-on-linux/?tab=comments#comment-72752).

**Comment by craigmasonnc** [comment]
> I was able to install the patch 1.8.1 easily using protontricks.
> 
>     1. Launch Kotor once to create the wine prefix
> 
>     2. Create a temporary symlink to the kotor folder as the patch installer's file browser doesn't show hidden folders:
>        ```shell
>        ln -s ~/.local/share/Steam/steamapps/common/swkotor ~/kotor
>        ```
> 
>     3. Run the installer using protontricks:
>        ```shell
>        protontricks -c "wine /path/to/K1CP/INSTALL.exe" 32370
>        ```
> 
>     4. When the installer asks for the game folder, navigate to `My Computer\Z:\home\$USER\kotor`.
> 
> 
> Took about 5min. You can delete the symlink after.
> 
> Can also be done without protontricks of course, if you manually specify the wine envvars, path to the prefix, path to the proton wine binary etc.
> 
> protontricks 1.6, Proton 6.3-6

I was able to follow these instructions, but with the following two differences which might be useful to the next guy who comes along

1. I wasn't able to see `~/kotor` from the installer, so instead I created a symlink like so:
 ```shell
ln -s ~/.local/share/Steam/steamapps/common/swkotor ~/Desktop/kotor
```
2. I just double-clicked / right-clicked -> open with protontricks on the INSTALL.exe to use the protontricks gui, then selected Star Wars Kotor 32370 - this works just as well as protontricks in the terminal

Another note, I was able to load my saves properly by manually copying them from my PC to the deck.  For whatever reason, the steam auto copied only 1 save and it wouldn't load properly.

**Comment by MonstraG** [comment]
Following the previous dude:

1. created the desktop symlink:
```
ln -s ~/.local/share/Steam/steamapps/common/swkotor ~/Desktop/kotor
```

2. Also right-clicked, and run trough `protontricks` instead of command line, selecting `Star Wars Kotor 32370` too. `protontricks` crashed on first try, turns out I had old version of them, and needed version 1.12.

When selecting location of the folder I clicked trough 
```
Z:\home\USER\Desktop\kotor
```
after that I finally was able to escape white void

Thanks to previous 2 dudes!

**Comment by th3w1zard1** [comment]
if anyone comes across this thread in the future, while the above strategies may work they are highly unintuitive and unnecessary.

K1CP swapped to [*the tslpatcher replacement **HoloPatcher***](https://github.com/NickHugi/PyKotor/wiki/Installing-Mods-with-HoloPatcher). It is an os-native platform-agnostic drop in replacement of TSLPatcher written in Python. You can run it **without wine or protontricks** and without worrying about any of these custom terminal commands.

Get it here: https://github.com/NickHugi/PyKotor/releases

**Comment by th3w1zard1** [comment]
Hey you might be right, perhaps I'm not as familiar with winetricks/proton. Thank you for the feedback, communication isn't my strong suit or I'd have tried to provide better documentation with the app for scenarios such as this.

Does HoloPatcher work under that method out of curiosity, with that 2023 version specified, under protontricks? I would just like to clarify.

disclaimer: I am an active maintainer of HoloPatcher and the PyKotor project.
