### ISSUE TITLE
Carth out of the loop

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#2]
Carth talks about being left out of the loop as soon as you've gotten the star map on Dantooine, instead of waiting until after you've met with the council again.

**Comment by JCarter426** [comment]
[k_swg_carth06.txt](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/2798314/k_swg_carth06.txt)
Put Carth back in the loop.

**Comment by DarthParametric** [comment]
Due to a change in the starting conditional, Carth can wind up non-communicative when one of the banter triggers on Dantooine fires. Requires an edit of k_trg_partyinit to account for the change.

Reported by Gebangi [on /r/kotor](https://old.reddit.com/r/kotor/comments/ix2p22/the_game_told_me_something_was_bothering_carth/).
