### ISSUE TITLE
Korriban Sith Academy - Carth lacks a quest state to address the death of Dustil

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#202]
If you kill Dustil in the Sith Academy, his OnDeath script sets Carth's personal quest to stage 99:

`Carth and you have nothing more to talk about, for the moment.`

This is despite Carth actually having a specific conversation for this event, where he blames the player. It seems logical that there should be an intermediate quest state to suggest that the player talk to Carth about Dustil's death, and then set the state to 99 after that talk. 

Edit: Since we have new added states for the Dustil quest, maybe it would be better to use those. They could be left open (with an addendum about speaking to Carth) and then closed after talking to Carth.

**Comment by JCarter426** [comment]
This happens if you kill Dustil normally as well, via `k_swg_dustil99` fired from `k_hdustil_dialog.dlg`.

**Comment by DarthParametric** [comment]
Possible candidate for inclusion in N-DReW25's [Unofficial Tweak Pack](https://deadlystream.com/files/file/2081-unofficial-k1cp-tweak-pack/).
