### ISSUE TITLE
Kashyyyk Great Walkway - Dark Jedis won't attack

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#205]
This may be a rather common occurrence but it's annoying nevertheless.

The script fired at the end of the dialogue is ironically enough called k_pkas_sithattk.

Video: https://youtu.be/tDEqgQwyb4E

**Comment by DarthParametric** [comment]
The vanilla script is:

```
#include "k_inc_generic"

void main() {
	
	object oDrkJedi2 = GetObjectByTag("kas22_darkjedi02", 0);
	object oDrkJedi3 = GetObjectByTag("kas22_darkjedi03", 0);
	
	ChangeToStandardFaction(oDrkJedi2, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(oDrkJedi3, STANDARD_FACTION_HOSTILE_1);
	ChangeToStandardFaction(OBJECT_SELF, STANDARD_FACTION_HOSTILE_1);
	
	AssignCommand(oDrkJedi2, DelayCommand(1.0, GN_DetermineCombatRound(OBJECT_INVALID)));
	AssignCommand(oDrkJedi3, DelayCommand(1.0, GN_DetermineCombatRound(OBJECT_INVALID)));
	DelayCommand(1.0, GN_DetermineCombatRound(OBJECT_INVALID));
}
```
That should work, but perhaps switching to `GN_DetermineCombatRound(oPC)` would be in order. Try this and see what happens.

[k_pkas_sithattk.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3512749/k_pkas_sithattk.zip)

**Comment by Mako88** [comment]
From the look of the video, it may not be a problem with the script, but rather that the trigger is far enough away that when they go hostile they can't "see" you to attack. Maybe it would make sense to move the trigger closer to their spawn point?

**Comment by DarthParametric** [comment]
I assume it was probably on purpose to allow the player to initiate combat. Compared to say the Tatooine one where you get dumped straight on top of them.

**Comment by DarthParametric** [comment]
Just got around to checking this in-game. They attack me as soon as the cutscene ends, despite not moving after hitting the trigger. Everything looks to be working exactly as intended. Unless there is compelling evidence to the contrary, I am going to consider this a non-issue.
