### ISSUE TITLE
Upper Shadowlands - One issue with katarns spawn

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#207]
There is a problem with the original k_pkas_dire_01 script:

```
void main() {
	object oPC = GetFirstPC();
	object oEntering = GetEnteringObject();
	object oKas22_dire_01 = GetWaypointByTag("kas22_dire_01");
	location location1 = GetLocation(oKas22_dire_01);
	int int1 = ((GetLevelByPosition(1, oPC) + GetLevelByPosition(2, oPC)) + GetLevelByPosition(3, oPC));
	if ((IsObjectPartyMember(oEntering) == 1)) {
		if ((int1 > 11)) {
			if ((int1 > 14)) {
				CreateObject(1, "kas24_katarn03", location1, 0);
			}
			CreateObject(1, "kas2_katarn_02", location1, 0);
			CreateObject(1, "kas2_katarn_02", location1, 0);
			CreateObject(1, "kas24_katarn03", location1, 0);
		}
		else {
			CreateObject(1, "kas2_katarn_01", location1, 0);
			CreateObject(1, "kas2_katarn_02", location1, 0);
			CreateObject(1, "kas2_katarn_02", location1, 0);
		}
		DestroyObject(OBJECT_SELF, 0.0, 0, 0.0);
	}
}
```

It uses the wrong creature "kas24_katarn03" which is the weak version used for Jolee's cutscene

This is my proposed change:

```
void main() {
	object oPC = GetFirstPC();
	object oEntering = GetEnteringObject();
	object oKas22_dire_01 = GetWaypointByTag("kas22_dire_01");
	location location1 = GetLocation(oKas22_dire_01);
	int int1 = ((GetLevelByPosition(1, oPC) + GetLevelByPosition(2, oPC)) + GetLevelByPosition(3, oPC));
	if ((IsObjectPartyMember(oEntering) == 1)) {
		if ((int1 > 11)) {
			if ((int1 > 14)) {
				CreateObject(1, "kas2_katarn_01", location1, 0);
			}
			CreateObject(1, "kas2_katarn_02", location1, 0);
			CreateObject(1, "kas2_katarn_02", location1, 0);
			CreateObject(1, "kas2_katarn_01", location1, 0);
		}
		else {
			CreateObject(1, "kas2_katarn_02", location1, 0);
			CreateObject(1, "kas2_katarn_01", location1, 0);
			CreateObject(1, "kas2_katarn_01", location1, 0);
		}
		DestroyObject(OBJECT_SELF, 0.0, 0, 0.0);
	}
}
```

**Comment by DarthParametric** [comment]
> It spawns only one of such wrong creature for the highest level of the Player

No it doesn't. It spawns an _additional_ one of those for players over level 14. They still get the 2 x katarn_02 and 1 x katarn03  (so two total) for players greater than level 11 as well. The only change that needs to be made is the ResRef.

**Comment by Salk73** [comment]
Yes, I noticed soon after writing that thus my edit.

One less bug though... ;-)

**Comment by Salk73** [comment]
There is another issue with those creatures so ironically enough the original title would have been right.

The spawn script sets, probably because of a typo, the OnDeath flag to 1 rather than the Heartbeat flag, meaning that the creatures don't do the randomwalk routine in their UD script.

Easy fix: change boolean value from 27 to 28.

**Comment by Salk73** [comment]
Actually this is going to go under "Won't Fix" because there is no bug.

The spawned katarn is not the weak version (_kas24_katarn_03_) but a normal version with a name that is almost identical (_kas24_katarn03_).

My bad.
