### ISSUE TITLE
Missing quest reward on Manaan

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#209]
Reported by djh269:
> Manaan Republic Representative reward change: 
> - In the vanilla reward script after you complete the main quest on Manaan you are provided with 500 credits, Cardio Power System and the line: g_w_sonicrfl003, which isn't an item template in the game. So I've changed it to the Arkanian Sonic Rifle's UTI (g_w_sonicrfl03).
>

**Comment by DarthParametric** [comment]
The script is k_pman_temp01 that fires on Entry 99 of man26_repdip.dlg in manm26ae (Manaan East Central).

```
void main() {
	
	CreateItemOnObject("g_w_sonicrfl003", GetPCSpeaker(), 1);
	CreateItemOnObject("g_i_implant305", GetPCSpeaker(), 1);
	GiveGoldToCreature(GetPCSpeaker(), 500);
}
```
