### ISSUE TITLE
Removing Sand People disguises can crash the game

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#21]
If you remove a Sand Person disguise and then exit an area, there's a good chance the game will crash. I believe this is triggered by the OnExit script for the area (which is identical to the heartbeat script) but I don't know what in there would cause the game to crash.

**Comment by DarthParametric** [comment]
Is this avoidable by removing the disguise, saving, exiting, reloading, then transitioning?

**Comment by DarthParametric** [comment]
Something left in memory then?

**Comment by JCarter426** [comment]
My best guess is that while the heartbeat code is running, objects are deleted on account of the new level being loaded. And the game crashes because something is being deleted while it's in the middle of doing something.

But I have no idea how to fix that. Presumably it's supposed to fire that script on exit.

**Comment by JCarter426** [comment]
Since this may be an engine issue and we see no way to fix it at the moment, I'm calling this one closed. It's unfixable unless new information can shed light on the matter.
