### ISSUE TITLE
Upper Shadowlands: wrong replies for tach glands sale

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#212]
There is a problem in kas24_poffice_01.dlg.

R31 and R32 rely on two scripts (k_pkas_yespoach1.ncs and k_pkas_yespoachx.ncs) to make the replies mutually exclusive when Player sells the glands.

In theory R31 should be available if the Player has only one gland in the inventory and R32 if there are more.

Due to the same bug in both scripts, R31 is the only reply, no matter how many glands have been harvested.

Easy fix. Change the following line in both scripts:

`int1 = (int1 +1);`

to:

`int1 = GetNumStackedItems(oInvItem);`

**Comment by DarthParametric** [comment]
It's using the Utility function `UT_GetNumItems`. I would change it to use this instead:

```
int GetStackSize(object oTarget, string sItemTag) {
	
	object oItem = GetItemPossessedBy(oTarget, sItemTag);
	int nCount = 0;
	
	if(GetIsObjectValid(oItem))
		{
			nCount = GetNumStackedItems(oItem);
		}
	
	return nCount;
}
```

**Comment by Salk73** [comment]
Oh okay.

That will work too, of course.

**Comment by DarthParametric** [comment]
If you can test them and confirm that they work, then we'll add them in.

[Poach_Scripts.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3534237/Poach_Scripts.zip)

**Comment by Salk73** [comment]
Worked fine.

Thanks.
