### ISSUE TITLE
Tatooine Dune Sea - Weakling PCs can suffer a premature death during the Gamorrean ambush

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#216]
The ambush cutscene in tat_m18aa (Dune Sea), where the party is lured in by a recorded woman's cry for help, can result in the player being killed when the mine is detonated at the start of the scene. It has a fixed damage amount of 60, so can kill anyone with low health. The script should be amended to switch to a variable amount based on the player's current health value. The presumable design intent was for the party to merely be slightly injured. You can't extort a corpse.

Edit: It should be noted that this ambush is more dangerous than stepping on a Deadly Frag Mine, since that only does 54 damage with the chance of a Reflex save for half damage. 

Reported by @JCarter426

**Comment by DarthParametric** [comment]
The script in question is k_ptat_ambushgo2. One possible solution:

```
void main() {
	
	object oPC = GetFirstPC();
	object oDroid = GetObjectByTag("kas18_ambush_drd", 0);
	int nCurHP = GetCurrentHitPoints(oPC);
	int nDamage;
	
	if ((nCurHP < 65) && (nCurHP > 15))
		{
			nDamage = nCurHP - 10;
		}
		
		else if (nCurHP <= 15)
			{
				nDamage = 0;
			}
		
			else nDamage = 60;
	
	ActionPauseConversation();
	
	DestroyObject(oDroid, 1.5, TRUE, 0.0);
	ApplyEffectAtLocation(DURATION_TYPE_INSTANT, EffectVisualEffect(VFX_FNF_GRENADE_FRAGMENTATION, FALSE), GetLocation(oDroid), 0.0);
	ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(nDamage, DAMAGE_TYPE_UNIVERSAL, DAMAGE_POWER_NORMAL), oPC, 0.0);
	
	DelayCommand(1.0, ActionResumeConversation());
}
```

**Comment by Salk73** [comment]
My 2 cents is to go for a percentage of the current HPs.
