### ISSUE TITLE
Tatooine Dune Sea - Desert Wraid never spawn

### ISSUE THREAD

**Issue by Snigaroo** [KOTORCommunityPatches/K1_Community_Patch#218]

**Comment by JCarter426** [comment]
Possibly my fault with the OnEnter scripts.

**Comment by DarthParametric** [comment]
While I see wraid, they do not appear to be following their usual patrol AI. They are just sitting in one spot.

**Comment by DarthParametric** [comment]
It was difficult to get a video from far away, as I got attacked by about half a dozen random Sand People spawns (so no problems with that working at least), but here are the Wraid when entering the Dune Sea for the first time - https://www.youtube.com/watch?v=nBte_zvr3uI

One other thing I noticed, and I'm not sure if this also happens in the pure vanilla game, but while the Wraid patrol around on subsequent visits to the module, it seems that you can attack them piecemeal by aggroing the tail-end one or two while the rest keep going. I was sure that in the past they always all attacked together, but I could be mistaken (and I don't know what we would have changed that would alter it).

**Comment by JCarter426** [comment]
I've confirmed the wraid don't follow their AI on the first visit, but do on subsequent visits. But I've also confirmed that the module scripts aren't responsible. Is there anything else affecting wraid in the Community Patch?

**Comment by DarthParametric** [comment]
Should only be textures as far as I am aware. It worked fine in the previous build, so whatever it was is only a recent addition.

**Comment by DarthParametric** [comment]
Looking at the UTCs, all their scripts are generic vanilla ones except the module specific OnSpawn, `k_ptat_wraidspwn`. 

```
#include "k_inc_generic"

void main() {
	
	GN_SetSpawnInCondition(SW_FLAG_DYNAMIC_COMBAT_ZONE, TRUE);
	GN_SetDayNightPresence(AMBIENT_PRESENCE_ALWAYS_PRESENT);
	GN_SetListeningPatterns();
	GN_WalkWayPoints);
}
```

But we haven't touched that at all.

**Comment by DarthParametric** [comment]
I just tried this in a completely vanilla game and the Wraid still don't do anything on the first entrance to the Dune Sea. So this is actually a vanilla bug, not something we broke.

**Comment by DarthParametric** [comment]
Hah, this is a ridiculously simple problem. There a are six Wraid UTCs. Three are used in the initial spawn, the other three used in subsequent spawns. The ones used in the initial spawn all lack an OnDialogueEnd script. The other three UTCs use the generic `k_def_endconv`. If you add that to the UTCs of the initial spawn, then suddenly they walk their waypoints as intended. I assume the initial scene with Marlena on the first entrance to the module is causing all AI to cease, but when the conversation ends they have nothing to tell them to resume, so they sit idle until the player gets to within perception range.

**Comment by DarthParametric** [comment]
Splitting this off into its own issue, since this issue was originally for a bug we created.
