### ISSUE TITLE
Tatooine Eastern Dune Sea - Bastila's Father's Holocron Pickup Issues

### ISSUE THREAD

**Issue by Snigaroo** [KOTORCommunityPatches/K1_Community_Patch#219]
The holocron remains in the loot pile after attempting to acquire it. I opened the pile, hit loot, and Bastila began speaking about the holocron. After re-opening the container, the holocron was still present. Didn't test if it somehow duped the holocron and gave it the first time or not.

**Comment by DarthParametric** [comment]
Altering the OnClosed script should prevent the conversation from firing without possessing the Holocron:

```
void main() {
	
	object oBackpack = GetObjectByTag("K_SWG_HELENA01", 0);
	object oBastila = GetObjectByTag("bastila", 0);
	object oPC = GetFirstPC();
	object oHolocron = GetObjectByTag("holocron");
	object oHasItem = GetItemPossessedBy(oPC, oHolocron);
	int nTalked = GetGlobalBoolean("K_SWG_BASTILA_HOLO");
	
	if (((nTalked == FALSE) && (GetIsObjectValid(oBastila)) && (GetIsObjectValid(oHasItem)))
		{
			AssignCommand(oBackpack, ActionStartConversation(oPC, "tat18_bastila"));
		}
}
```

There may need to be an addition that also checks the placeable for a duplicate, if that issue is confirmed.
