### ISSUE TITLE
Tatooine Sandpeople Enclave - Sandpeople Storyteller Repeats Outsiders Section

### ISSUE THREAD

**Issue by Snigaroo** [KOTORCommunityPatches/K1_Community_Patch#221]
If you request of HK-47 to hear the entire section of the Long Walk as related by the Storyteller, he immediately cuts into the Outsiders section of his dialogue after a black screen, representing hours of discussing the Long Walk. But despite giving the Outsiders dialogue at this time, you can't ask the Storyteller about the Outsiders section of the history until you "continue" with the history, which just causes HK-47 to repeat the Outsiders section you already heard.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] In addition to the above, the party also needs to be jumped for his conversations.
