### ISSUE TITLE
Republic Soldier Corpse in the First Hrackert Rift Module Appears to be Levitating

### ISSUE THREAD

**Issue by Snigaroo** [KOTORCommunityPatches/K1_Community_Patch#222]
It's the first hallway into the facility, just beyond the panicked mercenary. It could be the result of some of the model changes I'm using I guess, but it appears to be levitating about a foot off the floor.

**Comment by DarthParametric** [comment]
Picture?

**Comment by Snigaroo** [comment]
![spoopy](https://user-images.githubusercontent.com/5841974/64484232-570da380-d1dd-11e9-9095-de8d27d3658f.jpg)

It's difficult for me to take ingame screenshots so that's the best I can do.

**Comment by Snigaroo** [comment]
![spoopy2](https://user-images.githubusercontent.com/5841974/64484271-b2d82c80-d1dd-11e9-82f9-a420ce8c23c5.jpg)

A second instance, I think more egregious. This time Jolee is standing directly next to the corpse.

**Comment by DarthParametric** [comment]
I don't see any floating on my end.

![Manaan_Corpses](https://user-images.githubusercontent.com/46890653/64484306-7b0bcc00-d253-11e9-856d-3b3408704b50.jpg)

The ones you are referring to are characters with spawn dead scripts, so they should obey normal collision. The angles in your screenshots make it difficult to see any floating.

**Comment by JCarter426** [comment]
Looks like it's the placeable version, plc_rsldcrps, so it must just be bad Z-coordinates.

**Comment by Snigaroo** [comment]
It's possible my models have something to do with it, as I said.

**Comment by DarthParametric** [comment]
Yeah I see it now. The first one is more like 6" or so, which is why I didn't notice. It also has no collision, which is odd, but I guess intentional on Bioware's part.

**Comment by JCarter426** [comment]
Since it's the placeable version, my soldier fix shouldn't be affecting it. Also I uninstalled just to be safe, and I do see it on my end:
![swkotor 2019-09-08 02-21-56-76](https://user-images.githubusercontent.com/46898647/64484430-ba98d080-d1df-11e9-86cc-227c63776cc0.png)

**Comment by DarthParametric** [comment]
Seems as though a couple of footlockers also have the floating disease. These are all AFP changes from previous versions, so I'm surprised it took this long to be reported.
