### ISSUE TITLE
Manaan Hrakert Station - Assault Droids use melee attacks

### ISSUE THREAD

**Issue by Snigaroo** [KOTORCommunityPatches/K1_Community_Patch#223]
Despite having blasters equipped, Assault Droids in the room just beyond the Faulty Repair Droid use melee attacks

**Comment by DarthParametric** [comment]
Location?

**Comment by Snigaroo** [comment]
Right, forgot. Hrackert Rift, first module (the same one as the previous reported error). I'm not sure the name of that first module or I'd edit it into the title.

**Comment by DarthParametric** [comment]
The blasters are part of the model and serve no functional purpose beyond aesthetics. This will likely be a case of the UTC lacking an actual equipped weapon UTI (the same problem as one of the droids in the Vulkar base on Taris).
