### ISSUE TITLE
Manaan Hrakert Station - One of Bandon's Sith Refuses to Attack

### ISSUE THREAD

**Issue by Snigaroo** [KOTORCommunityPatches/K1_Community_Patch#224]
![Bandons sith on strike](https://user-images.githubusercontent.com/5841974/64484543-9b02a780-d1e1-11e9-8e93-5a03e1bc14ff.jpg)

The man's gone on strike. This could totally be a build issue, but in case it's not I figured to report it.

**Comment by DarthParametric** [comment]
This will be a script issue with it failing to turn him hostile. The scripts were edited to prevent them going hostile too early, but it seems to have broken on your end for some reason.

**Comment by DarthParametric** [comment]
Ah, I think I see the problem. I didn't change the script, I just changed the default faction of the UTCs. In vanilla they both start out as hostile, but it seems like there's an incorrect tag in the script. It worked in vanilla because the were already hostile, so the broken script didn't matter.
