### ISSUE TITLE
Korriban Sith Academy - Open prestige quests are not closed once sufficient prestige is obtained

### ISSUE THREAD

**Issue by Snigaroo** [KOTORCommunityPatches/K1_Community_Patch#225]
If the "Aiding Lashowe" quest is advanced to the quest stage where you've killed the Tuk'ata and then killed Lashowe but choose not to turn it in before otherwise attaining sufficient prestige to gain the nomination as a Sith from Uthar, the quest will never remove itself from your journal.

**Comment by DarthParametric** [comment]
It appears only quests you actively submit to Uthar are closed. All other quests will remain open, even after you have finished Korriban.

**Comment by DarthParametric** [comment]
These are the specific prestige quests:

- A Doubting Sith
- Aiding Lashowe
- Renegade Sith
- Rogue Droid
- The Code of the Sith
- The Hermit in the Hills
- The Mandalorian Weapons Cache
- The Sword of Ajunta Pall

There are also the two quests related to betraying one or both of Uthar/Yuthura. These should be closed if you give the datapad to Adrenas/put the device in Uthar's bed, but I don't know if they remain open if you fail to do that before heading to the Tomb of Naga Sadow:

- The Double-Cross
- The Double-Double-Cross

It appears the the global quest may also fail to be closed under some circumstances (notably when betraying both parties). at least before clearing out the Academy itself:

- The Way of the Sith
