### ISSUE TITLE
Unknown World - When Force Persuading Zaalbar to Kill Mission, Canderous Activates an Equipped Shield

### ISSUE THREAD

**Issue by Snigaroo** [KOTORCommunityPatches/K1_Community_Patch#226]
This could possibly apply to the droids as well if they have anything equipped (I don't think mine did).

**Comment by DarthParametric** [comment]
Zaalbar and Mission are set to factions `STANDARD_FACTION_FRIENDLY_1` and `STANDARD_FACTION_FRIENDLY_2`, respectively, so neither should be considered hostile to the party (which would be what I would expect would cause the shield activation).

**Comment by DarthParametric** [comment]
Calling this closed for now, since it was not able to be reproduced. This entire scene needs to be addressed at some point, per #168, but that's for a future release.

**Comment by DarthParametric** [comment]
I did hear a shield activate in the background on this playthrough, although Canderous didn't visibly show anything. Possibly it was HK? As per the above, I'll see what shakes out come the changes due in v1.9.

**Comment by DarthParametric** [comment]
So I can confirm I have HK activating his shield when getting Zaalbar to kill Mission. I believe this is probably the same issue as #431. For some reason the AI can be randomly triggered by combat when they shouldn't. We can disable the party member's AI for the scene of Zaalbar killing Mission, or try changing it to a fake scripted cutscene attack. I'll add it to #168 for resolution during the rest of the scene.
