### ISSUE TITLE
Kashyyyk Landing Pad - Couple of issues with Matton/Eli dialogue 

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#228]
Hello!

Two problems:

- [ ] There is a game breaking bug when Eli tries to leave but there are obstacles (party members) on his path. If that happens the screen stays black and the script doesn't ever advance the dialogue. An easy fix is to add a delay of 3 seconds to ActionResumeConversation() in k_pkas_elileave.ncs.
- [ ] R53 has an inconsistent follow-up if Zaalbar is not in the party. I remedied by replacing it with a duplicate of E57 instead which I then linked to R55.

===========
_**DP - This is a sub-issue of #118**_

**Comment by DarthParametric** [comment]
In regards to Eli, a better solution would be to just destroy him under the fade to black. Otherwise he will presumably be doing the circle dance around the companions after the conversation ends.

**Comment by Salk73** [comment]
The next script (_k_pkas_eligone_) already destroys Eli too but I guess it is fine.

**Comment by Salk73** [comment]
The flow of the dialogue, without Zaalbar and with Player suggesting to kill Eli is like this in the vanilla game:

- (Eli) Well, that is... uh... It's not how it looks. You see, a good mechanic is hard to find and...
- (Matton) And what? I thought I owed you! You tricked them into the Shadowlands and killed them all while I fixed your freighter in orbit!
- (Player) Kill him, Matton. You know he deserves it after what he's done to your crew mates.
- (Matton) **This is business? Maybe in Hutt Space, but not here! Not with me!**

The last line is completely arbitrary and makes sense only if there is Zaalbar in the party because then before it becomes like this:

- (Player) Kill him, Matton. You know he deserves it after what he's done to your crew mates.
- (Zaalbar) You outsiders even cheat each other! No wonder you give no thought to my people!
- (Eli) Whatever your Wookiee is saying, he's not helping diffuse the situation. This is just a simple business matter.
- (Matton) **This is business? Maybe in Hutt Space, but not here! Not with me!**

So I changed it to become like this:

- (Eli) Well, that is... uh... It's not how it looks. You see, a good mechanic is hard to find and...
- (Matton) And what? I thought I owed you! You tricked them into the Shadowlands and killed them all while I fixed your freighter in orbit!
- (Player) Kill him, Matton. You know he deserves it after what he's done to your crew mates.
**- (Eli) Now keep your head, Matton. It was just business.**
- (Matton) **This is business? Maybe in Hutt Space, but not here! Not with me!**

It makes way much more sense, in my opinion.

**Comment by DarthParametric** [comment]
Ah, I thought you were just redirecting it to the vanilla node so that he would leave instead of being killed. Duplicating the node and inserting it ahead of the existing end node for killing him sounds fine.

**Comment by DarthParametric** [comment]
Checking the scene in-game, it seems he runs off towards the Great Walkway entrance, so jumping the party into position is also a possibility. That was already under consideration anyway, given other problems with that conversation.

**Comment by DarthParametric** [comment]
Closing and merging into #118
