### ISSUE TITLE
Taris Upper City Hideout - Gap in wall behind bed

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#231]
There is a gap in the left-hand back wall of the bed recess that is visible during the post-vision conversation with Carth (and afterwards). The relevant room model needs vert repositioning and/or black boxing.

**Comment by DarthParametric** [comment]
Alternative option.

There are some beds modelled into those recesses in the wall. However, presumably due to walkmesh issues, they ended up just dumping some placeable beds in front of them for the waking up scene (although the lightmapping is pretty dark, so they are hard to spot at a glance):

![Taris_Hideout_Fake_Beds](https://user-images.githubusercontent.com/46890653/65216646-03f8f200-daf5-11e9-924e-62ccd26436ea.jpg)

I figure that section should probably just be replaced with sections that match the walls either side, like so:

![Taris_Hideout_Fake_Beds_Walled_Off](https://user-images.githubusercontent.com/46890653/65216655-0a876980-daf5-11e9-9c36-b93acc52a92a.jpg)

That also fixes the gap at the same time. Although presumably @JCarter426 's dream sequence mod would need a compatibility patch.

**Comment by Salk73** [comment]
I find the alternative option pretty elegant.

**Comment by JCarter426** [comment]
```That also fixes the gap at the same time. Although presumably @JCarter426 's dream sequence mod would need a compatibility patch. Edit: Seems not, based on a quick check.```
Yeah, it uses an instance of the room model so all is well.
