### ISSUE TITLE
Czerka Ithorian on Kashyyyk may walk away prematurely

### ISSUE THREAD

**Issue by Mako88** [KOTORCommunityPatches/K1_Community_Patch#24]
Reported here: https://deadlystream.com/topic/6923-kotor-manaan-docking-bugs/

It appears that when talking to Janos, the Czerka Ithorian collecting docking fees, leave the planet, and return he will walk away after you refuse to pay instead of making you leave again.

Alternatively it may be that when you talk to him, go to another planet, and talk to him there this happens.

**Comment by DarthParametric** [comment]
As per #23, this issue is actually on Kashyyyk, not Manaan. Editing title and first post to reflect that.
