### ISSUE TITLE
Taris Black Vulkar Base (Garage) - More mooks attack with fists

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#240]
- [x] Two mooks in room next to Garage Head's office attack with fists.
- [x] Three mooks in rooms on opposite side to accelerator room (workbench is in one) all attack with fists. The two Duros are working on swoops though, which would be weird with pre-equipped weapons. Maybe they need to be neutral and get switched with a trigger or something.
- [x] The revised OUD approach requires moving the mooks around slightly so they aren't too close to/don't have their back to the doors. While at it, might as well reposition the two swoop bikes so they align properly with their designated pads and leave enough room to path around.

Edit: All these mooks are pantomiming working on something, hence why they are unarmed.

**Comment by Salk73** [comment]
I think we are once again facing a general AI issue with the combat routine.

During my testing in this specific case I noticed how the mooks you reported fighting with fists correctly use their weapons instead. My guess is that sometimes the AI master skips the wielding weapon action and goes straight for the Attack. If that happens, the NPC won't ever equip his weapon even if a weapon is in the inventory and the right proficiency is set.

We would need an overhaul of the general AI routine but that is way beyond my capabilities.

**Comment by DarthParametric** [comment]
That's why I suggested for the Duros at least that they could probably spawn neutral and then be triggered to turn hostile. That way they could be forcibly equipped before attacking. The others can probably just be spawned already equipped/forced to equip by their OnSpawn, as we have already done previously in the Vulkar base (and elsewhere, like Davik's estate).

**Comment by DarthParametric** [comment]
There are three instances of `tar10_vulkgang.utc` and two instances of `tar10_vulkgan001.utc` which all use the same UserDefine `k_ptar_mech01_ud`. This has an OnHeartbeat event that forces them to face the nearest swoop bike and do the `ANIMATION_LOOPING_USE_COMPUTER` anim while not in combat. Since they are all contained inside small rooms with closed but unlocked doors, seems like the easier solution would be to set them to neutral, then have the doors fire an OnOpened script that triggers the nearest unarmed Vulkars to equip a weapon and switch factions. But there's a computer command to open all doors in the base, so that doesn't seem the best approach. There's the `KOTOR_DEFAULT_EVENT_ON_PERCEPTION`, but I ran into trouble getting that to work properly with Xor, so I don't know about that. Although maybe it could use `GetLastPerceptionSeen`. 

Seems like the most reliable approach would be to simply use a trigger inside each room. If going this route, the southern ones would probably need the spawn in positions altered to move them back away from the doorways in order to give the script time to kick in when the party enters. Might also need additional triggers outside the doorways that would fire if the doors were already open. That's a whole _bunch_ of extra GIT data though (7 triggers), so the OUD approach would be a lot more compact.

**Comment by DarthParametric** [comment]
As per my prior experiences, after some testing it seems like creatures are _extremely_ flaky when it comes to perception events. Sometimes they won't trigger at all, or they will only do so after some extended period of time (e.g. not triggering `GetLastPerceptionSeen` when the player is standing right in front of them). You can add a backup heartbeat event to turn them hostile if a PC is within X number of meters, but you can be standing next to them for an extended period before that seems to kick in.

**Comment by DarthParametric** [comment]
1.10.0 beta test observations:

- [ ] The current implementation seems too unreliable. Investigate firing via door OnOpens, or added triggers as a last resort.
