### ISSUE TITLE
Taris Upper City Cantina - Player does nothing during their dueling ring introduction

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#243]
At the start of each duel, the opponent does the Victory animation when their name is announced, but the player just stands there during their introduction. It seems like they should also perform the anim.

And while at it, a custom `ActionPauseConversation` delay could be added to the opponent introductions, since currently a couple of them switch to the next node a bit too quickly given the adjusted animation timings.

**Comment by Salk73** [comment]
If I am not mistaken, you have added the Victory animation in your stand alone modification, right?

**Comment by DarthParametric** [comment]
I added Greeting (wave) for LS players and Taunt for DS players as I recall, which why I left it out of the version used in K1CP. But having gone through it again, I think the Victory animation would be appropriate. It looks a little odd for you character to just stand there doing nothing.

**Comment by DarthParametric** [comment]
So we already added the player doing the victory animation via `cp_tar_fistpump`, but apparently it didn't do anything in my playthrough.  Not sure what happened there.
