### ISSUE TITLE
Taris Black Vulkar Base (Garage) - Protototype accelerator laying on the ground

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#244]
The accelerator is just sitting on the ground in an otherwise empty room, which seems weird. It should really be on a bench or something. Maybe next to a swoop - there are those Duros mechanics working on raised swoops at the opposite end of the hall (the ones that attack with fists - see #240 ).

**Comment by ebmar** [comment]
> It should really be on a bench or something. Maybe next to a swoop...

I wonder if it'd work with this scheme -
![PrototypeAccelerator_Repositioned](https://user-images.githubusercontent.com/50026566/65261479-95d32000-db32-11e9-9921-4c2a6360930d.jpg)

**Comment by Mako88** [comment]
I think simply adding a non-functioning workbench to set the accelerator on is within the scope of the K1CP, although the extensive edits suggested by ebmar would be a separate mod.

**Comment by DarthParametric** [comment]
I've made my own [standalone mod](https://deadlystream.com/files/file/1747-black-vulkar-base-engine-lab-bench-for-swoop-accelerator/), since I still don't think it warrants direct inclusion. As such, I'm closing this (again).
