### ISSUE TITLE
Taris Upper City South Apartments - Canderous' messenger scene

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#247]
- [x] For the Canderous' messenger scene, the first time exiting the Hideout post-Bastila rescue, the party needs jumping into position. The messenger seems to almost run straight into the player/camera as well, so that may benefit from a different angle or static camera.
- [x] Messenger has consecutive lines that repeat the same phrase.

**Comment by Mako88** [comment]
Adding an additional issue with this screen: the messenger repeats himself with "Given his connections..." It'd be better to either drop one of the lines where that is said, or re-word it so it's not so repetitive.

**Comment by DarthParametric** [comment]
The two (consecutive) lines are:
```
Yes, that's the one. Given his connections, you can see why it would be wise to attend this meeting.
```
and:
```
Canderous didn't say why he wanted to meet you. He only said he had an offer you couldn't refuse. Given his connections, you can see why it would be foolish to ignore his request.
```
Seems like the easiest solution would be to trim the end off the second line, like so:
```
Canderous didn't say why he wanted to meet you. He only said he had an offer you couldn't refuse.
```
and switch to a shorter VO (it uses generic Twi'lek speech). Would also necessitate a new StrRef.
