### ISSUE TITLE
Ebon Hawk - Pre-Dantooine arrival Bastila/Carth conversation

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#256]
- [ ] There is an extremely long pause before Bastila starts her first line.  This is actually due to the VO. For some reason there is a 4 second silence at the start of the file.

NM12AABAST01000_

**Comment by DarthParametric** [comment]
Seems like the Kashyyyk vision intro line has a similar extended pause.

**Comment by ebmar** [comment]
That is an amazing findings! Thought at first that was the script that does controls it. Might try to dive-in to the relevant audio files and see how they goes with changes been made.
