### ISSUE TITLE
Dantooine Grove - Clicking through Bolook's rambling causes issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#257]
If you click through Bolook's dialogue during the introductory murder mystery scene on the bridge it seems to cause the corpse to give an audible death cry and be stuck in a T-pose. The script that spawns it may need a `NoClicksFor` call and possibly be moved to a different node.

**Comment by DarthParametric** [comment]
Per [this report](https://deadlystream.com/files/file/1258-kotor-1-community-patch/?do=findComment&comment=8971) on DS, it appears this issue still persists. It may be worth investigating changing the spawn event from during Bolook's dialogue to the initial trigger script that starts the conversation.

**Comment by JCarter426** [comment]
Unfortunately, I don't think that's an option. If you tell Bolook to sod off, then he disappears forever and everybody else never spawns. So it at least has to be after that branch of dialogue.

**Comment by DarthParametric** [comment]
It's easy enough to account for that in his sod off script though (k_pdan_bolook03). But I need to be able to reliably reproduce it before worrying too much about how a potential fix is implemented.
