### ISSUE TITLE
Dantooine Jedi Enclave - Lena can get stuck inside Aratech Mercantile

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#262]
It is possible to silently spawn Lena (Mission's personal quest messenger) inside the Aratech Mercantile store at the edge of the landing bay without being aware of it. If you never visit the store, you'll never notice, since the door is closed. And because she has already spawned, she won't appear at any of the messenger spawn points on other planets. 

Manually initiating dialogue with her will teleport her and the party to the usual messenger spot in front of the Hawk.

Apparently this is a known issue - https://steamcommunity.com/app/32370/discussions/0/540732596650326652

![Lena_Shopping](https://user-images.githubusercontent.com/46890653/65303388-4851c400-dbc1-11e9-8efe-4582700f56cb.jpg)

**Comment by DarthParametric** [comment]
Checking back through earlier saves, it appears she must have spawned right after the first Council conversation, where you get sent back to the ship and have the Revan/Malak ruins vision. You get a party selection pop-up at that point after speaking to Carth, and I chose Mission and Carth. I'll have to experiment a bit with that and see if it is that specifically that causes it.

Edit: No, it wasn't that. Mission still needed two more conversations before she was at the state to spawn Lena. So I must have been going in and out of the Hawk purposely trying to spawn her. I'm not sure what circumstances could cause her to spawn inside that room, and for it to be consistent enough that it is a (relatively) common problem. There's nothing special about Lena's section in `k_trg_messengers` that should cause it. And Googling a bit, it seems like it might not just be Lena that can suffer this issue on Dantooine, but possibly all of them (although I have personally never encountered it with any of them before now). 

I wonder if it could be some sort of clash with the wandering NPCs, if they happen to be passing over the waypoint at the exact time the game tries to spawn the messenger. It would seem like long odds, but I suppose it's not impossible. Although in that case I'd expect the spawn to just be offset a couple of meters, not like 20m.

**Comment by DarthParametric** [comment]
Not working as intended due to the added include function never returning true when it should have. The 1.8.1 fix actually broke it. Hopefully 3rd time's the charm.

**Comment by ancient-animal** [comment]
For historical accuracy, I will say this:
In your submitted 3bde908 patch, you wrote "**2020-11-28**" twice. I'm quite sure you meant to write "**2021-11-28**" both times.
