### ISSUE TITLE
The finger colour of Griff Vao's body texture doesn't match the tone of his head texture

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#266]
Griff's fingers are a much darker blue than his face. They could stand to be lightened a tad to better match.

**Comment by ebmar** [comment]
> Griff's fingers are a much darker blue than his face.

Yes, I noticed it on my playthrough but decided to skip on fiddling with it, hahah. While at it moments ago I've give it a try. Perhaps this should work - [Griff_HandRecolor_N_TwilekMD01.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3635458/Griff_HandRecolor_N_TwilekMD01.zip)

Screenshot:
![Griff_HandRecolor](https://user-images.githubusercontent.com/50026566/65320492-2a3d9100-dbcc-11e9-8f39-58ce626e00c8.jpg)
