### ISSUE TITLE
Tatooine Dune Sea - Jagi fight outcomes

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#267]
If you convince Jagi that he had strayed from the teachings of Mandalore and he kills himself, his two mooks still attack you. It seems like they should probably just leave though. Thoughts?

**Comment by Salk73** [comment]
This is how I solved it: https://www.youtube.com/watch?v=dWKgYbtasEE&feature=youtu.be
