### ISSUE TITLE
Kashyyyk Great Walkway - Skipping line of dialogue for Chorrawl

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#268]
If you try to talk to Chorrawl a second time on the Great Walkway, his DLG instantly exits. If you check the Messages window, you see he supposedly said a line "I am done with you, outsider. Go away. I won't be your entertainment.". but nothing is shown in-game.

**Comment by Salk73** [comment]
I have a Save game just before descending into the Shadowlands and if I talk to Chorrawl he correctly says the line above.

**Comment by DarthParametric** [comment]
It seems like this might be another of those weird XP quirks. I couldn't replicate the issue on Win 10, and there wasn't anything obvious in the DLG, so I am going to call this closed for now.
