### ISSUE TITLE
Broken quest resolution for Casus Sandral

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#27]
The quest initiated after finding the corpse of Casus Sandral can be left orphaned if you don't inform Nurik during your meeting with him.  

The protocol droid outside the estate has dialogue nodes that indicate that it should still be present post-resolution of the Feud quest, thus allowing the reporting of Casus being dead and handing over his diary. However, the droid is apparently destroyed at the resolution of the Feud quest, regardless of the outcome. Additionally, the existing lines for returning the diary (and thus closing the quest) appear to be predicated on having told Nurik you found the corpse previously. The fix would require restoring the droid post-Feud and reworking the dialogue to remove references to having spoken to Nurik about it. Edit: There is apparently a node for reporting Casus dead without having his diary (which I am not sure is actually possible) that then closes the quest (per the comment below, with a description about giving the diary to Nurik).

The correct behaviour if you take the DS route should be to flag the quest as failed and closed once both families have killed each other.

**Comment by DarthParametric** [comment]
Looking at the JRL, there are only two states for the quest: one for having the diary in your inventory and one for successful resolution of the quest after having informed Nurik and handed over the diary. There is no fail state available for the quest if you get a bad end to the Sandral/Matale Feud, nor one for any of the possible peaceful Feud resolutions if you don't tell Nurik about Casus and hand over the diary during your initial meeting with him (as per the above comment).

Possible resolution options:

1. Simply forcibly remove the quest if it still active at the resolution of the Feud quest
2. Add one or more new fail state JRL entries and set the quest to these as appropriate at the resolution of the Feud quest
3. As 2, but also restore the protocol droid and amend its DLG (after peaceful resolution of the Feud) per the first post to allow resolution

**Comment by DarthParametric** [comment]
Here's a test of the DS resolution of the Feud quest, showing the new journal entry being added and the quest closed (although it has no description yet):

https://www.youtube.com/watch?v=_Q3xSg1gLLg

The protocol droid is also no longer destroyed by the module OnEnter, allowing post-Feud completion of the Casus quest. In the DS resolution it is set to hostile so it can be destroyed by the player.

**Comment by DarthParametric** [comment]
Here is the interaction with the protocol droid allowing resolution of the quest after having already spoken to Nurik:

https://www.youtube.com/watch?v=vdzrMJ76fSI

**Comment by DarthParametric** [comment]
The nature of the edits to this quest arguably make it more of a Tier 2 addition, since it requires editing some vanilla resources, as per the above video, and adding an entirely new journal entry.

**Comment by DarthParametric** [comment]
Adjustments to the Nurik conversation:

https://www.youtube.com/watch?v=aVeatEyqmPw

Still needs a minor tweak, as when he leaves he is just visible fading out as Rahasia enters.

**Comment by JCarter426** [comment]
I'm throwing some junk in the private repository - all the binaries for the Casus stuff from my installation that seem to be functioning together. It's a bit of a mess, and I'm not sure what we should do about changes.ini, especially with the Sandral droid's dialogue.
Changes from the previous version:
- edited dan14_sdroid.dlg (patch or replace?)
- replaced NM14ADSDRO04091_ and NM14ADSDRO04092_ (not sure where to install these, audio seems to skip)
- rewrote a couple TLK strings (needs patching)
- edited k_pdan_casus01_2.ncs to fix reward
- edited OnEnter and OnAcquirItem for danm14ab
- edited old Casus PLC (needs patching)
- added new Casus PLC, UTC, and scripts

**Comment by DarthParametric** [comment]
I think the best approach it to have the edited DLG as a new one and edit the UTC to point to it.

The install location for the wavs is in changes.ini - streamwaves\m14ad\sdro04

**Comment by JCarter426** [comment]
I've updated everything to include the diary files, and did a hard replace of the Sandral droid's dialogue like we talked about.

I ran a partial patch onto my system and it seemed to work, but you might want to double-check.

**Comment by DarthParametric** [comment]
Hah, the skeleton is a nice touch.

Seems like the only outstanding issue is that the invisible placeable is not destroyed once the diary is looted. As it stands, it remains active post-quest conclusion, allowing the container to be interacted with repeatedly (although it is empty). You also get the quest update ping sound on looting it after the quest is resolved.

**Comment by JCarter426** [comment]
As I recall, the placeable isn't destroyed anymore so as to prevent the other loot in it from ever being destroyed - originally, if you never looted the body for the diary quest, you'd miss out on all the other items on it. I guess I could alter the script to destroy the placeable if it's empty, though I don't know if there would be much of a point since placeables are usually left all over the place after you're done with them anyway.
The other stuff sounds like a bug though. I remember disabling the original script that updated the quest, so maybe it didn't get disabled properly with the TSLPatcher install. I'll extract the files from my build and take a look.

**Comment by DarthParametric** [comment]
Possibly you need to add an additional quest state check for the added DS route, since that uses non-vanilla values.

**Comment by JCarter426** [comment]
It should already account for that, as the corpse is only changed to a skeleton if the families are killed. I think I spotted the problem in changes.ini, will have to test to confirm though.

**Comment by DarthParametric** [comment]
Testing the lasted updated script seems to have prevented the diary being re-added. I think we can call this good for now.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] The Sandral droid's added lines regarding reporting Casus being dead lack subtitles. Must be a config issue adding them to the DLG because the TLK lines exist in append.tlk.
