### ISSUE TITLE
Carth lacks an interjection during the Bek pre-race conversation

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#28]
As referenced in #12, Carth has an interjection in the Vulkar pre-swoop race conversation when the party is informed that the accelerator may cause the swoop to explode. However, he has no equivalent interjection in the Bek dialogue, despite Gadon saying more or less exactly the same thing.

The line used in the Vulkar conversation could be inserted into the Bek conversation, reusing the existing assets.

**Comment by DarthParametric** [comment]
Implemented, but with have to decide whether it is within the purview of the CP to include given that it makes edits to the DLG that slightly alter one branch structure, potentially impacting compatibility.

https://www.youtube.com/watch?v=Vo9_ghahC7o

**Comment by Mako88** [comment]
I would say go ahead and add it. Although we want to try to stay as compatible as possible, given the nature of a patch like this, it will be on other mod authors to release compatibility patches for this mod.

**Comment by Mako88** [comment]
I think this should be Tier 3 as restored/added content, instead of Tier 2.
