### ISSUE TITLE
Lehon Central Beach - Duros survivors scene framing issue

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#285]
- [x] After defeating the Black Rakatan raiding party, you get a scene of two Duros running out from behind the rocks. However, one of them ends up off-screen for the entire conversation. Could be due to both running to the same waypoint, but regardless the non-speaker could be positioned in-frame with better herding.
- [x] When the Duros leave, you can see their shadows while they are standing still just off-screen before they are destroyed. 
- [x] There's some camera wiggle on every Duros speaking node. Must be due to all those nodes having the player as listener. Jumping the party and removing the listener tags should fix it.
- [x] There's supposed to be a fade-out at the end of the scene (assuming you let them leave) based on the dev comments in the DLG, but it's just a hard cut back to the game.

**Comment by ebmar** [comment]
> Could be due to both running to the same waypoint...

Actually each of them are running to different waypoints, as seen in the vanilla `k_punk_ith03` script -
```
void main()
{
	ActionPauseConversation();
	SetGlobalFadeIn(0.0, 0.5, 0.0, 0.0, 0.0);
	AssignCommand(GetObjectByTag("unk41_ithor01", 0), ActionMoveToLocation(GetLocation(GetObjectByTag("ith1wp", 0)), 1));
	AssignCommand(GetObjectByTag("unk41_ithor02", 0), ActionMoveToLocation(GetLocation(GetObjectByTag("ith2wp", 0)), 1));
	AssignCommand(GetObjectByTag("unk41_ithor02", 0), ActionMoveToLocation(GetLocation(GetObjectByTag("ith3wp", 0)), 1));
	ActionWait(2.0);
	ActionResumeConversation();
}
```
Though on my end I found that the problem was with them using `ActionMoveToLocation` in the first place. That function seem to have flaws, as quoted from the NWN Lexicon -
> Move to location functions (ActionForceMoveToLocation() and ActionMoveToLocation()) seem to try to move to their destination in a straight line, unlike move to object functions (ActionForceMoveToObject(), ActionMoveToObject()) which actually do path finding. Furthermore, the move to location functions get interrupted very easily. If anything bumps or obstructs the moving object then the command is finished.

Therefore changing it to either `ActionForceMoveToObject` or `ActionMoveToObject` is more preferable. I have this with my setup which seem to be working - 
```
//:://////////////////////////////////////////////////////////////
//:: k_punk_ith03
//:://////////////////////////////////////////////////////////////
/*
	Fired by unk41_ithor01.dlg in unk_m41aa [Unknown World - Central Beach]

	This script fires with E0 of the DLG. It commands the Duros
	survivors to RUN to the assigned waypoints subsequently after
	the Black Rakatans raid parties are defeated. The vanilla script
	uses *ActionForceMoveToLocation* which make it possible for
	them to get interrupted very easily. *ActionForceMoveToObject*
	nullifies that. It also was having a setup for the third Duros
	which is not present, therefore this modification eliminates
	one as it is redundant.
*/
//:://////////////////////////////////////////////////////////////
//:: Created By: ebmar [based on BioWare's implementation]
//:: Created On: September 25, 2019 - 3:30 PM
//:://////////////////////////////////////////////////////////////

void main()
{
	// Creatures
	object oDuros1 = GetObjectByTag("unk41_ithor01");
	object oDuros2 = GetObjectByTag("unk41_ithor02");
	
	// Waypoints
	object oWP_Duros1 = GetObjectByTag("ith1wp");
	object oWP_Duros2 = GetObjectByTag("ith2wp");
	
	// Pause the conversation for the following commands to takes effect
	ActionPauseConversation();
	
	// Not allow clicking on anything for 2 seconds
	NoClicksFor(2.0);
	
	// Sets a fade-in that fades for 0.5 seconds 
	SetGlobalFadeIn(0.0, 0.5);
	
	// Command the first Duros to RUN to the assigned waypoint and face the PC upon arriving
	SetCommandable(TRUE, oDuros1);
	AssignCommand(oDuros1, ActionForceMoveToObject(oWP_Duros1, TRUE));
	AssignCommand(oDuros1, ActionDoCommand(SetFacingPoint(GetPosition(GetFirstPC()))));

	// Command the second Duros to RUN to the assigned waypoint and face the PC upon arriving
	SetCommandable(TRUE, oDuros2);
	DelayCommand(0.3, AssignCommand(oDuros2, ActionForceMoveToObject(oWP_Duros2, TRUE)));
	AssignCommand(oDuros2, ActionDoCommand(SetFacingPoint(GetPosition(GetFirstPC()))));
	
	// Resume the conversation
	DelayCommand(2.0, ActionResumeConversation());
}
```

**Comment by DarthParametric** [comment]
`ActionForceMoveToObject` has a timeout (defaults to 30 seconds). I don't think there are many cases where you'd use it over the regular `ActionMoveToObject`.

The issue here is framing. If they are using separate waypoints then that means the waypoint needs to be moved, or the off-screen one needs to get a custom location.

**Comment by ebmar** [comment]
> `ActionForceMoveToObject` has a timeout (defaults to 30 seconds).

I didn't know that - thanks for the insight! I'd consider myself to use `ActionMoveToObject` regularly then. And yeah, we could see many of the scripts there around the beach are are using `ActionMoveToLocation` which I think potentially causes troubles.

> ...the off-screen one needs to get a custom location.

That'd be much preferable. Perhaps having him stand linearly with the speaker one which is `unk41_ithor01`.

**Comment by DarthParametric** [comment]
`ActionMoveToLocation` is used because they will actually move to that exact spot. `ActionMoveToObject` only moves them to within a certain range of the object. The default is 1m, and it seems that specifying a lower value than this has no effect (which means if you are trying to use it for precise positioning, you need to offset the waypoint to get them in the right spot).

**Comment by DarthParametric** [comment]
So the issue is there were originally three individuals, but at some point they dropped that to two. The first script has the second Duros run to its intended waypoint, but then, for some inexplicable reason, they tell it to run to the waypoint for the (now non-existent) third Duros. Simply removing that command should fix it.
