### ISSUE TITLE
Xor only appears via rapid transit

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#29]
Split from #8 

The second Xor encounter, the spaceport ambush, will only happen if the player returns to the _Ebon Hawk_ using the rapid transit system. If you don't use it, you can't ever finish Juhani's quest.

The reason Xor consistently does appear after the rapid transit system is used is thanks to this bit of code:
```
        //This allows the players to be ambushed in the starport outside the Ebon Hawk
        if(nXor == 1)
        {
            Db_MyPrintString("Xor 1 == 1");
            if(GetGlobalBoolean("K_XOR_AMBUSH_FIX") == FALSE)
            {
                Db_MyPrintString("Xor 2 Ambush Fix == FALSE");
                if(nPlanet == 20 || nPlanet == 25 || nPlanet == 30 || nPlanet == 35)
                {
                    Db_MyPrintString("Xor 3 Ambush Choosing Planet");
                    SetGlobalNumber("K_XOR_AMBUSH", TRUE);
                    SetGlobalBoolean("K_XOR_AMBUSH_FIX", TRUE);
                    Db_MyPrintString("Xor 4 Hijack");
                    if(nPlanet == 20)
                    {
                        sPlanet = "kas_m22aa";
                    }
                    if(nPlanet == 25)
                    {
                        sPlanet = "manm26ad";
                    }
                    if(nPlanet == 30)
                    {
                        sPlanet = "korr_m33aa";
                    }
                    if(nPlanet == 35)
                    {
                        sPlanet = "tat_m17ab";
                    }
                    StartNewModule(sPlanet, "K_XOR_AMBUSH_SPAWN");
                    return;
```
I edited my save to manually set K_XOR_AMBUSH to 1 and was able to trigger the encounter after walking to the spaceport. I searched through the scripts and only found one other that sets the global to the correct state - a cheat script for quality assurance that isn't ever used anymore. So that'd be why nothing else works.

But we should be able to set this global and trigger the encounter without requiring the use of rapid transit. I think the best solution is to attach it to the OnEnter scripts of each module adjacent to the spaceports. That way when you leave the spaceport after the initial encounter with Xor, he'll be set up to ambush you when you return to the _Ebon Hawk_, via rapid transit or otherwise. The only potential oddity is if you immediately enter the _Ebon Hawk_ and travel around the galaxy without leaving ever leaving a spaceport. Though if you did that, it would be no surprise that Xor would never catch you.

I'll sort this out later, too tired now. This is mostly a reminder to my future self.

**Comment by JCarter426** [comment]
I've smoked Xor out and made him stop hiding like the coward he is.

**Comment by Salk73** [comment]
Is the OnEnter change needed also for Dantooine?

k_pdan_14a_area has been modified accordingly but to my knowledge Xor won't ever appear on Dantooine.
