### ISSUE TITLE
Kashyyyk The Great Walkway - Incorrect walkmesh

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#291]
Both sides of the gate to the village  of Rwookrrorro can be walked into. The area walkmesh needs a fix.

See picture: https://imgur.com/a/JDvc1Wq

**Comment by DarthParametric** [comment]
This should fix it:

[m22ab_09a.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3680507/m22ab_09a.zip)

That is also a gateway to nowhere. You can see there is nothing on the other side.
