### ISSUE TITLE
Kashyyyk Upper Shadowlands - Visible seams

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#297]
I am not sure whether or not this is something that applies only using certain graphics settings and/or if it is a matter of drivers or if it instead happens to everyone but I am attaching a few pictures showing how a white line, probably where different module rooms are sewn together, is quite visible and I cannot convince myself it's just a spider web thread.

See here: 
https://imgur.com/a/th1ytQh
https://imgur.com/a/YHJ8TuK
https://imgur.com/a/peCoDNr

**Comment by DarthParametric** [comment]
Yeah it is the seams between mesh chunks, although I don't recall seeing anything that explicit on Kashyyyk. I would assume that it is indeed a rendering issue on your end. I suspect it might be due to the fog, since the Shadowlands should essentially be black boxed by the trees skybox,

**Comment by Salk73** [comment]
I am on Windows 10 now.

And I am using a nVidia card. I don't seem to remember having seen this in the other areas I have been through in this current playthrough so far (Taris, Dantooine, Tatooine) but it might have escaped my notice.

**Comment by Salk73** [comment]
I have discovered that this problems come from a HD/Upscale texture I am using in my game so it's just a false issue.

Sorry about that.
