### ISSUE TITLE
Taris North Apartments - Odd facing choice during Largo's conversation

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#299]
As you can see from the screenshot, Largo very briefly and unnaturally turns to Carth as he lectures the PC for being too generous: 
![largo](https://user-images.githubusercontent.com/42473604/66712486-1eb83280-ed52-11e9-8e11-4e4f31398611.png)

**Comment by DarthParametric** [comment]
The problem there is actually that Carth's interjection is off-screen, a common problem. Needs a forced camera angle one on Carth's node.
