### ISSUE TITLE
Taris Swoop Platform - Weapons should be hidden in the post-victory cutscene

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#301]
The PC is clearly a masochist who enjoys impaling himself: 
![post-swoop](https://user-images.githubusercontent.com/42473604/66989287-ef1e6880-f078-11e9-965d-7db8e1bc9864.png)

Maybe this has been covered already, but I searched through the issues and didn't see any mention of it.

**Comment by DarthParametric** [comment]
It's in my own notes, but I never added it as an issue. While the usual approach would be to simply enable the `UnequipItems` flag in the DLG, that's not desirable in this instance given the following scene with Bastila escaping her cage. The solution would be to forcibly unequip the PC at the start of the scene via script, then re-equip them at the end. Might have to store their weapons in invisible containers to make sure they get re-equipped properly.

**Comment by DarthParametric** [comment]
While we are editing that conversation, there's some camera wiggle when the announcer turns to face Brejik. Might need to pre-orient him off-screen on the previous line.
