### ISSUE TITLE
Manaan West Central - Sentinel droid back legs clip into the wall

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#302]
Just in the room where the player pays the docking fee.

Screenshot: 

![NxeyxfC](https://user-images.githubusercontent.com/46890653/68034218-0746e680-fd0d-11e9-920d-9bcab3900ca4.png)

**Comment by DarthParametric** [comment]
Hrm, it must be hard up against the walkmesh there.

**Comment by Salk73** [comment]
I have simply edited the .git file and changed a little the Y position of the sentinel droid and now it's fine. Granted, such a cumbersome droid for a narrow space was a poor choice.

**Comment by DarthParametric** [comment]
Oddly the collision looks correct. I'm not actually sure how the droid is managing to clip into the wall like that. It should automatically get shoved further out when it spawns. Can you share your GIT adjustment @Salk73?

**Comment by Salk73** [comment]
My pleasure.

```
[m26ac.git]
!Destination=modules\manm26ac.mod
Creature List\1\YPosition=63.126293182373
```

**Comment by DarthParametric** [comment]
Cheers. We'll credit you directly for that one.
