### ISSUE TITLE
Invisible placeholder speaks to Kandon

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#305]
Reported by [DarkWolf36](https://www.reddit.com/r/kotor/comments/dkctll/is_this_a_bug/)

![swkotor 2019-10-19 22-15-15-82](https://user-images.githubusercontent.com/46898647/67153824-5b3dde00-f2be-11e9-9c9f-1ec6ff51da44.png)

During the conversation with Kandon in the Vulkar swoop garage, the player's name is replaced by "Invisible placeholder" for some lines of dialogue.

I thought this was a simple oversight with the speaker being wrong, but the speaker field is blank for both lines. Maybe it has something to do with how the scene is triggered?

**Comment by DarthParametric** [comment]
Yes, the placeable is the owner. Easy enough to switch the StrRef for its name though.
