### ISSUE TITLE
Tatooine Docking Bay - Customs officer scene issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#308]
- [x] When arriving for the first time, the party needs to be jumped when the scene is triggered to prevent them being scattered.
- [x] If you Force Persuade the customs officer to avoid the fee, he faces whatever companion interjects on his next line.
- [x] If you choose the "stay out of my business" option to end the conversation, he doesn't walk back to his starting location like he does on the other exit nodes.
- [x] The script that sends him back to his starting point has him set his facing to the waypoint's orientation, but he ignores that command which leaves him with his back to the Hawk. Probably needs to be added to his action stack via `ActionDoCommand`.

**Comment by darthbdaman** [comment]
The Force Persuade check in this conversation does not have the persuade animation attached to it

**Comment by DarthParametric** [comment]
The animation is actually present on the successful node (E18). The failure node (E16) does lack the anim however. The camera angle for E18 is set to 3 (wide shot), but I assume that is failing and it is falling back to angle 1 (close up of speaker). It would likely need a static camera.

**Comment by DarthParametric** [comment]
1.10.0 beta test 2 observations:

- [ ] First visit jump did not appear to work. Party members were not repositioned.
