### ISSUE TITLE
[v1.8 Beta] Dantoine Ruins - Questionable facing changes

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#314]
Generally, the PC is well-framed for the duration of the overseer droid conversation: 
![ruins3](https://user-images.githubusercontent.com/42473604/67444790-5f6c4300-f5bf-11e9-8ab1-7d224b005668.png)

However, the camera angle seems a bit off after Bastila's interjections: 
![ruins1](https://user-images.githubusercontent.com/42473604/67445063-41eba900-f5c0-11e9-9189-3b2b7e01ec03.png)
![ruins2](https://user-images.githubusercontent.com/42473604/67445077-4c0da780-f5c0-11e9-8283-86308e8e4787.png)

Or maybe this is intentional/unavoidable. I'm no scripting guru, after all.

**Comment by DarthParametric** [comment]
This is addressed in #105.
