### ISSUE TITLE
Manaan Sunry Trial - Witnesses have inconsistent appearences

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#318]
The witnesses Firith and Gluupor use different appearances in the Visitor's Hotel (East Central) when compared to the trial (Ahto West). Here are a few screenshots: https://imgur.com/a/uDInqA4

**Comment by DarthParametric** [comment]
Hotel (manm26ae) - Firith = 386, Gluupor = 39
Court (manm26aa) - Firith = 27, Gluupor = 257
