### ISSUE TITLE
Manaan Ahto West - Prisoner has mismatched head/hands

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#319]
![ahto west prisoner](https://user-images.githubusercontent.com/42473604/68081595-c5ca4000-fdcd-11e9-8af1-3ddacf1d5d06.png)
Pretty insignificant, but I thought I'd mention it since I'm on Manaan ;^) It's probably safe to equip him with basically anything, since he's in a cage. Maybe basic commoner clothing would be a better choice than smuggler clothing?

**Comment by DarthParametric** [comment]
It goes back to the same problem on Taris. Either the smuggler clothes needs full gloves, or each racial variant needs matching hands for all four textures. Much easier than editing every single UTC that has the problem.

**Comment by DarthParametric** [comment]
@auri0n - if you want to test it out:  [Smuggler_Racial_Variants_Test.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3840111/Smuggler_Racial_Variants_Test.zip)

(7z inside a Zip due to attachment limitations and the poor compression of the Zip format)
