### ISSUE TITLE
Port improved/better quality textures from TSL

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#32]
As suggest by @JCarter426 in #22, I've created a new issue for this.

There are some textures that may have better quality versions in TSL. Either repaints, like N_CommF01 for example, or higher resolution. We should assess how many textures that may be, and if we want to include them in the patch.

For resolution, it should be simple enough to do a file size comparison on matching filenames. Improved quality though will require manual inspection.

**Comment by DarthParametric** [comment]
Here is a list of textures with matching filenames that have a larger TSL equivalent. Most of these are player portraits, which means they probably aren't relevant. 

```
File	K1 Size	TSL Size
N_CommF07	256x256	512x512
N_CommM07	256x256	512x512
PFHA01	256x256	512x512
PFHA01D1	256x256	512x512
PFHA01D2	256x256	512x512
PFHA03	256x256	512x512
PFHA03d1	256x256	512x512
PFHA03d2	256x256	512x512
PFHA04	256x256	512x512
PFHA04d1	256x256	512x512
PFHA04d2	256x256	512x512
PFHA05	256x256	512x512
PFHA05D1	256x256	512x512
PFHA05D2	256x256	512x512
PFHB01	256x256	512x512
PFHB01d1	256x256	512x512
PFHB01d2	256x256	512x512
PFHB02	256x256	512x512
PFHB02d1	256x256	512x512
PFHB02d2	256x256	512x512
PFHB03	256x256	512x512
PFHB03d1	256x256	512x512
PFHB03d2	256x256	512x512
PFHB04	256x256	512x512
PFHB04d1	256x256	512x512
PFHB04d2	256x256	512x512
PFHB05	256x256	512x512
PFHB05D1	256x256	512x512
PFHB05D2	256x256	512x512
PFHC05	256x256	512x512
PFHC05d1	256x256	512x512
PFHC05d2	256x256	512x512
PMHA01	256x256	512x512
PMHA01D1	256x256	512x512
PMHA01D2	256x256	512x512
PMHC03	256x256	512x512
PMHC03D1	256x256	512x512
PMHC03D2	256x256	512x512
twilek_f01	256x256	512x512
combatreticle	64x64	128x128
iarmor	64x64	128x128
ibelt	64x64	128x128
idarmor	64x64	128x128
idbelt	64x64	128x128
idforearm_l	64x64	128x128
idforearm_r	64x64	128x128
idhands	64x64	128x128
idhead	64x64	128x128
idimplant	64x64	128x128
idweap_l	64x64	128x128
idweap_r	64x64	128x128
iforearm_l	64x64	128x128
iforearm_r	64x64	128x128
igaunlet	64x64	128x128
ihand_l	64x64	128x128
ihand_r	64x64	128x128
ihands	64x64	128x128
ihead	64x64	128x128
iimplant	64x64	128x128
iweap_l	64x64	128x128
iweap_r	64x64	128x128
MGF_target02	64x64	128x128
```
It seems this is more the sort of thing for K2CP, as there are more relevant textures in K1 that could be ported to TSL (albeit issues with envmaps in some cases).

**Comment by JCarter426** [comment]
Looks like the 7th variation is used. g_a_clothes08 points to that texture variation, and I see it used by a few UTCs. I'd be in favor of replacing N_CommM01 as well.

**Comment by DarthParametric** [comment]
Ah, they do the same thing with N_CommM01 that they did with N_CommF01. I hadn't noticed. So the list would be:

N_CommF01
N_CommM01
N_CommF07
N_CommM07

Is that it?

**Comment by JCarter426** [comment]
That should be it as far as replacing, yeah. I also have some touch-ups from my minor fixes that I haven't added yet.

**Comment by DarthParametric** [comment]
In the same vein as this, albeit already included in K1's files, is a higher res version of N_CommFC01, the texture for Czerka_Protcol_OfficerF.

**Comment by DarthParametric** [comment]
It seems that N_CommF07/M07 was actually replaced with TSL's F11/M11, which is a dirty version of their repainted F01/M01.
