### ISSUE TITLE
Tatooine Anchorhead - Conversation with Helena's Duros friend doesn't trigger automatically

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#320]
![duros_helena_dlg](https://user-images.githubusercontent.com/42473604/68081688-6bca7a00-fdcf-11e9-9a96-1dc4e75287d6.png)
In the vanilla game, this conversation is initiated automatically once Bastila's quest reaches the right point. With K1CP installed, however, his dialogue has to be initiated manually.

**Comment by DarthParametric** [comment]
I think I see the problem. You have previously been to Anchorhead before advancing Bastila's quest far enough to spawn him I presume?
