### ISSUE TITLE
Leviathan Prison Block - Rescuer's body can almost completely block the camera

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#321]
![lev-prison-block](https://user-images.githubusercontent.com/42473604/68099947-329b1400-fe7a-11e9-8084-9f87a8cf7886.png)

It could be that this only happens with Canderous - I haven't tested it with the others. Maybe this should be merged with #145?

**Comment by DarthParametric** [comment]
Never seen it before using other characters.  I'll try Canderous this run and see if I can replicate it.

**Comment by DarthParametric** [comment]
No problems for me. I assume you must have accessed the computer from the far side in order for that to happen. The user might be able to be jumped out of the way as a fail-safe.

**Comment by auri0n** [comment]
Huh. Probably safe to close this one, then.

**Comment by DarthParametric** [comment]
I was thinking of making a standalone mod at some point that shows the entire crew in that scene, rather than just Canderous, so maybe I'll take a look at it as part of the rejigging for that, when and if I get around to it.
