### ISSUE TITLE
Korriban Dreshdea - Camera incorrectly faces Lashowe and yes-men

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#322]
![kor-dresh](https://user-images.githubusercontent.com/42473604/68100034-98879b80-fe7a-11e9-98c9-2c7fc2c23733.png)
The PC should definitely be in frame for their response. I think this is related to the v1.8 beta and not a vanilla bug, but I'm not entirely sure.

**Comment by DarthParametric** [comment]
No, it does it in vanilla as well.

**Comment by StellarExile** [comment]
Is the camera supposed to be facing them in this one?
