### ISSUE TITLE
Restoration of hitting on Rahasia Sandral/Shen Matale

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#33]
In the final confrontation scene of the Sandral/Matale Feud quest, the DLG has lines between the player and Rahasia/Shen where they can proposition the opposite gender NPC when asked about getting a reward. This was removed from vanilla by Bioware inserting some return false conditionals to the appropriate nodes. It would be a simple case of reverting these to the appropriate gender-check conditionals. But since it is purposely cut content, that makes it Tier 2 at the least.

Liliarch suggested on Discord that this is restored as part of K1R.

**Comment by DarthParametric** [comment]
This should be sufficient (while TSLPatcher can't delete nodes, it _can_ null out fields):
```
[dan14_cutscene.dlg]
EntryList\162\RepliesList\0\Active=
EntryList\165\RepliesList\0\Active=k_con_ismale
EntryList\165\RepliesList\1\Active=k_con_isfemale
```

**Comment by Mako88** [comment]
I think this can be added to tier 3 as long as the cut lines flow well with the original dialog.

**Comment by DarthParametric** [comment]
I'll post a video of it when I get the chance.

**Comment by DarthParametric** [comment]
Hrm, seems like it requires a bit more effort that I first suspected. The line that precedes the response from either Rahasia or Shen "Is there something - anything - we can offer you as a reward?" while listed as being spoken by Rahasia is actually voiced by Nurik. Which, while hilarious, presents a bit of a problem. The conversation also breaks if allowed to go along that route. 

I think the only practical option would be to create a new branch below the existing options so as to cut out the missing line. That should  actually be less of a compatibility issue than what I originally intended, as it wouldn't be altering any of the existing nodes at the start of the DLG.

**Comment by DarthParametric** [comment]
https://www.youtube.com/watch?v=uUBr8u0cY88

**Comment by DarthParametric** [comment]
Determined to be outside the scope of K1CP.
