### ISSUE TITLE
Taris Davik's Estate/Yavin Station - K1CP's new Trandoshan soundset doesn't work

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#330]
It's possible the soundset is broken, but I doubt that. Unfortunately, I didn't travel to the Yavin station during my bare-bones playthrough to test it.

Edit: Updated title

**Comment by DarthParametric** [comment]
Hrm, he is set to the Trando soundset by default, which is why we didn't edit the UTC. I'll have to check the 2DA to make sure the names are correct.

**Comment by DarthParametric** [comment]
Can confirm the Trandos on Yavin station don't appear to use their soundsets properly either.

**Comment by DarthParametric** [comment]
Looks like a simple case of the WAVs incorrectly being put in the Override folder instead of in the streamsounds folder.
