### ISSUE TITLE
Global - Visual glitch with self-closing doors

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#335]
This is a quite elusive issue which I encountered already in the past.

Easiest to reproduce on Manaan where there are many self-closing doors. 

What happens is that sometimes, on loading a game saved with one such door open, there will be a visual glitch showing the door closed and with the interaction cursor while in reality there is no closed door at all.

See video: https://youtu.be/ZHuJ-TNFOUA

**Comment by DarthParametric** [comment]
That's a problem with the walkmesh not properly animating. The door is actually closed, but the walkmesh isn't there to prevent you clipping through it. I encountered a similar problem when making a mod to open and close the forcefield in the Upper Shadowlands. It might require switching to the `YavinHackCloseDoor` function.

**Comment by DarthParametric** [comment]
The OnEnter script for manm26ac can't be decompiled, but it is possible to hex edit it to replace the occurrence of `ActionCloseDoor` with `YavinHackCloseDoor`. Try the following and see what happens:

[k_pman_locked03.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3827243/k_pman_locked03.zip)

**Comment by Salk73** [comment]
Yes, the door in the video is man26ac_to26aa001.utd.

Perhaps @JCarter426 might have an idea about what's going on there. I have no clue.

**Comment by DarthParametric** [comment]
Given I have never seen it, and your prior issue with doors, I would suspect the problem is something on your end. I'm going to call this closed unless you can provide direct evidence that this is a vanilla issue.

**Comment by JCarter426** [comment]
First I've heard of it too.
