### ISSUE TITLE
Tatooine Anchorhead - Game-breaking bug

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#336]
Well, it's actually a permanent fade to-black, so more of a soft lock. This only occurs _the first time_ you leave the landing area for Anchorhead. As you're approaching the Czerka office, the screen will fade to black and nothing will happen afterwards. You can still use your map to return to the Ebon Hawk, so it's not the end of the world, but it's definitely a problem. This happened during my first playthrough with the K1CP Beta as well, but I thought it was just a fluke. Not sure if this will be any help, but I had Bastila in my party both times this occurred.

**Comment by DarthParametric** [comment]
I'm guessing this may be related to #320. If you have a suitable save, try throwing the attached script in your Override and see if that fixes it.

[k_ptat_maanatalk.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3827329/k_ptat_maanatalk.zip)

**Comment by auri0n** [comment]
I think that did the trick. Did you run into the same thing during your last run?

**Comment by DarthParametric** [comment]
No, it never came up for me as I'd already triggered Bastila's messenger before leaving Dantooine. So good catch on that.
