### ISSUE TITLE
Korriban Sith Academy - Uthar went from meditating to standing position in just 0.01 millisecond

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#341]
In Korriban Sith Academy we know that Uthar does his meditation routine most of the time, that is commanded by his OUD, `k35_ud_uthar` -
```
...
	ActionPlayAnimation(ANIMATION_LOOPING_MEDITATE, 1.0f, 1000.0f);
...
```
The problem was if we talk to him, he does his "_Dark side_" stuff which makes him gone from meditating to standing position in just 0.01 millisecond.

It seem to me that the cause of that issue was in no less than _five_ initial nodes of his DLG `kor35_utharwynn.dlg`, they're lacking at least a bridging animation -let's say `PERSUADE`-, so he will stand-up from his meditating position in an appropriate way.

That _trick_ was also used by Kel Algwinn, one of the Sith student there that were meditating, though he's using `GREETING` animation instead.

Here's a setup that I use on my end and that seem to be working -
```
;Adding fields to Uthar's DLG
[kor35_utharwynn.dlg]
!Destination=modules\korr_m35aa.mod
AddField0=gff_kor35_utharwynn_AnimList_0_0
AddField1=gff_kor35_utharwynn_AnimList_0_1
AddField2=gff_kor35_utharwynn_AnimList_0_2
AddField3=gff_kor35_utharwynn_AnimList_0_3
AddField4=gff_kor35_utharwynn_AnimList_0_4

;Configure the PERSUADE/10126 animation to the animation list
[gff_kor35_utharwynn_AnimList_0_0]
FieldType=Struct
Path=EntryList\0\AnimList
Label=
TypeId=0
AddField0=gff_kor35_utharwynn_Participant_0
AddField1=gff_kor35_utharwynn_Animation_0
[gff_kor35_utharwynn_Participant_0]
FieldType=ExoString
Label=Participant
Value=OWNER
[gff_kor35_utharwynn_Animation_0]
FieldType=Word
Label=Animation
Value=10126
[gff_kor35_utharwynn_AnimList_0_1]
FieldType=Struct
Path=EntryList\1\AnimList
Label=
TypeId=0
AddField0=gff_kor35_utharwynn_Participant_1
AddField1=gff_kor35_utharwynn_Animation_1
[gff_kor35_utharwynn_Participant_1]
FieldType=ExoString
Label=Participant
Value=OWNER
[gff_kor35_utharwynn_Animation_1]
FieldType=Word
Label=Animation
Value=10126
[gff_kor35_utharwynn_AnimList_0_2]
FieldType=Struct
Path=EntryList\2\AnimList
Label=
TypeId=0
AddField0=gff_kor35_utharwynn_Participant_2
AddField1=gff_kor35_utharwynn_Animation_2
[gff_kor35_utharwynn_Participant_2]
FieldType=ExoString
Label=Participant
Value=OWNER
[gff_kor35_utharwynn_Animation_2]
FieldType=Word
Label=Animation
Value=10126
[gff_kor35_utharwynn_AnimList_0_3]
FieldType=Struct
Path=EntryList\90\AnimList
Label=
TypeId=0
AddField0=gff_kor35_utharwynn_Participant_3
AddField1=gff_kor35_utharwynn_Animation_3
[gff_kor35_utharwynn_Participant_3]
FieldType=ExoString
Label=Participant
Value=OWNER
[gff_kor35_utharwynn_Animation_3]
FieldType=Word
Label=Animation
Value=10126
[gff_kor35_utharwynn_AnimList_0_4]
FieldType=Struct
Path=EntryList\91\AnimList
Label=
TypeId=0
AddField0=gff_kor35_utharwynn_Participant_4
AddField1=gff_kor35_utharwynn_Animation_4
[gff_kor35_utharwynn_Participant_4]
FieldType=ExoString
Label=Participant
Value=OWNER
[gff_kor35_utharwynn_Animation_4]
FieldType=Word
Label=Animation
Value=10126
```

**P.S.** it's been awhile since the last time I fiddle with an INI so, apologize if I missed something there. :beers:

**Edit**: I did a mistake there [with the `AddField` numbering], and now they has been edited as appropriate.

**Comment by DarthParametric** [comment]
Interesting. It seems any animation specified (at least the ones I tried anyway) will be ignored in favour of playing the transition meditate-to-standing, regardless of whether they are fire-and-forget or looping. Nice find.

**Comment by ebmar** [comment]
> Nice find.

Cool, and thanks! Glad that it worked for you and K1CP also. Anyway, I see you change the animation to `10038` which is `TALK_NORMAL`, if I recall correctly? If it does working then that should be the most appropriate way as it looks more neutral in movement than any other animation available.

**Comment by DarthParametric** [comment]
Yeah, it's TALK_NORMAL. Like I said above, it has the same end result, but I figured just in case it ever does trigger directly, talk would make the most sense.

**Comment by ebmar** [comment]
Sorry to say that `TALK_NORMAL` didn't work, DP. I tested it with Kel Algwinn on few attempts just earlier. I recall I uses `PERSUADE` after few trial-and-error attempts which I believe leads me to use it amongst others.

**Comment by DarthParametric** [comment]
Weird. Works fine for me.

**Comment by ebmar** [comment]
>  ...guess Persuade it is.

Hahah, yeah, it is. Though `GREETING` can also work but it wouldn't be preferable in this case. While at it I believe Kel will also need the same treatment for one [or two] of his nodes. I can open an issue for it to be inspected with the required fix tomorrow if you don't mind.

**Comment by Salk73** [comment]
I just wanted to chime in to report Keeper Orsaa (unk_m42aa) suffers the same issue.
