### ISSUE TITLE
Korriban Sith Academy - Uthar's meditate-to-standing sorcery was a contagious to Kel Algwinn

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#343]
Kel Algwinn does learnt a lot from his Master. Several of his DLG nodes were missing a bridging animation -that in this case is `PERSUADE`-, which makes him stand-up from meditating position faster than a human should be.

He was using `GREETING` with a few that are by default suitable with the conversation. Though rest of them are preferably use `PERSUADE` which seem to be [working with Uthar in other instance](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/341).

Something to note here that even though `PERSUADE` is used for the DLG animation, it doesn't actually shown. Therefore, its utilization shouldn't do any radical change aside of fixing the meditate-to-stand animation, which I think is suitable for K1CP.

Here's a setup that I use on my end and that seemingly works -
```
;Adding new AnimList fields to Kel Algwinn's DLG
[kor35_kelal.dlg]
!Destination=modules\korr_m35aa.mod
AddField0=gff_kor35_kelal_AnimList_0_0
;Rest of the three are commented as I haven't tested them
;AddField1=gff_kor35_kelal_AnimList_0_1
;AddField2=gff_kor35_kelal_AnimList_0_2
;AddField3=gff_kor35_kelal_AnimList_0_3

;Configure the PERSUADE/10126 animation to the newly added AnimList
[gff_kor35_kelal_AnimList_0_0]
FieldType=Struct
Path=EntryList\1\AnimList
Label=
TypeId=0
AddField0=gff_kor35_kelal_Participant_0
AddField1=gff_kor35_kelal_Animation_0
[gff_kor35_kelal_Participant_0]
FieldType=ExoString
Label=Participant
Value=OWNER
[gff_kor35_kelal_Animation_0]
FieldType=Word
Label=Animation
Value=10126

;Fields below are commented and haven't been tested as I don't have access to them
;I told Uthar about Kel's doubted mind of being a Sith hence those nodes were skipped on my end
;[gff_kor35_kelal_AnimList_0_1]
;FieldType=Struct
;Path=EntryList\30\AnimList
;Label=
;TypeId=0
;AddField0=gff_kor35_kelal_Participant_1
;AddField1=gff_kor35_kelal_Animation_1
;[gff_kor35_kelal_Participant_1]
;FieldType=ExoString
;Label=Participant
;Value=OWNER
;[gff_kor35_kelal_Animation_1]
;FieldType=Word
;Label=Animation
;Value=10126
;[gff_kor35_kelal_AnimList_0_2]
;FieldType=Struct
;Path=EntryList\31\AnimList
;Label=
;TypeId=0
;AddField0=gff_kor35_kelal_Participant_2
;AddField1=gff_kor35_kelal_Animation_2
;[gff_kor35_kelal_Participant_2]
;FieldType=ExoString
;Label=Participant
;Value=OWNER
;[gff_kor35_kelal_Animation_2]
;FieldType=Word
;Label=Animation
;Value=10126
;[gff_kor35_kelal_AnimList_0_3]
;FieldType=Struct
;Path=EntryList\32\AnimList
;Label=
;TypeId=0
;AddField0=gff_kor35_kelal_Participant_3
;AddField1=gff_kor35_kelal_Animation_3
;[gff_kor35_kelal_Participant_3]
;FieldType=ExoString
;Label=Participant
;Value=OWNER
;[gff_kor35_kelal_Animation_3]
;FieldType=Word
;Label=Animation
;Value=10126
```
- Look for #341 for similar issue.

**Comment by DarthParametric** [comment]
Hrm, I thought it might be better to change their default OnDialogue (or possibly OnDisturbed) event to play the anim rather than editing the DLG, but it seems that just forces them to play it instantly and not play the transition animation. I wonder what the DLG does that causes it to play. Must be some hardcoded blending function or something.

**Comment by ebmar** [comment]
> I wonder what the DLG does that causes it to play.

Yeah, that's what I thought so. Because I think what has been done recently was just finding the _quick_ answer and not the core of the problem. It'd be nice to know what happens in background, such as why the `GREETING` animation does play its movement after the transition whilst `PERSUADE` doesn't, and `TALK_NORMAL` [with few others as well, perhaps] did not affect anything.

Is there a function to call DLG animation, like something other than `ActionPlayAnimation`? As I write this up I found [the indicated one](https://nwnlexicon.com/index.php?title=PlayConversationAnimation) in the Lexicon which I think should be working, but suspected that it has been taken out from KotOR's engine.

**Comment by DarthParametric** [comment]
No, that is not a valid KOTOR function. What is in nwscript.nss is what is available.
