### ISSUE TITLE
Manaan East Central - A script is checking for the wrong file

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#344]
The global k_pman_planet45.ncs script checks for an item that is apparently unused in the game. It makes sense that we check instead for the passcard (w_sithkey.uti).

```
int StartingConditional()
{
    int iResult;

    iResult = (GetIsObjectValid(GetItemPossessedBy(GetPCSpeaker(), "w_sithkey")) == TRUE);

    return iResult;
}
```

**Comment by DarthParametric** [comment]
`MAN_REPTECH1_DONE` being false a check for one of the nodes in the Republic Technician's DLG `Hey, great! You sliced the encryption on those cards! They change the codes regularly, so you'll have to use it pretty soon or not at all.` so you don't want to include that. It can be switched to a local boolean if needs be.

**Comment by Salk73** [comment]
Oh okay, good.

The vanilla script included that check so I let it be but I should have known better. Thanks for the heads-up. We can even just remove it altogether without bothering to replace it with any local variable.

**Comment by DarthParametric** [comment]
There's an existing global starting conditional that does this, `k_pman_missing34`.
