### ISSUE TITLE
Kashyyyk Lower Shadowlands - PC is frozon for one response during Star Map conversation

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#346]
I forgot to report a few of these. Here's the line in question:
![kash_map](https://user-images.githubusercontent.com/42473604/68972202-195e6580-07a0-11ea-82c8-524ef7565c1b.png)

**Comment by DarthParametric** [comment]
Doesn't happen on my end. Notionally it could be caused by Jolee's interjection on the previous line, but we haven't edited the DLG so it shouldn't be from anything we've done.

**Comment by auri0n** [comment]
Ah, no problem then. I'll close this and #347.

**Comment by DarthParametric** [comment]
I just got this during my 1.9.0 beta test. Additionally, the right side of the hologram's body remained stuck in a pose from one of its ambient animations.
