### ISSUE TITLE
Korriban Dreshdea - Small problem with Lurze Kesh conversation

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#347]
The camera is focused on Lurze for one of the PC's responses during the Mysterious Box conversation:
![lurze](https://user-images.githubusercontent.com/42473604/68972793-7575b980-07a1-11ea-9bf6-2890818b6d18.png)

**Comment by DarthParametric** [comment]
This is the same problem that occurs in the Lashowe conversation. I don't think it is fixable, since speaker/listener tags and camera changes made no difference in that instance.
