### ISSUE TITLE
Korriban Dreshdea - Prospective Sith can run out of Czerka area during Sith Thug encounter

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#348]
![prosp_sith](https://user-images.githubusercontent.com/42473604/68972956-e3ba7c00-07a1-11ea-8df0-7b7f28c1b28b.png)

**Comment by auri0n** [comment]
Didn't see the tag until now lol, let me know if there's anything I can clear up.

**Comment by DarthParametric** [comment]
> let me know if there's anything I can clear up

All of it. What is the specific issue? NPCs from a different room becoming hostile?

**Comment by auri0n** [comment]
Well, the 'Prospective Sith' NPC, who is standing between the PC and Canderous in the attached screenshot, is meant to stand still in the Czerka area, but will occasionally run out into the open during the thug encounter.

**Comment by DarthParametric** [comment]
Odd. I'm not even sure how that would happen while they remain neutral, but presumably it must be AI-related.
