### ISSUE TITLE
Manaan Sith Base - Receptionist types telepathically

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#350]
Sorry, forgot to report this one, too. Should probably be merged with #141.
![recep_type](https://user-images.githubusercontent.com/42473604/69016245-93821c00-0951-11ea-829e-8a54e637a9d1.png)

**Comment by DarthParametric** [comment]
Yes, it's part of the complete revision required for that scene. Won't be looked at until v1.9 though since I hate Manaan.

**Comment by DarthParametric** [comment]
This is now resolved with a forced facing as part of 732b26ee7088b7108cfe23cd04c99de1c0bda372.
