### ISSUE TITLE
Manaan Sith Base - Visual inconsistency with flow control panels

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#351]
When you try to empty the chambers sometimes the operation is aborted because the system detect human presence thus stopping the flooding process.

The same visual cue, hinting at the water being completely transferred, is used even in this case. We should make sure that the blue bar doesn't move from the default position if the operation is unsuccessful.

The video shows exactly what I mean: https://youtu.be/JoIGKVLD85I

EDIT: I tried to take a look at this myself but it's a mess due to all scripts involved being impossible to decompile...

**Comment by DarthParametric** [comment]
Just about any script written using the Manaan or Tatooine includes won't decompile with DeNCS for some reason (it's not recursion). Such scripts will have to wait until @xoreos further develops ncsdis/ncsdecomp into something more practical/functional.

**Comment by Salk73** [comment]
I fear we may never see the day but hope dies last, they say.

I have pinpointed the single script responsible for this and it's k_pman_flow05.ncs. One thing I can try to do is to work around the problem somehow. I will come back to this if I find some solution.

**Comment by DarthParametric** [comment]
Depending on how complex it is, it may be possible to reconstruct it from the bytecode.

**Comment by Salk73** [comment]
Definitely a progress.

What I am trying to figure out right now is how man27_waterlvl04.utp shows the "empty" animation when the Player successfully moves the water around. In the relevant .dlg file ( there is no script firing in E1 or R2 and k_pman_flow05.ncs, which contains the ACTIVATE and DEACTIVATE actions is a conditional script and its code is skipped in that case.

**Comment by Salk73** [comment]
Well, it seems that something happens when a game is loaded the first time but not the successive times.

I have made another small video to show that here: https://youtu.be/Q0Ak8Lo3M8E

I saved the game in the first flow room to the right (the one that has the out of order panel) with both the water level indicators full (water level 02 and water level 04),

 The water level 04 placeable plays its animation ONLY the first time the game is loaded. Any other time instead the animation has already while the game is being loaded. I have encountered this behavior just recently when I tried to postpone an action until the game was fully loaded. Without a workaround, that action would be played correctly only the first time the saved game was loaded and failed each other time.

**Comment by DarthParametric** [comment]
Might need an OnEnter addition gated behind an `if (GetLoadFromSaveGame())` that sets/resets their animation state.

**Comment by Salk73** [comment]
I made some progress here and I will share my finds. The problem is not only cosmetic, making the puzzle broken but that part I have fixed.

There remains the cosmetic issues which annoy me but am not sure I can really fix other than use a FadeOut/FadeIn sequence.

**Comment by Salk73** [comment]
Okay, here's the situation.

I need to explain how this puzzle is partly broken. It is partly broken because you can solve it in a way that does not make sense.

There are two corridors, each one with three chambers (A to E). Two of these rooms contain a body of water and the puzzle is all about shifting them from one chamber to another in order to free a path to the other side. The OnEnter script fills once only room A and D with water. The others are empty.

E         F
C        D
A        B

The intended way to solve this puzzle is (starting from the Flow Control room) push the button outside chamber B (moves water from chamber D to B), push the button outside chamber A (moves water from chamber A to chamber C), enter chamber A, push the button on the front wall (moves water from C to E), open the door to chamber C, push the button on the right wall of Chamber C (moves water from E to F and B to A), open the door to chamber E and finally open the door to the corridor beyond.

But there is a bug. If the player pushes the button outside chamber A then enters chamber A and push the button on the right wall, what happens is that there will be water only in chamber D, allowing the player to open the door to C, then the door to E and finally the door to the corridor, breaking the puzzle.

To fix this I had to add a new Entry to man27_warning.dlg, man27_warning002.dlg, man27_warning003.dlg, man27_warning004.dlg, man27_warning005,dlg and man27_warning.dlg.

Such entry contains a new conditional script (cp_man_flow05.ncs) and is to be placed first after R1 ("[Proceed]"). The new line needs a TLK addition: "WARNING: Occupied chambers." and a VO which I have already created ("NM27AAWARN16002_.mp3) that needs to be placed in ".../streamwaves/m27aa/warn16". The new VO line reuses the same original clips and, while not ideal (I would have liked to use the original word "water" to make "Water in occupied chambers" as well but it doesn't sound good), it does the job well enough.

Speaking of VO, there is another bug. The original man27_warning002.dlg, man27_warning003.dlg, man27_warning004.dlg, man27_warning005.dlg and man27_warning006.dlg all  have empty VO_ResRef and unchecked SoundExist so that there is no VO for them other than the initial one ("WARNING: Activating flow control may flood occupied chambers. Please ensure all receiving chambers are empty."). I restored those as well, of course.

The following is the new script:

```
#include "k_inc_man"

int StartingConditional() {

  return ((GetRoomFull("A") && GetRoomFull("B")) || (GetRoomFull("C") && GetRoomFull("D")) || (GetRoomFull("E") && GetRoomFull("F")));

}
```

What remains to fix are two cosmetic issues. The first is caused by the original k_pman_flow05.ncs. The problem being that it plays the animations for the water indicators even when it shouldn't. It would be a very simple fix if I could decompile the script but since it is not possible, it needs a workaround. 

The second is that upon loading a saved game, the indicators play their animation after the game is loaded. To verify this, save the game outside Chambers A and B, load the game and pause the game as soon as the screens fades in from black. Both the indicators outside Chambers A and B will show "empty". Upon unpausing the game, the indicator outside Chamber A will fill up and the one outside Chamber B will empty itself. 

This is related to the issue [I showed a video for earlier](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/351#issuecomment-555532042).

**Comment by Salk73** [comment]
I have worked around the two cosmetic bugs left but I doubt it's of any interest for the CP patch. One is an awful hack and the other requires adding 6 static cameras.

Just let me know if there is any interest in any of the above.

**Comment by DarthParametric** [comment]
Sounds a bit extreme for what is a fairly inconsequential issue.

**Comment by Salk73** [comment]
Agreed.

The part about fixing the riddle and restoring the missing VOs may be worth inclusion though.

**Comment by th3w1zard1** [comment]
Is this partially-decompiled script I've written of any use?
```
#include "nw_i0_generic"
#include "x0_i0_door"

void StartingConditional()
{
    int sRoom;

    int nResult = RSADDS();
    int nConst1 = CONSTI(1);
    int nConst0 = CONSTO(0);
    int nAction1 = GetTag(1);
    int nAction2 = GetStringRight(2);
    CPDOWNSP(-8, 4);
    MOVSP(-4);
    CloseAssociatedDoor();
    SwitchWaterRooms();
    RSADDI();
    CPTOPSP(-8, 4);
    int nResult2 = GetRoomFull(sRoom);
    if (nResult2 == 0)
    {
        SwitchWaterRooms();
        nConst1 = CONSTI(1);
        CPDOWNSP(-12, 4);
        MOVSP(-8);
        JMP loc_00000E1B;
    }
    else
    {
        JMP loc_00000DF5;
    }

loc_00000DF5:
    nConst1 = CONSTI(0);
    CPDOWNSP(-12, 4);
    MOVSP(-8);
    JMP loc_00000E1B;

loc_00000E1B:
    return;
}
```

**Comment by DarthParametric** [comment]
> Is this partially-decompiled script I've written of any use?

If that is manm27aa/k_pman_flow05 then [that has already been decompiled](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M27AA_Manaan_Sith_Base_manm27aa/k_pman_flow05.nss) (although not manually cleaned up).

**Comment by th3w1zard1** [comment]
> > Is this partially-decompiled script I've written of any use?
> 
> If that is manm27aa/k_pman_flow05 then [that has already been decompiled](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M27AA_Manaan_Sith_Base_manm27aa/k_pman_flow05.nss) (although not manually cleaned up).
> 
> Edit: I've now cleaned those flow control scripts up in [commit 0351e82](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/commit/0351e821b45783c0b5078d0dacef9576395ed642).

Ah, looks like I was close. I mostly couldn't figure out this part:
`string sRoom = GetStringRight(GetTag(OBJECT_SELF), 1);`

although, where are all the constants that are shown in the compiled version?
