### ISSUE TITLE
Juhani's and Jolee's dialogue - One line is never spoken due to wrong code in script

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#355]
The original conditional script k_hjuh_p28.nss never returns true because sArea in the function

`string sArea = GetName(GetArea(OBJECT_SELF));`

seems to be returning a null string, despite the following remark I found on NWN Lexicon:

"Remarks:

GetName() returns the name of modules and areas (pre-1.25 it returned a null string)."

It is easy to replace it with something appropriate thus restoring one of Juhani's lost lines.
```
int StartingConditional()
{
    string sArea = GetModuleFileName();
    if ((sArea == "unk_m44aa") || (sArea == "unk_m44ab"))
    {
      if ((GetGlobalNumber("G_JUHANIP_STATE") != 10) || (GetGlobalNumber("G_FinalChoice") != 2))
      {
        return TRUE;
      }
    }
    return FALSE;
}
```

**Comment by Salk73** [comment]
I've added an extra check to make sure this won't interfere with the "This may be the last time I will have a chance to talk to you..." dialogue (E489).

**Comment by Salk73** [comment]
One more bug in Juhani's dialogue. The script at E82 needs to be removed.

**Comment by DarthParametric** [comment]
Is that secondary check for the globals intended to be an OR, or was it meant to be an AND?

**Comment by Salk73** [comment]
An OR check.
