### ISSUE TITLE
Tatooine Eastern Dune Sea - Bad punctuation in Bastila's added holocron dialogue

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#356]
![bast_dlg](https://user-images.githubusercontent.com/42473604/69702702-a8bf1f00-10a4-11ea-9f9b-0c7c204838b6.png)
There should be a space after the ellipsis. Also, I've got a dialogue.tlk based on Salk's (https://deadlystream.com/files/file/1313-kotor-dialogue-fixes/) with all of the fixes described in #148 as well as most of Gimmick5000's punctuation/consistency/lore fixes, and of course a few typos or mismatches I've caught. Obviously I would need permission from them both, and I would feel bad about stealing some of Gimmick's thunder, but if it works out then I'd be happy to send it to you.

**Comment by DarthParametric** [comment]
We won't be adding any of Gimmick5000's changes, or any other TLK revisions.

**Comment by auri0n** [comment]
Fair enough ;) If I receive all the correct permissions I'll post it to Deadlystream. Just making sure you knew about the thing regarding Bastila's dialogue, since that one isn't in the .tlk.

**Comment by DarthParametric** [comment]
It is actually in the TLK. StrRef 29852 & 29853. The DLG is pulling directly from the TLK. As such it can be covered by third party TLK mods.

**Comment by auri0n** [comment]
Damn, my ctrl+f skills have failed me yet again. Thanks for the info.
