### ISSUE TITLE
Taris Upper City/Lower City Cantinas - Excessive fog

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#357]
The two cantinas on Taris with their shared layout have fairly obnoxious levels of fog to hide the fact that the side rooms aren't visible from one another.  It can be dropped back with an ARE edit and the side rooms made visible with a VIS edit.

**Comment by Mako88** [comment]
I recommend changing the SunFogFar value to 33 and leaving SunFogNear at 10 to still keep a smoky atmosphere, but make it no longer look like you're walking through soup.

**Comment by ebmar** [comment]
Apparently, having the modified `m02ae.vis` grabbed from `#mod_development` installed seem to cost a performance issue on my end [:hurtrealbad:] which might affect others [that has similar specs] too. At the other hand, having only `SunFogFar` at `33` seem to be working very nicely. Nice catch on the value, @Mako88!

Though, I noticed if the said VIS weren't installed then look across to the side-room from specific spot around the module, there's indeed a solid grey fog present and will be gone when moving from the relevant spot [which I could live with].

While at it I'd like to drop an INI setup that represents AFP/Mako88's ARE configuration for convenience's sake -
```
; Taris - Upper City Cantina
[m02ae.are]
!Destination=modules\tar_m02ae.mod
SunFogFar=33

; Taris - Javyar's Cantina
[m03ae.are]
!Destination=modules\tar_m03ae.mod
SunFogFar=33
```
