### ISSUE TITLE
Taris Undercity - Mission running towards party has bad camera angle

### ISSUE THREAD

**Issue by Mako88** [KOTORCommunityPatches/K1_Community_Patch#360]
If you exit the gates from the town and head to the right instead of the left, when Mission comes running up the camera is a close-up shot of her face instead of a more wide-angle shot.

**Comment by JCarter426** [comment]
That has to do with your positioning. That shot is using the usual dynamic cameras, which default to a close-up if there's too much crap between you and the speaker for one of the other angles.
