### ISSUE TITLE
Taris Black Vulkar Base (Upper) - Two lieutenants with duplicate pass cards

### ISSUE THREAD

**Issue by Mako88** [KOTORCommunityPatches/K1_Community_Patch#364]
There are two lieutenants with pass cards in the same room. Either we should move one of them to another room, or take away the pass card from one of them. To remove the pass card would be a .utc replacement since currently it's not possible to remove items view TSLPatcher.

**Comment by DarthParametric** [comment]
Resolvable in a similar manner to the ritual corpse issue on Kashyyyk (#124), where the item is deleted if the player already had one.

**Comment by DarthParametric** [comment]
1.9.0 observations:
- [ ] Two cards still drop if the player slices a terminal and overloads the electrical conduit. That may need to be addressed by the console's script given they are both killed more or less simultaneously.

**Comment by DarthParametric** [comment]
So apparently neither UTC was in the GFF list. Probably explains why it didn't work during the last beta test....

Anyway I have switched the former approach out for a simpler OnSpawn method which should prevent further issues.
