### ISSUE TITLE
Taris Davik's Estate - Calo's last stand during hangar fight

### ISSUE THREAD

**Issue by Mako88** [KOTORCommunityPatches/K1_Community_Patch#368]
He yells at the end of his dialogue, and then immediately yells again once you leave his dialogue.

**Comment by DarthParametric** [comment]
This is probably similar to Admiral Karath's death scene (#131) in that his death fires his soundset death cry independent of the actual conversation. The DLG could be altered to remove the death cry, or the script that kills Calo could be edited to teleport him to the other side of the module before knocking him on the head.

**Comment by DarthParametric** [comment]
Watching the scene again, it seems like the yell in the DLG is out of place anyway, so the simplest solution is probably just to null out the TLK StrRef for that node.

**Comment by DarthParametric** [comment]
A couple of other things I have noticed about this scene:

- [ ] The initial camera angle is low pointing up to the ceiling to show the structure hanging over Calo's head that eventually falls on him, but you can see it being spawned in (it's a placeable). Needs to either be spawned in earlier, or the camera angle changed.
- [ ] Calo initially does his custom animation for holding up a thermal detonator, but then he stops. Needs to be extended.
