### ISSUE TITLE
Leviathan Bridge - Attempting to return via external catwalk leaves you stuck in the space suit

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#372]
Apparently if you try to exit the bridge by going back the way you came via the external catwalk, you are put in the space suit but then trapped in it when getting to the other side. The simplest solution may be to lock the door behind the party once they have passed through the first time to prevent this from happening.

Reported by fire-wariorr [on Reddit](https://old.reddit.com/r/kotor/comments/e6k842/im_stuck_in_my_spacesuit/).

**Comment by Salk73** [comment]
DP,

I was testing this and I have some feedback. It's still possible to go back on the catwalk by bashing open lev40_airlockin. At least, that is what is happening to me.

**Comment by Salk73** [comment]
I tested this and it is all fine.

Due to human error (typo), I had not the Plot flag activated for the door hence a previous feedback about bashing the door open (now removed).

All fine.
