### ISSUE TITLE
Taris Sith Base - Duros prisoner doesn't match his original appearance

### ISSUE THREAD

**Issue by auri0n** [KOTORCommunityPatches/K1_Community_Patch#373]
First of all, congrats on the 1.8 release ;) your work has been phenomenal. Now, on to the issue: the prisoner tells you that he's the same Duros you saved outside your hideout, but he's wearing the wrong outfit. Should be the green and white variant, not the plain white one.

**Comment by ndye** [comment]
Simple fix - tar_m09aa.mod the file n_duros001.utc needs Appearance type needs to be changed from 24 to 373.
