### ISSUE TITLE
Unknown World Temple Main Floor - Standing lamp missing render flag?

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#375]
A very minor issue that someone can just let it slide, but I'm dead-curious with what's happening here.

Inside the Temple Main Floor/`unk_m44aa`, there's a room which inside are three _rune covered pillars_ which one of them is lootable. The problem is not on them, but a source of light that comes from nowhere as seen with the screenshot here -
![TMF_StandingLampMissingRenderFlag](https://user-images.githubusercontent.com/50026566/71560289-9ddc1d80-2a9a-11ea-831f-84ecbde4e888.jpg)

I think a standing lamp is missing from the area, which I'd gather it's missing its render flag. At first, I was expecting the lamps as placeables, but apparently they're not as there're no references of them inside the module's GIT. We can guess something being placed there [or a walkmesh?] as if we try to walk the spot, there's something blocking the path.

Apologize that further information about the room model's name can't be provided 'cause I unable to track which one of it, as there are more than dozens of them.

The co-ordinates for the relevant spot is - `X = 76.54 || Y = 96.41` - if that could help tracking the model's name.

**Edit1**: thanks to @DarthParametric for troubleshooting and finding the model name -which is `m44aa_17a`- we managed to find the essence of the problem. The missing lamp caused by a missing reference for the relevant lamp. It is not part of the room model nor a placeable, instead a `reference` model called by the room's. By adding a lamp's reference to the model, the lamp is there now to see -
![UWTMF_MissingLampFix](https://user-images.githubusercontent.com/50026566/71563025-d04a4280-2abb-11ea-818c-c44f60b5662b.jpg)

As suggested on `/r/kotor's #mod_development` this will be a standalone mod and I get the chance to release it, though -

**Edit2**: -- it seem there are at least _three_ of them left to be cured, lol -
![UWTMF_MissingLampsPart2](https://user-images.githubusercontent.com/50026566/71563048-1dc6af80-2abc-11ea-8d4c-87469bb91697.jpg)

**Edit3**: as I've got the heads-up to release it as a stand-alone mod, I did it just recently. Looking very forwards to **K1CP** including it with their next build. Here's the link for the release - https://deadlystream.com/files/file/1545-k1-temple-main-floor-missing-lamps-fix/

**Comment by DarthParametric** [comment]
Calling this complete now, since the potential part 2 for the catacombs is deemed not suitable for K1CP.
