### ISSUE TITLE
Messenger Conversations keep looping

### ISSUE THREAD

**Issue by Spirit-Warden** [KOTORCommunityPatches/K1_Community_Patch#379]
I'm having an issue that only started after installing this mod, so I must assume it is responsible for it. Basically the problem is with the messengers that appear for companions. Like Lena and Jagi.

Their conversations glitch out and loop. E.g Jagi appeared on Dantooine  to challenge Canderous to a duel on Tatooine then he walked off. After the conversation I spoke to Canderous with him saying we had to get to Tatooine so he could kill Jagi. After that convo ended, the screen went black and we were entered into a conversation with Jagi again (he was standing near that Jedi who tells you about the Terentatek) and this conversation was his dialogue on Tatooine 'so you have come and I see you have brought friends' etc. etc.

I convinced Jagi not to fight, he 'supposedly' took his own life, and that ended the conversation, I received XP and a journal entry saying Jagi was dead and it has shaken Canderous. I went to where Jagi was in the convo and he was just standing there, I spoke to him and it re-entered the original conversation back outside the Hawk, where Canderous was surprised to see Jagi, and Jagi challenging him to a duel. I went into the Ebon Hawk and Canderous is talking about needing to go to Tatooine to kill Jagi. I haven't gotten there yet so I don't know what effect this will have.

Another example with Lena, after I finished the conversation with her. I tried going back to the Ebon Hawk but the screen went black, and the conversation restated. Overall I went though Lena's conversation 3 times before I finally was able to enter the Hawk.

**Comment by DarthParametric** [comment]
It appears that the boolean check is incorrect (checking for TRUE rather than FALSE), so the trigger is actually doing the _opposite_ of what it was intended to do. If you have an appropriate save available, I'd appreciate if you could extract the attached into your Override and test whether the issue persists.

[k_pdan_trig1301.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/4272172/k_pdan_trig1301.zip)

**Comment by Spirit-Warden** [comment]
Sadly I've already done a clean install of KOTOR, without the CP installed this time. But I could try creating a 2nd installation if GOG allows me to do that.

**Comment by DarthParametric** [comment]
I managed to find a save where Canderous was ready to pop Jagi and confirmed the existence of the bug and the fix, so no need.
