### ISSUE TITLE
Consular Sentinel Class Skills

### ISSUE THREAD

**Issue by darthbdaman** [KOTORCommunityPatches/K1_Community_Patch#381]
Currently, the Jedi Guardian and Sentinel get the Awareness, Persuade, and Treat Injury skills, while the Consular get those, plus the Computer Use, Demolitions, and Repair skills.

I don't see anyway that this could be intentional. The Sentinel gets more skill points, and is supposed to be the skill class. It really doesn't make any sense for the Consular to get more class skills, when it gets less skill points, and is not presented to the player as a skill class. The Sentinel should have those class skills.

I've never been sure if this is really a bug or not, but I just can't see any way that this makes sense, or could even have been the developers intent.

**Comment by DarthParametric** [comment]
How does this compare to the base TSL Sentinel and Consular?

**Comment by darthbdaman** [comment]
In K2 they have slightly different skills. They all have Awareness, Persuade, and Treat Injury, same as in K1, plus:

Guardian: Demolitions
Consular: Repair
Sentinel: Computer Use, Security, Stealth

In K1 the Guardian and Sentinel have Awareness, Persuade and Treat Injury, and the Consular has those plus:

Consular: Computer Use, Demolitions, Repair

**Comment by DarthParametric** [comment]
So switch all of them to the TSL distributions then, including Guardian? Demolitions certainly seems more up their alley than either Sentinel or Consular.

**Comment by darthbdaman** [comment]
I think that would be fine, and makes more sense. The only other thing is that Sentinels get more skill points in TSL (from 2 -> 3), and Consulars get more points (1 -> 2), Guardians stay at 1.

**Comment by DarthParametric** [comment]
Thoughts @Mako88 and @JCarter426 ?

**Comment by JCarter426** [comment]
There are other differences with the skills at play here (Jedi being starting classes in K2, WIS vs INT for security, plus what the skills actually do in the game) so I'd be wary of making too many changes just because things were changed for the sequel, which has somewhat different gameplay.

I think you could make a case for swapping consular and sentinel, though.

**Comment by Mako88** [comment]
I personally always use your mod @darthbdaman for my playthroughs. I agree with JC, I don't think a complete skill overhaul is the way to go, but just swapping Consular and Sentinal makes sense IMO.

**Comment by DarthParametric** [comment]
So is that just implementing darthbdaman's mod as-is then?

**Comment by darthbdaman** [comment]
I think that's the most broadly acceptable idea
