### ISSUE TITLE
Manaan East Central - Missing quest update when Force persuading Gluupor

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#382]
In the man26_gluupor.dlg file we should add Quest Entry 20 in either E7 or E8. The way it is now, there won't be any journal update for Force Persuading Gluupor into revealing he planted the medal on Elassa.

**Comment by DarthParametric** [comment]
Seems like that branch is kind of weirdly arranged. There are a whole bunch of player nodes that come after the Force persuade option, whereas a successful regular persuade just goes straight to an end node.
