### ISSUE TITLE
Manaan Atho West - Missing Persuasion Check

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#383]
In the man26_sunry.dlg file E54 is missing the persuasion check. I suggest we add k_con_pershigh as conditional script there.

As a side note, in case of failed check there is an apparently unused line where you could confront Sunry saying you know about the affair thanks to some datapad (W_RDATAPAD) which must be one of the many cut items.

**Comment by DarthParametric** [comment]
That's probably the cut evidence that was originally in the Sith base.
