### ISSUE TITLE
Dreshdae - Spurious animation in Shaardan's dialogue file

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#385]
There is an odd animation which sometimes (oddly, it doesn't always happen...) freeze Shaardan at E2 in Shaardan's dialogue file (kor33_shaardan.dlg).

**Comment by DarthParametric** [comment]
Looking at dialoganimations.2da, row ID 40 is TALK_FORCEFUL, although I don't know that that particularly suits the line.

**Comment by Salk73** [comment]
I'd say that no, it doesn't fit with the tone of the delivered line (I think Shaardan is somewhat flattered rather than angry).

If I remember correctly you said TSL Patcher cannot delete animations but we could still change it to TALK_NORMAL.
