### ISSUE TITLE
Tatooine Swoop Registration - Issues with completion of the "Unfinished Business" quest

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#387]
It seems like there is a problem with both awarding plot XP and two missing window pop up for journal updates (ID25 and ID30).

The journal gets actually updated but no pop up window appears after returning from the Rakhata prison and after delivering the box to Motta on Tatooine.

**Comment by DarthParametric** [comment]
Not sure about the prison, but I'd expect there's a module transition directly from a DLG, which is possibly why that one fails to provide a pop-up. 

For Motta, the quest updates are on reply exit nodes of the DLG. Seems like that shouldn't make a difference, but changing it to an earlier entry node (or a script) would be worth testing I guess.

**Comment by Salk73** [comment]
I don't have a save game handy at the moment but I don't think the quest updates on the reply exit nodes worked but I may be wrong.

**Comment by DarthParametric** [comment]
I got the pop-up when handing in the box:

![Unfinished_Business](https://user-images.githubusercontent.com/46890653/139571187-3455c3ef-585d-4f2e-9db8-74106fbdbf26.jpg)

**Comment by Salk73** [comment]
Alright.

I can confirm that the journal gets updated using original game files but I still miss the XP which is something that doesn't happen to you from what I can see.

How does the game awards Plot XP though? You received 500 XP from completing the mission but in the original global.jrl file ID 30 has 0 for XP_Percentage.

**Comment by DarthParametric** [comment]
That's drawn from plot.2da, not the JRL.

**Comment by Salk73** [comment]
Right, thanks for the information.

There must be something weird on my side then because my game is using the original plot.2da file and I removed the Tatooine Swoop Registration module from it and I still do not get any XP award. Weird.

**Comment by DarthParametric** [comment]
Per some [discussions on the DS Discord](https://discord.com/channels/259507540503691267/259507540503691267/1158820944672981013), it appears there are some issues with the changes to Motta's DLG as they currently stand (which may be different to the source config). It seems like the quest will be orphaned if you ask for more money but fail the persuade check.
