### ISSUE TITLE
Failing to bribe Sarna is robbery

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#388]
(Reported by Kattmandu.)

The dialogue option `[Persuade] Make it 100 credits and we have a deal.` leads to a loss of 100 credits even if one fails the skill check and Sarna refuses to hand over the uniforms. Can be repeated indefinitely until you're out of credits, too.

Note:
- Should also check Yun, might have the same problem.
- I also recall hearing dialogue in which it's 1000 or 2000 credits vs 100 or 200, so we should also check that the right amount is being taken across the board.

**Comment by DarthParametric** [comment]
The really weird thing about this is that it the `k_con_credxxx` / `k_act_credxxx` scripts are local, not global. And there are also scripts for dealing with 100/200/1000/2000 credits, even though only the Sarna/Yun DLGs use them and only the 200 credit ones.

**Comment by Salk73** [comment]
I had fixed locally this one a long time ago and forgot to report it here.

On a side note, I am displeased with the fact that the developers chose a meager sum (200 or even 100 credits if persuasion is successful) for the bribe with the VO calling it a "small fortune".
