### ISSUE TITLE
Ahlan and Alhan Matale are used interchangably in the Dialog.tlk

### ISSUE THREAD

**Issue by jeroennieuw** [KOTORCommunityPatches/K1_Community_Patch#389]
I've been working on the eXtreme Dialog Overhaul for a while now and I found out that Ahlan (56 entries) is mixed up with Alhan (14 entries) in the dialog.tlk

I don't know what issues this may cause, if any, but Alhan is used in spoken text (line 6380) but also as waypoint (?) (line 7957), and other lines.
![Annotation 2020-05-22 143108](https://user-images.githubusercontent.com/22746617/82667834-e5756880-9c38-11ea-9d78-9de7d9c8c62c.png)

If no issues then at least for consistency's sake line 6380 should be patched.
I hope I made this post is in the right place.

**Comment by jeroennieuw** [comment]
Not the place for this kind of content/errors. I will close this thread.

**Comment by JCarter426** [comment]
We have an issue for any dialog.tlk problems [here](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/148).

For the time being we don't plan to fix any with the Community Patch given the lack of patching capability for dialog.tlk, but such a tool may be developed to make it possible in the future.
