### ISSUE TITLE
Party member facing when disembarking from the Ebon Hawk

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#392]
It seems like whenever a party of three is spawned after disembarking the Ebon Hawk, one party member has a correct facing (looking ahead) while the other one is facing the protagonist.

It is possible that the game uses the same party jump script in every circumstance.

**Comment by DarthParametric** [comment]
It doesn't use any by default. The player should get spawned at the module entry point and the party members will appear randomly within a few meters. They may then get jumped by the OnEnter or a trigger, but not necessarily. And typically only the player is jumped anyway, so the party members again just end up randomly positioned nearby. There are only a handful of very specific circumstances where the full party is allocated unique positions, and even then every example is typically fairly slipshod in execution, being weirdly positioned in combination with using waypoints (which the target will always end up offset from by at least 1m).
