### ISSUE TITLE
Endar Spire - Trask won't be on the other side the door when the conversation starts

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#394]
It feels like it may be a local problem of mine because I don't understand otherwise how it could have not been reported before but I still add this issue in case some safety measure could be safely added without negative side effects.

The conversation that Trask has with the Player starts at times while he is still on the other side of the door. The door will be subsequently shut off causing a game breaking bug.

I wonder if it is some timing issue related to _k_pend_cut09.ncs_? 

Something I have not yet understood is: what is the UD script for the Player? It seems the script above calls for it there.

**Comment by DarthParametric** [comment]
Interestingly, he is commanded to run to an object with no Tag:

`ActionMoveToObject(GetObjectByTag("", 0), TRUE, 1.0);`

I gather that must be the player? Seems like a very odd way to handle it. I would trying running him to a waypoint or location and see what happens.  We use `Location(Vector(16.34,20.5,-1.27), 180.0)` to position party Trask at approximately the same position.

**Comment by Salk73** [comment]
What I did was to simply open the door during the waking up cutscene and the problem was gone. Since the door is off camera when that happens it doesn't really cause any kind of issue.

I can of course test this further giving Trask a location to move to, if necessary.

**Comment by DarthParametric** [comment]
Given I have never seen this reported by anyone else, nor experienced it myself, I'm leaning towards this being a specific issue on your end. Unless you can reproduce it on a pure vanilla build of the game.

**Comment by Salk73** [comment]
Found the culprit in one custom change made to the k_ai_master script.
