### ISSUE TITLE
Manaan Docking Bay - Ithorak fights without weapons

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#398]
Not really a bug but I know we've provided weapons to NPCs fighting with their bare hands before.

This guy is supposed to be one GenoHaradan leader and he should be properly armed.

**Comment by DarthParametric** [comment]
He has a heavy blaster pistol in his inventory, so it's just the usual AI problem of him not equipping it. He starts out neutral, so it should be easy enough to have the script that sets him hostile equip the weapon first.

**Comment by Salk73** [comment]
I have it and I can very easily test it.

We also need to change Ithorak's soundset from 33 to 60.

**Comment by Salk73** [comment]
Testing successful.
