### ISSUE TITLE
[Tatooine - Dune Sea] Issue(s) with Hulas encounter

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#399]
I have two issues with this encounter. 

The first one is something I have verified to be confirmed when I watched a few videos about the confrontation: there is a Rodian among the opponents that looks exactly identical to Hulas. I believe an appearance edit is in order here.

The second instead is something which may as well be (yer another) local issue of mine: when hulas call the charge and plays the Victory animation at E7 (_tat18_hulas.dlg_) the weapon he is wielding disappears to reappear again when the fight starts. In the two videos I watched, this doesn't happen though.

**Comment by DarthParametric** [comment]
The second issue is almost certainly on your end. I'd suggest you've set the root node of the DLG to hide equipped weapons, which kicks in when he plays the anim.

One of the thugs (tat_thug1.utc) does share the same appearance ID (257 - Alien_Rodian_03), which is presumably a result of Bioware switching Hulas from a Duros to a Rodian at some point. An easy fix.

**Comment by Salk73** [comment]
I have no doubt the second issue may be local. I have (had) a good number of those... But the root node of the DLG is not set to hide equipped weapons.

Here's a video of what it looks like on my sad side: https://youtu.be/f3Rr-d0bw6w

**Comment by DarthParametric** [comment]
Using the mod that edits animations.2da to hide weapons during cutscenes then.

**Comment by DarthParametric** [comment]
More importantly, I notice he has already popped his energy shield at the start of the cutscene. That looks like an issue Sniggles reported with companions during the Lehon beach scene that I could never reproduce. Should probably address that too.

**Comment by Salk73** [comment]
The shield being activated at the start of the cutscene is intended, I think. I would not change it, honestly.

You were very right instead about the .2da edit. It hides weapons when playing the victory animation. I don't see much of a reason for it though so I think I'll revert that. 

Thanks for your help with this.

**Comment by DarthParametric** [comment]
There's no evidence in any of the related scripts that it is intentional (and his UTC doesn't even use any custom scripts, just generics).

**Comment by DarthParametric** [comment]
He doesn't pop the shield on my end until combat begins, so in the absence of further evidence I will put this down to Salk's version being screwed up (again).

**Comment by Salk73** [comment]
What happens in my case is that Hulas activate the shield 6 seconds after the area is loaded, actually. Doesn't this happen to you too?

**Comment by DarthParametric** [comment]
No. He manually activates it when combat starts post-conversation (including an activation animation).
