### ISSUE TITLE
Dustil's premature death

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#4]
If you kill Dustil while looking for proof, Carth will continue looking for proof instead of realizing that Dustil is dead.

**Comment by DarthParametric** [comment]
So I have a save to test this. I just have initiated the quest to find evidence, but after you have done that you can no longer turn him hostile through dialogue. So I guess the only way is if you end up killing Uthar and Yuthura, setting the whole academy hostile?

**Comment by JCarter426** [comment]
You can kill Uthar and Yuthura, or kill Uthar and convince Yuthura to leave Korriban.

**Comment by DarthParametric** [comment]
Well that's an aside, my point was the only way to turn him hostile after having agreed to find evidence is to turn the entire academy hostile.

**Comment by JCarter426** [comment]
Yes, that's the issue - he goes hostile along with the rest of the academy if you finish Korriban with one of those two endings before finding the evidence.

**Comment by DarthParametric** [comment]
Which is a real pain in the ass to test, since I'd have to replay the entire planet. I wonder if I can just trigger whatever happens directly via script. Must be a global checked by the OnEnter or something?

**Comment by JCarter426** [comment]
Yeah, that's why I didn't test it way back when.
I've looked into some stuff since then, though. I believe entering the academy with the global `KOR_END_HOSTILE` will trigger everyone hostile. The other global determining the Korriban ending is `KOR_FINAL_TEST` and states 4 and 7 trigger the hostile ending.

**Comment by DarthParametric** [comment]
Yeah I just threw the `k_pkor_end_host` script that fires in the Valley if you leave without Uthar onto one of the end nodes in Dustil's DLG and that turned him hostile. As expected, no change from Carth. Will add your OnDeath script and see what happens.

**Comment by DarthParametric** [comment]
Looks like the Finding Dustil quest is still active after killing Dustil and Carth being on the "he's dead and it's all your fault" track. Seems if needs an addition something like:

```
	if ((GetJournalEntry("kor35_findingdustil") <= 25))
		{
			AddJournalQuestEntry("kor35_findingdustil", 40, FALSE);
		}
```

**Comment by DarthParametric** [comment]
How's this look?

```
#include "k_inc_switch"

void main() {

	SetGlobalNumber("KOR_DANEL", 5);
	SetGlobalNumber("K_SWG_CARTH", 99);
	
	if ((GetJournalEntry("kor35_findingdustil") == 10))
		{
			AddJournalQuestEntry("kor35_findingdustil", 50, FALSE);
		}

	if ((GetJournalEntry("kor35_findingdustil") == 20))
		{
			AddJournalQuestEntry("kor35_findingdustil", 60, FALSE);
		}

	if ((GetJournalEntry("kor35_findingdustil") == 25))
		{
			AddJournalQuestEntry("kor35_findingdustil", 70, FALSE);
		}
		
	//Carry out vanilla k_def_death01 function
	ExecuteScript("k_ai_master", OBJECT_SELF, KOTOR_DEFAULT_EVENT_ON_DEATH);
}
```

50, 60, 70 states would need to be added to the JRL.

**Comment by JCarter426** [comment]
Looks good to me. Another thing that may be an issue is the scene firing while other hostiles are nearby. But if we wrap everything else first, I'll see if I can test that issue when I get to Korriban.

**Comment by DarthParametric** [comment]
I don't think that is actually possible, is it? That's something else we'd have to address. I think the OnEnter might just destroy him outright if the academy has gone hostile.

**Comment by JCarter426** [comment]
The bug report was that Dustil goes hostile along with everyone else, although I've never bungled the quest that way so I'm not sure.

Carth is meant to say a few lines after Dustil dies when you kill him normally, as I recall. And normally there are no other hostiles in the area, so it shouldn't be an issue - but it might be if he's killed along with everyone else in the academy. I have a vague memory that they might be bark bubbles instead of a cutscene, though, so it might be ok.

**Comment by DarthParametric** [comment]
I killed Dustil when first meeting him (so non-hostile academy) Carth doesn't say anything unprompted that I recall. You manually talk to him, ask him "Do you want to talk about it?" and he goes off about how it's your fault for not talking Dustil down.

**Comment by JCarter426** [comment]
Huh, the dialogue I was thinking of must have been unused:
![Dead Dustil](https://user-images.githubusercontent.com/46898647/58263845-c9e83100-7d4a-11e9-80d8-61406342369a.png)

**Comment by DarthParametric** [comment]
I think the line itself is actually used, just not standalone like that.

**Comment by JCarter426** [comment]
Carth didn't say anything when I killed Dustil, so I suspect it may be bugged like the Gana Lavin encounter was. I believe the fix for that was to make it a bark bubble instead of a dialogue.
Also, after I killed Dustil (this is still the non-premature way) I couldn't interact with anything until I saved and reloaded.

**Comment by DarthParametric** [comment]
Thoughts on these for new journal entries?

Quest at stage 10 - Jordo has told Carth is on Korriban:
`You never managed to find Dustil and talk to him before the whole Academy turned against you. It seems that you inadvertently killed him while defending yourself. Naturally Carth now blames you for Dustil's death, saying that you could have done more to find him.`

Quest is at stage 20 - You talked to Dustil and promised to find evidence:
`You found and spoke to Dustil, promising to find evidence of the true nature of the Sith. Unfortunately, you didn't manage to discover anything useful before the whole Academy turned against you, including Dustil. You were forced to defend yourself, and Dustil was killed. Carth now blames you for Dustil's death, saying that you could have done more to help change his mind.`

Quest is at stage 25 - You found the datapad in Uthar's room:
`You found proof of Uthar's direct role in the death of Selene. Unfortunately, you failed to show it to Dustil before the whole Academy turned against you, including Dustil. You were forced to defend yourself, and Dustil was killed. Carth now blames you for Dustil's death, saying that you could have done more to help.`

**Comment by Mako88** [comment]
I think those look good!

**Comment by Salk73** [comment]
The only thing I would change is the end in Q stage 10 (to avoid using the verb "find" again): "... to track him down."

**Comment by DarthParametric** [comment]
Done. Although these changes haven't been committed yet anyway, since they are still awaiting testing.

**Comment by JCarter426** [comment]
So, I tested by killing Dustil before ever talking to him, and got this:
![swkotor 2019-08-04 10-51-02-05](https://user-images.githubusercontent.com/46898647/62425165-0bc81880-b6a6-11e9-971b-63c029fe5e54.png)
That might be down to the incomplete install. Carth did react properly, blaming me for Dustil's death.

It should be noted that the journal entry was updated before I spoke to Carth and therefore before he gets a chance to blame me, as it says in the journal. But it also does that if you kill him the normal way.

**Comment by DarthParametric** [comment]
Well that's unique at least. Did you check the JRL in your Override? What do the structs for Tag `kor35_findingdustil` look like? You're using the script from above?

**Comment by JCarter426** [comment]
Looks like it set the string references as lines 24, 25, and 26 in the TLK. The one I got is line 24, which corresponds to quest state 50.

**Comment by DarthParametric** [comment]
Oh crap. Did I not include append.tlk? Crap.

**Comment by DarthParametric** [comment]
So one remaining issue, albeit something of an edge case, is that once the Academy goes hostile, you can still find the datapad in Uthar's room and get the scene of Carth saying that it can help convince Dustil (despite the whole place trying to kill you). Seems like it needs to be destroyed in the OnEnter if the Academy is hostile.

**Comment by DarthParametric** [comment]
Another apparent problem. It seems that the intended journal entry for finding the datapad is not added. It should get updated to stage 25:
```
Carth's son has been found, but the reunion was not exactly what he'd hoped. Dustil does not believe anything Carth has to say on the true nature of his new "family". You have found a datapad belonging to the master of the academy which Carth believes will be proof of the Sith's true nature. He wants to return to Dustil as soon as possible with it.
```
But it seems it remains stuck on 20. Carth's DLG that fires on looting the footlocker has a script (k_pkor_car35tkpd) that takes the datapad from the PC (for some reason), so that could be amended to update the quest state.
