### ISSUE TITLE
Helena after the Leviathan

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#40]
(reported by LiliArch)

It's possible that Helena Shan, Bastila's mother, spawns in the cantina on Tatooine after Bastila is no longer in the party.

We need confirmation on this, but a fix shouldn't be a big deal. I believe the cantina OnEnter is already edited in the Community Patch to fix some issues with her not spawning. There's some stuff in other areas with a Duros that leads you to her too, though, as I recall.

She should also be removed if she spawned in the cantina legitimately before the _Leviathan_, but you never took Bastila to see her.

**Comment by DarthParametric** [comment]
> There's some stuff in other areas with a Duros that leads you to her too, though, as I recall.

The Duros spawns outside the Czerka office and triggers a cutscene complaining about what assholes humans are, based on his interaction with Helena. This only happens after you get the Twi'lek messenger exiting the Hawk that triggers the quest. I've never seen him anywhere else, and it's just the single convo. I would guess there is a trigger that fires a script with a conditional to launch the cutscene/convo for a given global value.

**Comment by JCarter426** [comment]
I think I found the script for that, k_ptat_maanatrig, but it wouldn't decompile for me. Possibly the UTT file for it could be edited though, so it only executes the original script if it's before the _Leviathan_.

**Comment by JCarter426** [comment]
I've added a fix for the Duros, but I don't have a save to test it.

**Comment by Salk73** [comment]
I tested this by loading a saved game before entering Anchorhead and manually setting K_SWG_HELENA to 2 and K_CAPTURED_LEV to 11. 

It seems to work fine. The Duros doesn't spawn.

**Comment by DarthParametric** [comment]
I'm going to call this closed for now. We can re-address if future bug reports indicate the need.
