### ISSUE TITLE
Player Head - PFHB03 eyelid clipping and bad UVs

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#401]
The player head PFHB03 has some clipping issues with the eyelids (especially the left), the eyeball UVs are not mirrored correctly (again, particularly the left), and the head/scalp is extremely bumpy for what are supposed to be cornrows.

![eyelid](https://user-images.githubusercontent.com/46890653/85218176-02898c80-b3db-11ea-8e86-679a2eb93b85.png)
Picture stolen from Dark Hope

Reported by Dark Hope and La Ingobernable

https://deadlystream.com/topic/7953-pfhb03-model-fix/

https://deadlystream.com/topic/8097-request-pfhb03-clipping-asymmetrical-eyelid

**Comment by LaIngobernable** [comment]
I looked into this a little more and it seems the clipping occurs because that first conversation with Carth uses a different listen animation, in which the eyebrows are arched more intensely. I see no trace of this clipping during the usual listen animation.

**Comment by LaIngobernable** [comment]
While doing some more testing I noticed that her eyes doesn't seem to close all the way when thrashing about her sleep (when having visions).

**Comment by DarthParametric** [comment]
Those are stunt animations. Nothing you can do about that without screwing it up for other heads. It's Bioware's fault for not having a standardised head mesh setup.
