### ISSUE TITLE
[Ebon Hawk - Man the turret] The attack happens before the Player can see what is happening

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#406]
Due to a delay in the fade in (or a too hasty return to action), the Sith vessels are able to attack the Ebon Hawk while the Player has not yet gained visual control.

It may be intended but it doesn't feel right or fair.

Perhaps the first incoming attack can be delayed with 3-4 seconds?

**Comment by DarthParametric** [comment]
The turret sequences aren't dynamic. It's a number of set animation tracks for the fighters and the game randomises which one it picks when the minigame is initiated. As such, changes aren't particularly easy to implement and something that's better off left to a dedicated mod.
