### ISSUE TITLE
[Leviathan - Prison Block] Lead party member off camera when addressed by Carth or Bastila

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#408]
A very minor thing but we have been fixing camera issues many other times so I thought it might be worth reporting it.

When the party member selected to free the Player, Carth and Bastila on the Leviathan opens the prison's door, a cutscene starts and the party member is either addressed by either Carth or Bastila (camera 7 is used) but it seems it stays off camera.

The LISTENER tag is empty but perhaps it should just be a matter of changing the camera's FOV?

**Comment by DarthParametric** [comment]
This is the developer's intent, since it uses a static camera.
