### ISSUE TITLE
Juhani lacks a soundset in the grove

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#41]
(reported by ebmar)

When the player fights Juhani in the grove, she lacks a soundset. Alas, the fix isn't as simple as assigning Juhani her usual soundset, as it contains lines such as "For the Order!" and "THAT is what a Jedi can do!" and it wouldn't make sense for her to say such things in that situation. Making a new SSF file that excludes these lines is easy enough, and I've done that, but the implementation would be messy. It would require a 2DA edit and one or two TSLPatcher tokens. That makes me wonder if it's worth it for the Community Patch, but it could be done.

**Comment by DarthParametric** [comment]
It's not really that messy. We are already editing appearance.2da and the Grove module anyway. I think it would be fine as a Tier 3 option.
