### ISSUE TITLE
[Kashyyyk / Great Walkway] Gap in tree mesh

### ISSUE THREAD

**Issue by Kexikus** [KOTORCommunityPatches/K1_Community_Patch#415]
Not sure if that's part of the scope of this project but I just noticed a gap in one of the trees in kas_m22ab - The Great Walkway.
You can see it in the upper middle of this screenshot: [https://i.imgur.com/upelGf3.jpg](https://i.imgur.com/upelGf3.jpg)
This is right in front of the entrance to the Wookiee village in the large tree that the plattform is built around.

**Comment by DarthParametric** [comment]
The issue was that mesh chunk was offset vertically for some reason. It just needed to be bumped up in height a bit. Fixed, although the lightmap issues remain:

![m22ab_09a_Tree_Fix](https://user-images.githubusercontent.com/46890653/104177272-3b12b580-5454-11eb-95b2-8f3ad3cacd10.jpg)
