### ISSUE TITLE
[Tatooine - Anchorhead] Travelers seem to like flying around in sand

### ISSUE THREAD

**Issue by Kexikus** [KOTORCommunityPatches/K1_Community_Patch#416]
The background ships flying around Anchorhead have a weird texture assignment (LTA_wall02) that looks like sand. I think this is probably a mistake since first it looks stupid and second the ships in the Dune Sea module use LTA_trm03 which looks much better.
Personally, I think LTA_trm02 looks even better though. See the picture below.

![Tatooine-Ships](https://user-images.githubusercontent.com/51493329/88418439-d56a3880-cde3-11ea-9122-7ffb51c00460.jpg)

**Comment by DarthParametric** [comment]
Is this in the skybox model? Is that going to clash with your mod?

**Comment by Kexikus** [comment]
It is, yes. But I made the same change for my mod so that my model could just override yours for people that use both mods.

**Comment by DarthParametric** [comment]
In that case I'd say we should just leave it to your mod to handle then, since it's a minor aesthetic issue with minimal impact that really lies outside K1CP's purview.
