### ISSUE TITLE
Snorting Corpse Pile

### ISSUE THREAD

**Issue by StellarExile** [KOTORCommunityPatches/K1_Community_Patch#418]
Reported by [agreydawn](https://www.reddit.com/user/agreydawn/) on r/kotor.
Apparently, there's a [dialogue error](https://www.reddit.com/r/kotor/comments/i21nxy/replaying_recently_found_an_interesting_bit_of/) which causes the corpse pile to be the speaker instead of the Rancor.

**Comment by DarthParametric** [comment]
It's not an error. It's fairly standard practice to use placeables as a DLG owner, especially in instances like this where an NPC is destroyed. The rancor can't be the owner, so it will need an invisible placeable that uses that name. Bioware just got lazy.

**Comment by StellarExile** [comment]
134340Goat did say he's seen a lot of them, like "StrRef" as the speaker but maybe it is because of the same thing.

**Comment by DarthParametric** [comment]
Fixed with the simple addition of a Speaker tag for the Rancor:
![Rancor_Snort](https://user-images.githubusercontent.com/46890653/92572437-ca059a80-f2c7-11ea-810a-c086cfb41089.png)
