### ISSUE TITLE
Boxing Duros on Dantooine

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#42]
(reported by ebmar)
The Mandalorians' Duros allies in the grove on Dantooine fight with their fists when engaging in melee. Apparently they actually have weapons, but lack the feats to use them.

**Comment by DarthParametric** [comment]
Looks like there are four Mando Duros:

dan14ac_duros01
Blaster pistol equipped, no melee weapon in inventory.
Weapon Focus: Blaster Pistol
Weapon Focus: Melee Weapons
Weapon Focus: Simple Weapons

dan14ac_duros02
Heavy repeater equipped, vibroblade in inventory.
Weapon Proficiency: Blaster Pistol
Weapon Proficiency: Blaster Rifle
Weapon Proficiency: Heavy Weapons

dan14ac_duros03
Light repeating blaster equipped, vibroblade in inventory.
Proficiency All

dan14ac_duros04
Mandalorian blaster equipped, vibroblade in inventory.
Proficiency All

So we can add Proficiency All to 01/02 and additionally add a vibroblade to the inventory of 01.

There is also dan14_duros, but this one has no equipment or inventory and no feats. It is named "Duros Warrior" though. Possibly used for a corpse?

**Comment by Mako88** [comment]
Are there Duros in any other module on Dantooine that should be checked? I seem to recall there are some in at least one other module.

**Comment by JCarter426** [comment]
Looks like the ones in m14ab have the same issue.

**Comment by JCarter426** [comment]
Done.
