### ISSUE TITLE
Gas mine code has logical error

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#425]
([reported by AmanoJyaku](https://deadlystream.com/topic/7611-a-new-dencs/?do=findComment&comment=78430))

The script k_trp_generic has a logical error here:
```
    //GAS POISON TRAP
    else if(nTrapID == TRAP_BASE_TYPE_POISON_GAS_MINOR ||
                       TRAP_BASE_TYPE_POISON_GAS_AVERAGE ||
                       TRAP_BASE_TYPE_POISON_GAS_DEADLY)
```
Following C-like logic, this is equivalent to
```
else if(nTrapID == 1)
```
so it seems this block of code will never evaluate, because the mine with the value of 1 is already checked above this.

**Comment by DarthParametric** [comment]
It's presumably supposed to be like this?
```
	else if(nTrapID == TRAP_BASE_TYPE_POISON_GAS_MINOR ||
		nTrapID == TRAP_BASE_TYPE_POISON_GAS_AVERAGE ||
		nTrapID == TRAP_BASE_TYPE_POISON_GAS_DEADLY)
```

**Comment by JCarter426** [comment]
Yup.

It looks like it has a main() function so it should be standalone.

**Comment by DarthParametric** [comment]
So as far as I can tell, both Average and Deadly versions of the Gas Mine work perfectly fine, despite the apparently invalid script. Both correctly apply the right amount of poison per tick (4 and 5 respectively, for those two). The pool in the Vulkar base is a good place to test, since it has three Deadly variants in a row. You just need a high enough Awareness to spot them.

![Deadly_Gas_Mine](https://user-images.githubusercontent.com/46890653/93020522-e9325e00-f620-11ea-8efa-16d0120eba39.jpg)

**Comment by JCarter426** [comment]
Ah, I looked through it more carefully and realized my first reading of it was wrong. The last else if condition is always going to be true, even if the ID isn't one for gas mine. So when it is a gas mine, it actually does work correctly.
```
nTrapID == TRAP_BASE_TYPE_POISON_GAS_MINOR
```
If it's minor gas, this is true and we can ignore the other conditions, if false keep checking.
```
|| TRAP_BASE_TYPE_POISON_GAS_AVERAGE
```
Because the id is 10 and 10 is not 0, this is equivalent to "or true" so the next condition is always true, so the overall condition is always true. And then there's another "or true" for good measure.

That raises the question of whether we should bother fixing it. It does actually work for all the game mines. It's just bad code is all.

**Comment by DarthParametric** [comment]
I noticed that Obsidian did fix it in TSL (as well as adding new stuff), but I question the necessity of adding an extra script to the Override if it effectively does nothing.

**Comment by JCarter426** [comment]
Yeah, fine by me. At least now we got the details of the problem on record here.
