### ISSUE TITLE
Going back to the academy on Korriban after having killed Uthar + Yuthura: HK-47 spawns in the central room, and not near the entrance

### ISSUE THREAD

**Issue by Myrthian** [KOTORCommunityPatches/K1_Community_Patch#426]
- I killed both Uthar + Yuthura in the tomb
- Back in the academy Juhani spawns close to the entrance, but HK-47 spawns all the way back in the circular room in the middle where Uthar prays 

I tried it several times and it's always the same: HK-47 always spawns in the circular room.

**Comment by DarthParametric** [comment]
While using K1CP v1.8+?

**Comment by Myrthian** [comment]
Oh right, forgot to mention the version: yup, 1.8.1.

**Comment by DarthParametric** [comment]
And what other mode are you using? Any large/intrusive mods like K1 Restoration?

**Comment by Myrthian** [comment]
https://i.imgur.com/soRNnsk.jpg

**Comment by DarthParametric** [comment]
Oh you're the guy from DS. Yeah your install is completely broken. The solution is to uninstall and start from scratch without using a bunch of conflicting mods. 

Since there's no evidence that any of your bug reports are related to K1CP, I am going to close the related issues.
