### ISSUE TITLE
Companions can't keep up with Burst of Speed, especially HK-47

### ISSUE THREAD

**Issue by Myrthian** [KOTORCommunityPatches/K1_Community_Patch#427]
Something I've been noticing rather frequently: when I charge ahead with Burst of Speed companions can't keep up, especially HK-47. 
In those instances they're lagging behind as far as half of the current map, and it's far worse in narrow pathways like Taris sewers, Anchorhead or Sith academy.

**Comment by DarthParametric** [comment]
This is not something K1CP is ever likely to address.
