### ISSUE TITLE
Griff doesn't spawn

### ISSUE THREAD

**Issue by Myrthian** [KOTORCommunityPatches/K1_Community_Patch#428]
Previously on Tatooine: 
- Finished the Jawa rescue quest
- Resolved the Sand People quest in a peaceful manner by getting them the moisturizer
- Opened every door in the enclave

Now before doing Manaan as the final planet I backtrack to finish the companion quests.

As for the quest itself:

- Saw the cutscene with Laura and Mission talking about Griff
- Went to Tatooine to talk to the Protocol Officer in the Office, and she mentioned the Sand People
- Talked to the chieftain with HK-47, asked about prisoner, then about Griff
- Did several rounds in the enclave but no Griff

I'm on 1.8.1
Save game while being in the enclave prior to talking to the chieftain: https://www.file-upload.com/31gbr3mpoehk

**Comment by DarthParametric** [comment]
Enduser issue. See https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/426#issuecomment-687755195
