### ISSUE TITLE
Xor: can't talk to him after beating him

### ISSUE THREAD

**Issue by Myrthian** [KOTORCommunityPatches/K1_Community_Patch#429]
- Triggered the 1st Xor cutscene and got the quest
- Triggered the 2nd cutscene and fought him, but now I'm unable to talk to him

1.8.1
Save game once I defeated him: https://www.file-upload.com/ae97pf87d9fi

**Comment by DarthParametric** [comment]
This is a duplicate of #8. The issue has never been resolved because it cannot be reliably reproduced.

**Comment by JCarter426** [comment]
If you have a save file that can reliably reproduce it though, we'd like to see it.
