### ISSUE TITLE
Taris Upper Sewers - Rancor corpse pile interactive after quest completion

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#430]
After you successfully kill the Rancor, it looks like the developer intent was that the corpse pile would no longer be interactive. However it remains so. Perhaps the best route might be to destroy it post-quest. Since the placeable itself is the owner of the DLG and scripts for the Rancor cutscene/s, it might be best to switch the inventory portion over to an invisible placeable.

Additionally, JC has come up with a method to filter the Give Item inventory screen so that only the desired/relevant items show up (see pic below), so that could also be added at the same time.

![Rancor_Give_Item](https://user-images.githubusercontent.com/46890653/92436086-2c3a9e80-f1e7-11ea-9cae-e2f1503b6709.jpg)

**Comment by StellarExile** [comment]
Odd, I also know that the Rancor corpse is bashable after you feed it synthesized odor. Not sure if it was intentional. Maybe just a minor annoyance.

**Comment by DarthParametric** [comment]
It's because the script locks it.

**Comment by JCarter426** [comment]
Hmm, would it be possible to make it not possible to interact with it at all? Maybe via SetCommandable()?

**Comment by DarthParametric** [comment]
Pretty hard to interact with it after it has been destroyed.

**Comment by DarthParametric** [comment]
1.9.0 beta observations:
- [ ] As an addendum, the player will likely have leftover synthesised odours after killing the rancor. I think any remaining should be destroyed at the end of the scene.
