### ISSUE TITLE
Korriban Sith Academy - Mandalorian prisoner interrogation issues

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#434]
- [x] The Mandalorian prisoner inside the cage spawns off-center.
- [x] The Mandalorian prisoner will "disappear" upon dying from an overdose. Edit: This is intended for all paths except killing the torturer
- [x] When the Player uses the console the camera framing is quite off.
- [x] When the Player uses the console they are airtyping badly.

See video: https://youtu.be/FEzbpCh53ic?t=138

_Edited to be more concise - DP_

Additional issues:
- [x] The torturer can have trouble pathfinding past the party after the initial cutscene.
- [x] The torturer needs a facing command after his initial walk away from the console.
- [x] The Mando prisoner seems to ignore speaker/listener tags, possibly affected by `SetLockOrientationInDialog`.
- [x] If the player chooses to attack the torturer, the party members may stand by watching.

Further issues from Salk:
- [x] The trigger for the initial convo with the torturer can be bypassed, needs to be enlarged.

**Comment by Salk73** [comment]
I solved it by giving a new spawning position to the prisoner while I jumped the party to make sure the Player is close enough to the console.

I found that camera 5 worked well at E2 and E3.

If you want my changes I will report them here.

Additionally I took a look at the script that checks computer skill to determine failure or success (p_kor_computer.ncs) and it seems to me unnecessarily convoluted. I made a much simpler version, making sure that if the Player fails, there won't be another chance to do it again (it doesn't make any sense).

I will share anything that may be considered of any interest to K1 CP.

Cheers!

**Comment by DarthParametric** [comment]
Per [this report](https://github.com/KOTORCommunityPatches/K1_Community_Patch/commit/7a8d2ae72c6a92e8b12a45ad864ec0c78c2fe304#commitcomment-124999300), apparently there are still some issues.

**Comment by Salk73** [comment]
I have not yet built an armband for this specific purpose but I did add this to the script:
void CheckCommandable(object oPC, object oTorturer) {

```
  if (GetCommandable(oTorturer)) {
    SendMessageToPC(oPC, "Torturer is commandable!");
  }
  else {
    SendMessageToPC(oPC, "Torturer is NOT commandable!");
  }
}

...

DelayCommand(0.5, CheckCommandable(oPC, oTorturer));
```

I tested it several times and in each case (no matter whether the conversation triggered) the torturer was always commandable. I delayed the check to match the exact time the conversation should start. I guess that is not it.

**Comment by DarthParametric** [comment]
I never encountered a problem with it firing despite _numerous_ trigger enters over the course of two days of development and testing. 

You can try editing the trigger OnEnter itself to ping the feedback screen with whether or not it is passing the initial object and local boolean check.

**Comment by Salk73** [comment]
The trigger does fire each time. It's the conversation that does not.

**Comment by Salk73** [comment]
Yes, I agree.

If I find out anything at all, I'll let you know.

Thanks for the assistance.
