### ISSUE TITLE
[Korriban - Valley of the Dark Lords] Dak Vesser's health bar

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#435]
I met more than one NPC with a few HPs missing from their health bar (I think another was Lashowe at the Sith Academy) which should be full, at least for internal consistency.

At first I thought it was just a matter of changing the MaxHitPoints from 68 to 60 so that they'd match the CurrentHitPoints value but it seems that was not the solution.

**Comment by DarthParametric** [comment]
I'd go the other way. That's what I did in #237.

**Comment by Salk73** [comment]
That didn't make any difference.

The problem is in the spawn script (_k_pkor_spn_hrtbf_) which executes _k_def_buff_.

**Comment by DarthParametric** [comment]
You should be using `DURATION_TYPE_INSTANT`.

**Comment by Salk73** [comment]
I will change to that.
