### ISSUE TITLE
Sandral-Matale Feud doesn't finish properly

### ISSUE THREAD

**Issue by RoboGuthix** [KOTORCommunityPatches/K1_Community_Patch#438]
Running with roughly https://www.reddit.com/r/kotor/wiki/kotormodbuildfull - thought I'd check if this was known/unfixable but if not, happy to reproduce without other mods + more details and a save game if helpful.

After chatting to Juhani, Council ask me to look into Sandral/Matale feud. Not talking to the Matales at all seems to cause the issue: I go straight to the Sandrals, save Shen, convince Rahasia and Shen to go off together, and both parents decide I suck.

The quest entry is gone, but it seems the quest hasn't finished properly: Shen and Rahasia aren't at the enclave where I would expect, I can go to the Matale house and Ahlan comes out and has the initial introductory chat with me, and the Council still say I haven't done anything.

**Comment by DarthParametric** [comment]
I'm not sure that's anything to do with mods necessarily. Could be a vanilla issue. Sounds like the problem is that because the quest isn't initiated in the expected order, some variables aren't being set. We'll look into it.

**Comment by JCarter426** [comment]
I tested it and didn't run into Shen and Rahasia regardless of whether I spoke to the Matales first. It may be something we messed up with the globals from the other changes in the Community Patch.

**Comment by DarthParametric** [comment]
> didn't run into Shen and Rahasia

After otherwise finishing the quest? Or at all. I know I have completed it successfully with the wipe everyone out and best ending, but don't recall testing the elope outcome.

**Comment by JCarter426** [comment]
In the enclave after finishing the quest.

I know I tested all endings the first time around, but I must not have gone back to the enclave to double-check that.

**Comment by DarthParametric** [comment]
I've done a quick test and could not replicate this. I got the elope ending. Shen and Rahasia appeared in the Enclave as intended, and the Matale droid told me I was denied entrance and that a complaint had been lodged with the Council. I'll test it again more thoroughly during the 1.9 beta test, but at this stage it doesn't appear to be a K1CP or vanilla issue.
