### ISSUE TITLE
[Lehon - Temple of the Ancients] Gap in the wall

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#441]
I tend to believe it is unintended but I submit it to your judgement, DP.

The area is the Temple Main Floor (unk_m44aa) and the location can be easily surmised  by the screenshot I have attached.

![Image](https://user-images.githubusercontent.com/49585226/100196608-67e92880-2ef9-11eb-90a2-7e9513d4355c.jpg)

**Comment by DarthParametric** [comment]
This is a sub-issue of #375, since that issue already edits that room model (m44aa_17a).
