### ISSUE TITLE
[GLOBAL] Walking speed animation in cutscenes

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#445]
I don't know why but it happens in some cutscenes that the walking speed of party members is somewhat "accelerated", resulting in a very awkward outcome.

I have personally noticed this behavior at least three times in the Unknown World: once in the cutscene with The One when meeting him the first time, in the cutscene with the party meeting the Rakata warriors with Rancors that want to bring the Player to The One and the third time when the Player, Juhani and Jolee regroup with the rest of the crew at the Central Beach after the confrontation with Bastila.

And about the latter, I checked YouTube as usual and found a video that showcases the exact issue. The difference with my own local situation is that in my case only one of the two NPCs (Jolee) is being "hasted".

I don't find any rhyme or reason to this behavior since the NPCs are given exactly the same commands and there should be no difference whatsoever in the speed of the animation. I have locally worked around this but it's just a coat of paint and doesn't address the core of the problem.

Here's the link to the video: https://youtu.be/JAHfeGgZEms?t=1029 

The second video shows the same issue  (he remarks on the animation speed too): https://youtu.be/blBr63XCKp8?t=832

**Comment by DarthParametric** [comment]
It's a known issue and not resolvable as far as I am aware, not via any scripting method I have tried. I'd guess it's some issue with how the engine calculates the required traversal distance vs speed. Could be a > 30fps issue, which something that often affects console ports for things like physics calculations and so forth. Might be worth finding a scene where the speedup is repeatable at 60fps and then capping the game to 30fps to see if it still occurs.

**Comment by DarthParametric** [comment]
Going back through prior discussions the last time this came up, I discovered that using `SetCommandable` on NPCs exacerbated this issue, which was something we originally used in certain Include functions. It still occurs with that disabled, notably with Mission for example, so it's still not entirely curable.

See bba5c5f82f5f93b06425e3f84240266fceba1d2d

**Comment by Salk73** [comment]
@DarthParametric,

we have a solution for this and I am very glad to report it (thanks to JC's suggestion).

```
[2DAList]
Table0=heads.2da
Table1=forceshields.2da
Table2=appearance.2da
Table3=featgain.2da
Table4=visualeffects.2da
Table5=soundset.2da
**Table6=creaturespeed.2da

[creaturespeed.2da]
ChangeRow0=pc_walking_speed_1_0
[pc_walking_speed_1_0]
RowIndex=0
walkrate=1.79**
```

**Comment by DarthParametric** [comment]
Interesting, I don't think I ever bothered looking at that 2DA before. I see that Obsidian changed it to that for TSL.

What about when under the effect of Force Speed?

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] There is definitely something weird going on with this. The player walks noticeably slower than the companions. It's causing the opposite problem to the original issue, where now the player walks far too slowly. I suspect this might have something to do with the appearance.2da changes, since I think AFP included some sort of walk-related mod. Increasing the `creaturespeed` value doesn't help, since it applies to all party members, not just the player.
