### ISSUE TITLE
Possible for Jolee to reference Star Map quest prematurely

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#446]
([reported on Reddit](https://www.reddit.com/r/kotor/comments/k61j3y/kotor_1_jolee_conversation_glitch/))

Allegedly, it is possible to progress through Jolee's dialogue tree without finishing Kashyyyk, and he will reference the events surrounding the Star Map quest even though you have not experienced them if you don't complete the planets one at a time in order like a good little player.

It seems like the dialogue branch in question begins at `So when did you go to Kashyyyk?`. Attaching a conditional script that locks the node off until Kashyyyk is completed might fix it.

**Comment by DarthParametric** [comment]
It's the sub-reply R105 that's the branch of interest:
```
R105 You sound quite fond of them. (3947)
|
--- E89 I suppose I am, in a way, despite the smell. For a race of gardeners, they've developed quite interestingly. (3622)
   |
   --- R106 Gardeners? (3948)
      |
      --- E90 You remember the alien computer, correct? Kashyyyk was meant to be an agricultural planet. The Wookiees were made for a reason. (3623)
         |
         --- R107 <>
            |
            --- E91 Or, at least, that's what I'm thinking. But I'm an old man who's had a long time to develop that opinion, so don't argue with me. (3624)
               |
               --- R108 <>
                  |
                  --- E88 At any rate, we should be moving along, don't you think? If you sat around this long in the Shadowlands, a tach would eat you. (Already listed) (3621)
```

**Comment by JCarter426** [comment]
I think it would be enough to change the initial conditional script for that branch to lock it until Kashyyyk is finished. That way there is no need to mess around with the dialogue file, and a few of his conversations imply that you've long left Kashyyyk anyhow.
A few conversationonversation does kind of imply that yo

**Comment by DarthParametric** [comment]
Perhaps, but that would also potentially allow for unintentionally skipping one his branches if a banter trigger pops up and the player doesn't pursue it again manually later.

**Comment by JCarter426** [comment]
Oh, right, I forgot about that problem that came up with Carth before.

**Comment by DarthParametric** [comment]
![Jolee_Kash_Star_Map_DLG](https://user-images.githubusercontent.com/46890653/106156783-afc44e80-61cd-11eb-825b-e589f598cbd2.png)
