### ISSUE TITLE
Helena Disappears After Leaving Tatooine

### ISSUE THREAD

**Issue by StellarExile** [KOTORCommunityPatches/K1_Community_Patch#448]
[Reported by Neural_groove on Reddit](https://www.reddit.com/r/kotor/comments/khle62/problem_with_bastilas_parents_sidequest_on_android/)
I'm not sure if this was a one time thing or basegame problem, but it seems that if you leave Tatooine with the Helena quest still open (haven't given her the holocron) and return she is no longer there.
Edit: Ups, looks like I misread.

**Comment by DarthParametric** [comment]
The cantina OnEnter destroys Helena if `K_KOTOR_MASTER` is greater than 20, i.e. if the Leviathan has been done/Dantooine destroyed. So this is intended behaviour presumably and the player just screwed around too much.
