### ISSUE TITLE
Taris Duel Animation is Low Quality

### ISSUE THREAD

**Issue by thebrokepope** [KOTORCommunityPatches/K1_Community_Patch#449]
When playing the game today both myself and my friend had a chuckle over the PC's waving animation during the Taris Duel. It felt off and of a lower quality than other animation in the game. Now I was coincidentally reading the changelog for this mod only to discover this animation is an addition of the mod! I salute whoever had a crack at this but I think no animation is preferable to questionable animation and suits the "Mysterious Stranger" moniker. For your consideration.

**Comment by DarthParametric** [comment]
It's one of the game's animations, and it's added by an entirely different mod, not K1CP. All K1CP does is give the player the same fistpump animation the opponent has.
