### ISSUE TITLE
Conversation trigger for Sharina outside the Anchorhead Hunting Lodge fails to fire

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#45]
Sharina, who wants the player to buy a Wraid plate harvested by her dead husband, is apparently supposed to accost the player as soon as they approach the entrance of the Hunting Lodge in Anchorhead. There is a trigger outside the doorway of the Hunting Lodge (tat17_sharintrig.utt) but its script (k_ptat_shariask) is not able to be decompiled with DeNCS. Looking at the byte code, it seems similar to other such dialogue trigger scripts (that do decompile), so I'm not sure what the problem is exactly, but a new script that does the job should be straightforward enough to make.

Discovered after ebmar suggested triggering the conversation, only to find out it was already supposed to work like that.

**Comment by Salk73** [comment]
DP,

I think the Sharina trigger geometry still needs some work. I can easily position myself very close to her coming from a "blind" side without triggering the conversation.

![Star Wars_ Knights of the Old Republic 2022-10-16 10_32_23](https://user-images.githubusercontent.com/49585226/196026336-964b2370-f400-4005-adc2-767ed266ce5d.png)

**Comment by DarthParametric** [comment]
True, it's feasible to do so if you really try:

![Sharina_Trigger_Geometry](https://user-images.githubusercontent.com/46890653/196028539-3306db95-0dd0-4217-b14b-a4b5ad62bba4.jpg)

But that's an extreme edge case. I seriously doubt the average slob will manage it unintentionally. But I suppose we can shuffle the lower right vert further to the right.
