### ISSUE TITLE
IOS compatibility

### ISSUE THREAD

**Issue by nemvishy** [KOTORCommunityPatches/K1_Community_Patch#450]
Hey!

The mod doesn't work on IOS for me. Am I doing something wrong or is it not supported? Cant find anything about it.

I copied the kotor directory to my PC and installed the mods then moved it back to the device. Instant crash

**Comment by JCarter426** [comment]
The Community Patch will not work on iOS at this time.

**Comment by nemvishy** [comment]
Bummer. Thanks

**Comment by nemvishy** [comment]
Sorry to bump this up but are there any plans in the future support? If there are I'll just skip the game until then. Unfortunately cant play on PC atm. Happy Holidays!

**Comment by DarthParametric** [comment]
No plans unless someone buys us an iPhone/iPad.
