### ISSUE TITLE
I have saves to share - about a possible voice flaw of Bastila.

### ISSUE THREAD

**Issue by ancient-animal** [KOTORCommunityPatches/K1_Community_Patch#451]
When I start the files called "Game 136" and "Game 138" and talk to Bastila, she says "How can I help?", and it sounds correct. But, when I start the file called "137" and speak to Bastila, her sentence "How can I help?" sounds like it's using a different voice file. Its quality seems worse.

Can anyone else notice?

I am playing the version of this game from GOG.com that shows this as the version number: Internal Update (29 May 2019)

I am using ONLY these mods:
K1 Community Patch (version 1.8.1): https://deadlystream.com/files/file/1258-kotor-1-community-patch/
JC's Security Spikes for K1 (version 1.2) [I chose "Option A", to make the spikes work]: https://deadlystream.com/files/file/1439-jcs-security-spikes-for-k1/

[save files to share - about possible voice flaw.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/5737266/save.files.to.share.-.about.possible.voice.flaw.zip)

**Comment by DarthParametric** [comment]
The line appears to be playing back at a speed above 1.0. Very odd.

**Comment by JCarter426** [comment]
She has a different line when you are on her messenger quest. That part seems intentional, at least. But perhaps there is an issue with the audio.
