### ISSUE TITLE
Kashyyyk - Upper Shadowlands - (Save-File attached) - two bodies are in the file - I must loot each one twice to gain its items.

### ISSUE THREAD

**Issue by ancient-animal** [KOTORCommunityPatches/K1_Community_Patch#455]
If I load this file, and press "R" on my keyboard to interact with the dead body, I can click "Get Items", but the items won't be attached to my inventory UNLESS I interact with the body again and click "Get Items" again. The same result will happen with the other dead body in the same small area. These bodies have two items each: one item seems to be random, and the other is a random amount of money. Since one item is random, this glitch is easier to verify by focusing on the amount of money I have. When I load the file, I will have 2742 credits. If the random amount of money is 50 credits and I press "Get Items", I'll still see 2742 credits in my inventory when I check it. If I interact with the body again and click "Get Items" again, THEN my credits will appear as 2792 in my inventory.

The same result will happen with the random item. When the file starts, I won't have a "Life Support Pack" in my inventory. If the random item is a Life Support Pack, and I press "Get Items", it WON'T appear in my inventory UNTIL I interact with the body again and press "Get Items" again.

I am playing the version of this game from GOG.com that shows this as the version number: Internal Update (29 May 2019)

I am using ONLY these mods:
K1 Community Patch (version 1.8.1): https://deadlystream.com/files/file/1258-kotor-1-community-patch/
JC's Security Spikes for K1 (version 1.2) [I chose "Option A", to make the spikes work]: https://deadlystream.com/files/file/1439-jcs-security-spikes-for-k1/

[save file - I must loot bodies twice to gain items.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/5737415/save.file.-.I.must.loot.bodies.twice.to.gain.items.zip)

**Comment by DarthParametric** [comment]
How long are you waiting? It works first time for either with mouse or keyboard, it just takes a couple of seconds to pop up the loot interface.

**Comment by ancient-animal** [comment]
Just a few seconds. After I click on the bodies and click "Get Items", I must click on the bodies again to open the loot interface again and click "Get Items" to transfer the items to my inventory. They won't be transferred to my inventory the first time. All other loot interfaces throughout the whole game, as far as I'm remembering now, worked correctly with just one open-interface-and-click-Get-Items process.

**Comment by DarthParametric** [comment]
Ah, I misread your original post. I can confirm that looting the first time doesn't appear to work. There's also the delay in popping up the loot interface which I mentioned, which also seems odd. I assume there is something going on with the random loot scripts these two placeables are using.

**Comment by DarthParametric** [comment]
So this appears to be similar to #172. In that case, the treasure script was the OnHeartbeat. In this case, it appears to be the OnOpen. I surmise that this is two instances of `kas24aa_cont_07.utp` in `kas_m24aa`, using the `k_plc_tresshahig` global script.

I'm wondering if for both cases the scripts should be switched to the OnSpawn instead. Thoughts @JCarter426 ?

**Comment by JCarter426** [comment]
Putting it in OnOpen does seem like a mistake, but I don't believe placeables have an OnSpawn event, which is why it's usually in OnHeartbeat.

As I recall, it's still the same in KOTOR 2, but they added a function to stop the OnHeartbeat script from firing again to reduce the computation footprint.

**Comment by DarthParametric** [comment]
Oh yeah, I always forget that. Well I guess we can switch them to the OnHeartbeat. Seems like it is usually fine for everything else. I think that the #172 issue is that they are right next to the entrance, so you can get to them before the heartbeat gets a chance to kick in.
