### ISSUE TITLE
Lip-Movement is not perfectly-aligned with the voices.

### ISSUE THREAD

**Issue by ancient-animal** [KOTORCommunityPatches/K1_Community_Patch#457]
Does this problem exist in the Xbox version of the game? I last played my Xbox version a long, long time ago, so I'm not remembering.

Could this be fixed without a mind-shattering amount of work? I'm curious about the thoughts of the developers of this community patch. I haven't ever seen this problem being mentioned by anyone else. If it's normal and can't be fixed without years of torturous work, feel free to mark this issue as closed.

**Comment by DarthParametric** [comment]
I assume you are talking generally and not a specific instance. In that case, the lip sync is an approximation and a long way from perfect. It's the same on all platforms. There's no practical way to improve it, and that's outside the scope of the Community Patch anyway.
