### ISSUE TITLE
Zaalbar's Stunt Double (Kashyyyk)

### ISSUE THREAD

**Issue by StellarExile** [KOTORCommunityPatches/K1_Community_Patch#460]
It appears that after helping Freyyyr defeat Chuundar and the game switches to the party selection screen, after you choose your party Zaalbar is still briefly visible and vanishes.

**Comment by DarthParametric** [comment]
Presumably this is similar to #122. Should be resolvable in a similar manner, jumping stunt Zaalbar out of site somewhere. 

Do you have a save handy? I don't have any LS playthrough ones to hand.

**Comment by StellarExile** [comment]
I'm afraid I don't, sorry DP :(.

**Comment by ancient-animal** [comment]
I quickly created a Save File that could reproduce this. I attached it to this message.

Steps to reproduce:

1. Start the file.
2. Walk forward, and talk to the character. You will be transported to a different area.
3. Choose all of the friendly dialogue options, then a fight will happen.
4. Finish the fight.
5. After the fight, choose the friendly dialogue options, then add Zaalbar to your party.

After adding him to your party, you will see two Zaalbars. The extra one will disappear after a few seconds.

[Save File - Zaalbar will appear twice when joining party after fight.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/5793184/Save.File.-.Zaalbar.will.appear.twice.when.joining.party.after.fight.zip)

**Comment by DarthParametric** [comment]
Thanks for the save @ancient-animal, that will be sufficient for testing purposes.

As with #119 and #121, there are some serious cinematic issues with the post-combat scene. I spent half of my quick test with the camera inside Zaalbar's head. I think there needs to be some organisation done. Either manually walking people or jumping them under a fade-out.
