### ISSUE TITLE
[GLOBAL] Blinking issue with Female Republic Officer head model

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#463]
I think there is a bug problem with the blinking of the left eye.

First I thought it may be a local issue but it can is still there with an empty Override folder. If this is indeed a vanilla bug I wonder how it is possible that it has gone unnoticed all this time.

I did upload a video showing this on my Google Drive account: https://drive.google.com/file/d/1SeOmafXqmWdSUx5c5WITupY0vS2DROXy/view?usp=sharing

**Comment by DarthParametric** [comment]
The left lid mesh has an incorrectly offset pivot, which is what is causing the spurious animation. The face mesh also has a couple of weights assigned to the OdysseyBase, which are invalid (although they are for static scalp verts, so shouldn't cause any harm), so whoever put it together was obviously pretty sloppy. Although I note that this is one of the few vanilla instances of an altered hierarchy to deal with the hologram transparency issue.

**Comment by Salk73** [comment]
Tested and confirmed working.

Thanks, DP.

**Comment by RedRob41** [comment]
Hi again. I had made a version of this myself. I upscaled it with touch ups edge seams; many UVW fixes to reduce stretching; fix head bone weights; fixed K1 version's problems with left eyelid animations. I'm not sure if I accomplished the eyelid fix the same way you did DP, but you're welcome to compare and use mine if you like.
