### ISSUE TITLE
Xor attacks twice

### ISSUE THREAD

**Issue by HuntersRun1** [KOTORCommunityPatches/K1_Community_Patch#468]
If you DON'T use fast travel and beat Xor, then later fast travel to the Ebon Hawk with Juhani in the party Xor will appear and attack again.

This is because the Boolean K_XOR_AMBUSH_FIX is not set to true in the scripts that are modified that effect Xor.

**Comment by DarthParametric** [comment]
1.10.0 beta test 2 observations:

- [ ] Not sure if this is related , but if Xor spawns without Juhani present and thus doesn't attack, it's possible to travel to another planet and have him spawn there as well. After defeating him, you can fly back to the first planet and he'll still be there as well. The second spawn is not being prevented as intended? Or there needs to be an OnEnter check to destroy an existing Xor if the globals indicate he has already been killed.
