### ISSUE TITLE
Vulkar has the wrong voice

### ISSUE THREAD

**Issue by Mako88** [KOTORCommunityPatches/K1_Community_Patch#470]
Reported via PM on DS by Jeremedy:

I noticed during the first scene where you meet Canderous, when the Davik agent is confronting the 2 Vulkars, the vulkar on the right uses the same voice as a male twi'lek instead of the usual Kadas'sa'Nikto (had to look up what race they are lol) voice. It's a minor thing but i just noticed it especially when the vulkar on the left has the correct voice.

![image](https://user-images.githubusercontent.com/4147635/124819031-58bb6600-df31-11eb-915a-61941e0912bb.png)

**Comment by DarthParametric** [comment]
That's presumably a deliberate developer decision to distinguish the two Nikto from one another in closeup, so I'm not sure it warrants changing. That's more the kind of thing for a 3rd party mod to address with additional Nikto VO from TOR or the like.
