### ISSUE TITLE
Female Republic Soldier head model problems

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#478]
The Female Republic Soldier's head has some minor problems, testing out the NPC by adding one on the Endar Spire showed that when in combat parts of the inside of the head will clip out.

The Female Republic Officer head, on the other hand, is a complete bloody mess. There is a massive hole on the side of the head, the little black bit of her cap distorts horribly when the NPC performs its idle "breathing" animations and the left eyelid pops right out of its head every time it blinks.

A possible solution: It appears Obsidian fixed some of these issues when porting these heads to K2, but some minor issues might remain. I do recall playing Kainz's NPC Overhaul and noticing a Female Republic Officer's head cap will still slightly distort if the NPC does a "talk_pleading" animation.

I tested out porting these K2 heads to K1 using MDLEdit, and it partially worked. The Female Republic Officer's head was mostly fixed from the outside except for her eyelids that couldn't blink. The Female Republic Soldier, whilst looking great from the outside, couldn't move her lips when talking.

I believe if you took the K2 Female Republic Soldier/Officer heads and ported it to K1, you could use those models as a base for a proper fix of these heads.

**Comment by DarthParametric** [comment]
The officer head should have already been (mostly) dealt with via #463.

**Comment by N-DReW2020** [comment]
I tested the fix for #463 and that totally fixed the Officer. As for the Republic Soldier, I did test out the heads in the vanilla game and I now have a screenshot of the female Republic Soldier's head in a broken state.

**Comment by DarthParametric** [comment]
Looks like the female soldier head had some bad weight assignments just like the officer head (weighted to the OdysseyBase). See if this fixes the problem: [K1_Rep_Soldier_Female_Head_Weight_Fix.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/7481619/K1_Rep_Soldier_Female_Head_Weight_Fix.zip)
