### ISSUE TITLE
Vandar (N_Yoda) model UV issues

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#479]
The most noticeable issue with Vandar: When Vandar talks, the inside of his mouth is blue... almost as if the model is using the parts of his own robe for the mouth texture.

The lesser noticeable issue with Vandar: In the module STUNT_51a, when Vandar says the "I sensed something different about Bastila during her transmission" line, Vander will raise his hands allowing us to look up his sleeve as see a distorted mess. The arm appears triangular in shape, parts of the blue robe texture appear on the bottom of his arm and parts of the brown part of the robe is also visible on the arm.

The problem with Dodonna: Due to her unique stunt animations in STUNT_51a, when she says "What? Impossible! She's on our side!" her left shoulder pad will sink into her shoulder. This might occur more than once in other Stunt scenes.

**Comment by RedRob41** [comment]
I had worked on N_Yoda.mdl in my own mod, where I had fixed several uvw map issues, including the inside of the mouth, tip of the nose, chin, right front shoulder/pectoral area, minor tweaks to ears, top of head seam, fingers, inside sleeve at wrist, right armpit, toes, and hem of robe. You are welcome to use the model, as well as the fixed texture (when I've released them).
