### ISSUE TITLE
Player is briefly visible between title crawl/intro movie and opening cutscene on the Endar Spire

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#48]
This appears to mostly happen when letting the intro movie play out by itself. Skipping the movie sometimes seems to prevent it. The Mod_Entry for M01AA is 15.425m, 20.122m, -1.275m, right near the end of the beds. Presumably this is a similar problem to what happens with the party appearing on the bridge of the Leviathan during the Taris escape sequence, except here it is also using the default player camera rather than switching directly to the cutscene camera. In which case, simply moving the entry point presumably won't fix the problem. Could some script shuffling perhaps fire the cutscene quicker to remove the delay? There is a loading progress bar before the intro movie starts playing, so surely the module must be fully loaded by the time the movie is finished playing.

![K1_Intro_Player](https://user-images.githubusercontent.com/46890653/56653102-464a0e80-66d0-11e9-9a1f-df9b4ad785db.jpg)

https://imgur.com/a/9NKmkkA

**Comment by JCarter426** [comment]
Fixed as well as it can be for now.
