### ISSUE TITLE
Female child body and head model clipping issues

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#483]
When performing certain idle animations, the female child NPC's leg will sometimes clip through the skirt. In addition, it also appears as if there's a slight clipping problem with the eyelids (Though this eyelid clipping problem is also common amongst other generic commoner NPC)

**Comment by DarthParametric** [comment]
Here @N-DReW2020, see if this does the trick for the body. Reduced/removed some Pelvis bone influence from the lower half of the skirt.
[K1_Commoner_Kid_Female_Skirt_Weight_Adjustment.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/7481239/K1_Commoner_Kid_Female_Skirt_Weight_Adjustment.zip)

Haven't checked out the head yet.

**Comment by Salk73** [comment]
This should be reopened because the adjusted female child head has more severe problems than the original.
