### ISSUE TITLE
Wrong journal entry when choosing T3-M4 for the Leviathan solo mission 

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#485]
DP,

there is a bug in the .dlg file.

Rather than using the correct Quest Entry number (2), the original file uses 5, which is Juhani's.

This should fix the problem (please, double check, as usual...)

```
[lev40_carth.dlg]
!Destination=modules\ebo_m40aa.mod
ReplyList\35\Quest=lev_captured
AddField0=gff_lev40_carth_QuestEntry_0
[gff_lev40_carth_QuestEntry_0]
FieldType=DWORD
Path=ReplyList\37\
Label=QuestEntry
Value=2
```

**Comment by DarthParametric** [comment]
R37 is the branch suggesting Mission (and has no quest update).

T3's branch ends on R34 and the quest is correctly using QuestEntry 2.

**Comment by Salk73** [comment]
It should have been R35 not R37.

But I have been checking the file inside KotOR Tool and it doesn't seem to match?

I attach here two screenshots showing the reply is R35 and that the QuestEntry is set to 5.

![Scr1](https://user-images.githubusercontent.com/49585226/140507938-0cda6e0a-08f5-4f0e-abe9-2a30b8a53a07.jpg)

![Scr2](https://user-images.githubusercontent.com/49585226/140507964-9853b422-40fb-4653-95fe-fcfc93fa0da3.jpg)

**Comment by DarthParametric** [comment]
Well stop using KTool for starters. It's garbage.  R34 and R36 are the two nodes with T3's state, and both are correct.

![Lev_DLG](https://user-images.githubusercontent.com/46890653/140509194-2e1e71b7-df22-461f-971d-d7113dd88466.jpg)

Confirm with DLGEditor and KGFF or GTFO.

**Comment by Salk73** [comment]
I checked with DLGEditor and KGFF.

Same result.

![Scr3](https://user-images.githubusercontent.com/49585226/140524281-86c715ef-19c6-4d51-a09a-3a8b44db9692.jpg)

![Scr4](https://user-images.githubusercontent.com/49585226/140524734-e0c9f346-3f0c-46a6-91f6-ce1a2abb92d0.jpg)

Are we even looking at the same file?

I have extracted lev40_carth.dlg from the ebo_m40aa.rim module using KTool and I double checked that there was no such file in my override. How is this happening?

**Comment by DarthParametric** [comment]
Apologies. It was late and I wasn't paying attention. I was looking at the lev_m40aa copy of lev40_carth.dlg. Ironically that has the correct journal entries, as posted above, even though apparently unused. Although it looks like it has some fairly significant structural differences based on a quick ChangeEdit comparison. I guess the original plan was to handle it all inside the Leviathan module, which makes sense given the comments regarding showing the troopers storm up the loading ramp. 

But I stand by what I said about KTool. Seriously, stop using that.

**Comment by Salk73** [comment]
KTool is garbage even when it comes to extracting the original game's files?

I use KTool mostly for that and for 2DA editing, when needed. Is it very buggy and that's why you are recommending to stay away from it as much as possible?

Anyway, I hope the TSLpatcher info I provided are correct and that we can call this done.

**Comment by DarthParametric** [comment]
The R37 stuff is redundant. The quest info already exists on that node and is correct. It's just R35 that needs its QuestEntry changed from 5 to 2.
