### ISSUE TITLE
[Global] Inject Animation glitch

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#489]
I don't know whether it's of any importance but I recorded a video where I show how the injection animation can be quite glitchy.

I am not sure how different items using the same animation may cause the glitch in the animation to be more or less prominent.

Videos here: 

https://www.youtube.com/watch?v=PkxPBDyPJ6c&ab_channel=CristianoMessaad

https://www.youtube.com/watch?v=ToUlnTMykbE&ab_channel=CristianoMessaad

**Comment by DarthParametric** [comment]
It's not a problem with the animation, it's a problem with the engine using the animation. Not something we can fix.
