### ISSUE TITLE
Dantooine Murder Mystery: Calder's body is partially floating

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#51]
Calder's new creature-based corpse is partially floating due to the angle of the slope and being larger than the original placeable. The waypoint it spawns on needs to be moved 2-3 feet southwards (GIT edit).

**Comment by JCarter426** [comment]
I actually calculated a location before you started working on it. I didn't move the waypoint, just gave the body a different location manually. When I did Casus' body this seemed to work better, as it left the clickable part centered on his body. Having them in the same place didn't work so well, at least for Casus, on account of how the death animation works. Less work than moving the waypoint anyway, too.
`location lSpawn = Location(Vector(326.6, 423.9, 61.3), 230.0);`
`CreateObject(OBJECT_TYPE_CREATURE, "cp_dan_calder", lSpawn, FALSE);`

**Comment by DarthParametric** [comment]
The corpse selection icon is out in front of his head. Needs to be shifted about a foot North-North-East.

**Comment by JCarter426** [comment]
Hmm, maybe your spawn coordinates were different from the ones I had used. I'll take a look.

**Comment by JCarter426** [comment]
Didn't happen to me for some reason:
![swkotor 2019-09-21 15-38-24-83](https://user-images.githubusercontent.com/46898647/65378441-266e4500-dc86-11e9-97ef-0b35d0d9fcef.png)

**Comment by DarthParametric** [comment]
Yeah I just tested on a pre-first Grove save on Win 10 and it was like that. The issue happened playing on Win XP. I wonder if there is some issue there, as I have noticed it's only on Win XP where I get those music issues I have reported previously. I can't see how a simple set of co-ords would be affected, but since I'm using two copies of the same game install that's the only real variable.

**Comment by DarthParametric** [comment]
I managed to replicate the offset selection icon by clicking through all Bolook's lines on the bridge.  Maybe doing so causes the corpse to speed through its spawn process and causes it to be offset. Maybe we need to add a `NoClicksFor` at the start of that script to be safe.
