### ISSUE TITLE
Do moving bystanders not ever blink? I cannot test the idea properly.

### ISSUE THREAD

**Issue by ancient-animal** [KOTORCommunityPatches/K1_Community_Patch#511]
I was on the area of Taris that has the old man who shouts about "a plague on these streets". He blinks, and the two people standing still next to him blink. While walking around the same map as the old man, I tried to follow some of the bystanders who constantly walk, and I didn't notice them blinking. I'm not sure about this because continuously moving my character to keep the camera moving along with the bystanders is hard.

I'm assuming that the maintainers of this K1 Community patch have adequate modding tools for this scenario, like a free-floating camera that could be positioned in front of a bystander's eyes and be moved with WASD keys.

**Comment by DarthParametric** [comment]
Depends on what you are looking at. Is this in vanilla? If vanilla, then I would say it's probably just the lite commoner models. Those are replaced with full fat commoners in K1CP. If it still happens with the replaced lite models then presumably it's part of a memory saving optimisation that waypoint walkers/ambient NPCs don't use facial animations. In which case it's not something we can change.
