### ISSUE TITLE
Dantooine Murder Mystery: Handon and Rickard wear the same clothes

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#52]
Handon and Rickard use the same clothing variation (g_a_clothes02). One of them needs to be switched, probably Handon since we already edit his UTC for the scripts. Alternatively, Handon could be switched to the fat commoner appearance.

**Comment by JCarter426** [comment]
I actually calculated a location before you started working on it. I didn't move the waypoint, just gave the body a different location manually. When I did Casus' body this seemed to work better, as it left the clickable part centered on his body. Having them in the same place didn't work so well, at least for Casus, on account of how the death animation works. Less work than moving the waypoint anyway, too.
```location lSpawn = Location(Vector(326.6, 423.9, 61.3), 230.0);
CreateObject(OBJECT_TYPE_CREATURE, "cp_dan_calder", lSpawn, FALSE);```
