### ISSUE TITLE
Taris Upper City Cantina - Sana and Gana share the same appearance

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#562]
In the Upper City Cantina, Gana Lavin and Sarna both have the exact same appearances. Matching female generic heads alongside identical white clothing.

I think a simple head swap for Gana Lavin is the appropriate fix here.

In vanilla, Gana Lavin uses the female Asian 01 generic head when encountered outside. K1CP 1.9 changes it so she uses the female white 01 head when outside, my advice would be to change Garna Lavin's head inside and outside the Cantina to the female Asian 01 generic head.

**Comment by JCarter426** [comment]
I believe this change was from my minor fixes. I have no objection to swapping which one gets changed because the change was only done for consistency.

**Comment by DarthParametric** [comment]
I've changed both incarnations of Gana to appearance 14 (Commoner_01_Fem_Asian).

Btw the original change is credited to AFP, so I guess we can blame him for this.
