### ISSUE TITLE
Endar Spire room glitch.

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#563]
When you enter the bridge, if the player/Trask rush inside to fight the Sith then the door explodes and locks. However, if the player stands in the doorway it is possible to prevent the door from closing and locking.

Once the Trask cutscene is over and the door is still open, you can look down the corridor all the way to the grenade cutscene room and the corridor to the right is pitch black.

![20211224145332_1](https://user-images.githubusercontent.com/24619934/147341662-ab5205e6-55a2-4bd2-94be-fbb1c1948428.jpg)

**Comment by DarthParametric** [comment]
This is a sub-issue of #490, since we already need to rejig the conversation after the first two mooks are dead anyway. The party can be jumped under a fade-out before the door is closed.

**Comment by DarthParametric** [comment]
Merged into #490.
