### ISSUE TITLE
Wrong texture-map for male Scoundrel's dark side underwear

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#564]
Apparently nobody in QA department playing as dark side male Scoundrel -- as it seem the underwear [`pmbasd01`] referred in the `appearance.2DA` is using a wrong texture-map. Instead on using the default `pmbas01` as the base for a proper map - it's using Saul's, leading to this --

![K1_DSMaleScoundrelUnderwear_Issue](https://user-images.githubusercontent.com/50026566/147851034-cd22ab5b-88dc-4f8b-9555-790aebe2eab1.jpg)

**Comment by Salk73** [comment]
It seems this is a problem with the male texture. 

The dark female scoundrel looks alright. We'd need to make a new texture for this.

**Comment by N-DReW25** [comment]
The Kotor 2 Underwear model uses the Scoundrel model, wouldn't that be the base of a new texture in the art style of the other K1 dark side underwear?

**Comment by Salk73** [comment]
From what I can see TSL  uses the very same wrong texture.

**Comment by N-DReW25** [comment]
Are you sure? @Salk73 

Considering Consular, Sentinel and Guardian all use the exact same underwear model and texture (Atton and Disciple also have the same underwear as the player btw), I find it hard to believe all of them have broken textures in-game.

Even if the bug is in K2, the correct underwear texture "pmbamd01.tga" still exists in the K2 texture files.

**Comment by Salk73** [comment]
The texture we are talking about is pmbasd01 and it is the same in both K1 and K2.

If I am not mistaken a PC scoundrel wearing underwear only and being Dark Side will use exactly that texture. I don't understand what pmbamd01 (which is also the same in both K1 and TSL except that in TSL it is much darker) has to do with this issue. 

But perhaps I am misunderstanding something?

Let's see what ebmar says if he happens to comment again.

**Comment by N-DReW25** [comment]
@Salk73 I just checked, and you are correct. The K2 male underwear model uses the Scout underwear model and texture map, so what I had proposed would be mostly useless for Ebmar or other modders looking to fix this problem.

It's odd how in TSL the female underwear uses the Scoundrel underwear model whereas the male underwear uses Scout for some reason.

**Comment by DarthParametric** [comment]
Last I heard redrob had basically retired due to family commitments. I sent him a permissions request PM on DS a year which still shows as unread, so I doubt we'll hear from him again. The Xbox version of the texture is correct, albeit only 256x256, so in the meantime we can use that.

**Comment by RedRob41** [comment]
> Last I heard redrob had basically retired due to family commitments. I sent him a permissions request PM on DS a year which still shows as unread, so I doubt we'll hear from him again. The Xbox version of the texture is correct, albeit only 256x256, so in the meantime we can use that.

Not retired, just under the radar. I had no idea that all this work was being done, while I have been quietly picking away at model & texture fixes in my spare time. Feel free to use the texture linked above for now, however I am really close to uploading a 2048x2048 version of that male DS underwear. You are welcome to use that one too.
