### ISSUE TITLE
Global - Soundsets lacking some or any sounds

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#565]
In the soundsets.2da file, there exists several Sith Apprentice soundsets.

* Sith_Apprentice
* Sith_Apprentice_Female
* Sith_Apprentice_Male

The first soundset "Sith_Apprentice" uses "n_sithappren.ssf", however, it is totally empty meaning this soundset plays nothing. I can confirm that Dak Vesser uses this dud soundset in the Valley of the Dark Lords, more NPCs might also be using this soundless soundset for all we know.

The soundset "Droid_Protocol" also has a similar issue like this, the soundset.2da file refers to the "c_drdprotocol.ssf" yet "c_drdprotocol.sff" is also empty... HOWEVER, "n_drdprotocol.ssf" also exists and this ssf file contains the audio... HOWEVER, said audio doesn't exist... no audio exists for the Protocol Droid soundset. I know this dud soundset is used for C8-42 on Dantooine and in other places in K2.

Also, "c_drdturt_dead.wav" exists which is a single audio file for an unused Turret soundset that was never properly finished (Could be useful to somebody).

**Comment by DarthParametric** [comment]
Nothing we can do for the protocol droid since no audio exists in either game.

For `n_sithappren` we could just switch the 2DA entry to point to `n_sithapprenm`, assuming it is even warranted.

**Comment by DarthParametric** [comment]
While we are at it, the assassin droid (`c_drdassassin`) SSF points to incorrect sounds (brith, astromech, bantha) despite proper sounds existing.

**Comment by DarthParametric** [comment]
Not sure there is anything else we can do for this issue.
