### ISSUE TITLE
Taris Upper City North/South - Sith Patrols share one mind

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#566]
When you speak to any of the four Sith soldiers patrolling Upper Taris, you will notice at the end of the brief conversation that they'd all stop and resume their patrol exactly at the same time.

I suspect it depends on the fact that they all share the same conversation file (tar02_sithpat22.dlg).

**Comment by DarthParametric** [comment]
Tested with the Sith troops. Even switching them to four separate UTCs with unique tags (which requires additional waypoints) and unique DLGs seems to make no difference. The DLGs still use the same scripts, but the commands should only apply to `OBJECT_SELF`.

**Comment by DarthParametric** [comment]
This appears to be resolved by switching the DLGs from cinematic conversations to bark bubbles. However only the Upper City South Sith troops need this edit. The Upper City North Sith already use a bark bubble DLG and don't display the described behaviour.

The protocol droids have a full conversation tree with player responses, so they are not going to be fixable it would seem.

**Comment by Salk73** [comment]
Well, it's going to be an improvement.
