### ISSUE TITLE
Canderous inconsistencies in the Undercity

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#568]
I've noticed a few inconsistencies between the Canderous UTC in the Undercity and the Canderous Party Member. Some of these inconsistencies are more important to fix than others, but here is a list of all of the issues I've noticed:

* Canderous the party member has a +4 regeneration hide, this is due to the implants he has in lore. His Undercity UTC lacks this hide and if he is attacked by a Rakghoul he won't regen any of his health like he normally would.
* Canderous' Undercity NPC has normal Power Blast, Master Rapid Shot and no melee attacks whereas his Party Member UTC has Improved Power Blaster, Rapid Shot and Power Attack.
* Canderous' Party Member UTC comes with a Vibrosword in its inventory which slides into the player's inventory upon recruitment. Canderous' Undercity UTC wields a Vibroblade instead.

Not exactly related to Canderous himself, but still related to the Undercity.
* Canderous has 3 Mercs follow him in the Undercity with 2 capable of being killed by Rakghouls, leaving 1 alive. Canderous will still refer to this 1 surviving Merc as "Boys" which suggests more than 1 survived.

**Comment by Salk73** [comment]
Is it of any importance that some of Canderus' stats in the Undercity are different from the Canderus that joins the party? As long as they don't affect the outcome of the cutscene there I think everything is fine.

The last point is instead well taken. I have fixed it locally in my own modification.

**Comment by DarthParametric** [comment]
This is already addressed in #235.
