### ISSUE TITLE
Leviathan Prison Block - Canderous as chosen jail breaker gets switched for stunt version

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#569]
Okay, this is rather interesting.

If the Player chooses Canderous for rescuing the rest of the crew, the items that Canderous was wearing can be retrieved in a container (_lev40_patgear.utp_). The Player can then take those items and put them back on Canderus before proceeding to free Revan, Bastila and Carth.

From what I understand, once the cells are open, the NPC chosen for the rescue is replaced with Revan via SwitchPlayerCharacter() called from a script that cannot be decompiled (_k_plev_freeparty_) and Canderous is spawned in the nearby cell, moves out of it and will speak a line later in the cutscene ("Don't you worry about that. I know how to deal with the guards. They won't know what hit them!") and here comes the problem: Canderous is now equipped with just his normal clothes as opposed to anything that the Player had put on him (usually the items he was wearing before meeting the Leviathan and found in that container mentioned above). This is quite jarring and even if it is a minor problem of aesthetics it does bother me and I tried to fix it.

The problem is that apparently the script in charge of this is _k_plev_transfrm1_ which DeNCS  decompiles but with the usual warning of "partial-byte code not matching". Unfortunately from my testing I discovered that in this case the decompiled script has a critical mismatch (I suspect DeNCS has problem with the Switch/case functions) which didn't give me a reliable result.

Perhaps a possible solution would be to move the items Canderous was wearing to Bastila (or Carth) and then have the respawned Canderous equip them before leaving the cell (_k_plev_candmove_)?

On this note, I guess that the respawned Canderous is not wearing the equipped items because that would only happen when a party member is removed from the party as opposed to destroyed/switched? But if that is the case, wouldn't the items Canderous was wearing be gone for good? I'd need to test the whole Leviathan module to verify this.

**Comment by DarthParametric** [comment]
I addressed this in my [All Hands on Deck](https://deadlystream.com/files/file/2097-all-hands-on-deck-for-the-leviathan-prison-break/) mod. The vanilla script uses `CreateObject` with the global Canderous UTC. I switched this to `UT_SpawnAvailableNPC`, which will preserve the party table version with whatever equipment they had at the time of activating the computer console.
