### ISSUE TITLE
Stunt Modules's have no loading screens.

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#570]
The stunt modules of Kotor 1 appear in the following areas:

* The Taris Apartment
* The Ebon Hawk
* The Leviathan
* Lehon Temple Roof
* Lehon Temple Interior
* Lehon Temple Exterior
* The Star Forge
* A Hammerhead Class Cruiser

None of these areas has any unique loading screens and all use the same generic loading screen. My suggestion would be to give the stunt modules their own loading screens based on the original loading screens.

The Ebon Hawk stunt modules will use the Ebon Hawk loading screen, the Leviathan bridge stunt modules will use the Leviathan bridge loading screen, the Bastila torture scene will use the Lehon Interior loading screen etc.

I've actually made 99% of these loading screens so if this is approved I can just donate them to the patch, however, Revan's dream stunt cutscene might be a problem as the bed is visibly the Ebon Hawk whilst the post-Endar Spire dream cutscene reuses the exact same Ebon Hawk dream stunt module... so that might be a problem.

**Comment by DarthParametric** [comment]
This is added content and outside the purview of K1CP. I'd suggest you release it as a standalone mod (probably with a compatibility patch for SithSpecter's "Loadscreens in Colour" mod).
