### ISSUE TITLE
Rakghoul Serum Icon

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#572]
On the XBOX version of Kotor, the Rakghoul Serum you find in the Undercity is a Plot Useable Item with the icon texture ip_pltuseitm_037. On the PC version, the Rakghoul Serum you find in the Undercity is an Adrenaline Item with the icon texture ii_adrnaline_001.

The item description of the Rakghoul Serum (Regardless if it is the one you find in the Undercity or bought from Zelka) says the following:

"A vial of greenish, bubbling liquid"

First of all, the description needs a full stop "." at the end, and more importantly, the icon texture ip_pltuseitm_037 looks to be some sort of syringe with green liquid inside. For this reason, I find that the XBOX rendition of the Rakghoul Serum matches the description of the Rakghoul Serum better than the PC version.

**Comment by Salk73** [comment]
Good find!

Interestingly enough, it seems there is a global  version of the Rakghoul Serum which is also found in several other Taris modules and one version in the Undercity module which is slightly different.

I think a global replacement is in order.

**Comment by DarthParametric** [comment]
> the icon texture ip_pltuseitm_037 looks to be some sort of syringe with green liquid inside

I assume one of us must be colour blind, because both the Xbox and PC textures show a _blue_ liquid on my end.

**Comment by Salk73** [comment]
I can confirm the texture shows a light blue liquid.

**Comment by N-DReW25** [comment]
Checked the file, and I would agree with Salk's observation: it's a blueish green in colour.

I'm sure this wouldn't be too noticeable in-game.

**Comment by DarthParametric** [comment]
Perhaps ip_pltuseitm_058 or ip_pltuseitm_026 would fit the description better.

**Comment by Salk73** [comment]
Do you know if ip_pltuseitm_058 is used for anything else in the game, DP?

**Comment by N-DReW25** [comment]
I can confirm that ip_pltuseitm_026 is the same icon used for the Toxins which are fed into the vents to poison the giant shark on Manaan.

Not so sure about 056.

**Comment by Salk73** [comment]
Thanks, N-DReW25!

**Comment by DarthParametric** [comment]
Thanks to JC providing an XML dump of all templates, I can see 183 instances of Plot Useable Items, none of which use model variant 58. There's one instance of variant 26, `man28_toxic.uti` as N-DReW25 alluded to.

There are three instances of variant 37. `g_i_gizkapois001.uti`, `ptar_rakghoul001.uti`, and `ptar_rakghoul002.uti` (both from tar_m02ac). These are sold by Zelka - cheap and expensive versions depending on who you gave the original serum to.
