### ISSUE TITLE
Manaan West Central - Selkath Kolto Overseer Clones

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#575]
In the module "manm26ac" you can find a small room with a Selkath Coordinator and a Selkath Overseer. The Coordinator is the Selkath who utters the famous line "One does not simply 'get' a purchase permit!" whereas the Selkath Overseer simply states "Why are you disturbing me? Can you not see I am overseeing the packaging of this kolto?"

The Selkath Overseer is simply labelled "Selkath" and its DLG is called "man26_selkol.dlg" suggesting this Selkath does the same Kolto packing duty as the Republic/Sith Soldiers. Should this Selkath be renamed to something a bit more specific? The generic Selkath are also called "Selkath" whereas this one has a specific job and proper dialogue.

But more importantly, just outside the small room, you can find two Selkath facing each other as if they were talking, but once you talk with them they give the exact same "overseeing the packaging of this kolto?" dialogue.

I suspect that the two cloned Selkath Overseers are intended to be generic NPCs because their opening lines say "Can you not see I am overseeing the packaging of THIS kolto?" which wouldn't make sense because they're both outside with no Kolto boxes insight.

I believe this can be fixed by modifying the module's .GIT file and replace the two cloned "man26_selkol.utc" with "man26_sel2.utc" and "man26_sel1.utc" as these two generic NPCs are the ones who'll say "This is a private conversation, off-worlder." which would make sense as they'd be directly facing each other as if they were talking.

**Comment by Salk73** [comment]
I have already opened an issue about the Kolto packers quite some time ago (#304) and I did change a few things to make things work well.

**Comment by DarthParametric** [comment]
> you can find two Selkath facing each other as if they were talking

This is a consequence of ambient animations. You will see this on every planet if you hang around long enough watching background NPCs.
