### ISSUE TITLE
Room model inter-mesh seams

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#576]
I don't know if there is anything that can be done (I fear not) but I report this anyway, in case there might be some solution.

The textures of the sand at the central beach on Lehon produce visible seams.

See here: https://pasteboard.co/iSGIGUZdDlML.jpg

**Comment by Salk73** [comment]
Sorry about the dead link.

I uploaded it here again.

Maybe there is nothing that can be done about it but I thought you might like to take a look at the screenshot anyway.

![Star Wars_ Knights of the Old Republic 2022-03-11 07_31_34](https://user-images.githubusercontent.com/49585226/167083497-c57a8c91-021d-45a1-aa44-bff75d4001cf.jpg)

**Comment by DarthParametric** [comment]
Yeah those are model seams. You can see it more clearly where they extend under the Hawk. It's possible to ameliorate, but it's a pain. You need to black box every room, but even they you may still get some leakage.

**Comment by DarthParametric** [comment]
Going to put this in the too-hard basket, given the extent of it. It really requires a fix at the engine level.
