### ISSUE TITLE
[Turret Minigame] Mouse speed set to too low value

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#579]
I have opened a topic at Deadlystream about this wondering if it is a local problem for me or if it's happening to everyone but I didn't get a single reply there so I decided to open an issue, just in case.

The turret minigame is pretty much a disaster.

The main offender for me is the mouse speed that seems to override the global setting. I have a perfectly comfortable camera movement speed using the mouse but once the minigame starts, the mouse speed for turning the turret plummets to a ludicrous value. I have no idea whether we can do something about it but I'm hoping that it's somehow possible.

On top of that, there is the problem of the game starting before the fades in is completed. This means that the Player takes unfair damage from enemies shooting while the screen is still completely dark.

But not only that. There is a problem with the enemy spacecrafts can fly under the reach for of the turret. This may be intended of course but it's a cheap trick, in my opinion.

**Comment by DarthParametric** [comment]
This is a local issue on your end. It has nothing to do with K1CP (or the base game).

**Comment by Salk73** [comment]
Thanks for confirming this is a local issue on my hand.

Somebody wrote to my in private saying he was having the same issue though. And I tested that this problem was present in the base game as well before posting.
