### ISSUE TITLE
Endar Spire Sith Soldier has 2 HP instead of 15 HP

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#580]
When you fight the first two Sith Soldiers on the Endar Spire, one of the Sith Soldiers has 2 HP whereas every other Sith Soldier NPC has 15 HP.

The file in question is "end_repsol002.utc".

**Comment by DarthParametric** [comment]
The only reference I can see to this UTC is via the encounter bridgesith.ute. Since the GIT doesn't list any encounters, I am going to say this UTC is never even spawned in the first place and thus this is a null issue. You can re-open it if you can find evidence to the contrary.
