### ISSUE TITLE
Manaan Hrakert Station - Calo Nord thug clones

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#581]
In the vanilla game, Calo Nord's two thug buddies on Manaan are both identical green Twi'leks who wear Cinnagar Weave Armor with Rodian soundsets.

K1CP currently fixes the soundset but the appearance has been left unchanged. This is a problem because the cowardly Mercenary NPC at the start of the Hrakert Station has the exact same green Twi'lek with Cinnagar Weave Armor appearance, thus creating a weird clone effect.

There are two possible fixes for this:

1) Change the armors: Both thugs have a Combat Suit and a Heavy Combat Suit in their inventory which they do not drop. Since these items are leftovers from Bioware, it isn't too much of a stretch to just swap out the Cinnagar Weave Armor with the Combat and Heavy Combat Suits.

2) Make them Rodians: Their soundsets were originally the Rodian soundset, so by changing their appearances to a Rodian appearance with the Rodian soundset then it would technically make them unique.

I would recommend using the Rodian 02 appearance as the Twi'leks had the Twi'lek 02 appearance.

**Comment by DarthParametric** [comment]
We can probably split it 50/50. Make one a Rodian, switch the other to a different armour and different Twi'lek racetex.
