### ISSUE TITLE
Global - Rodian texture bug

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#582]
The Rodian NPC has 5 texture variants:

Rodian 1= Biege Jumpsuit
Rodian 2= Yellow Jumpsuit
Rodian 3= Green Jumpsuits
Rodian 4= Red Jumpsuit
Rodian 5= Suvam Tan

The way the Rodians are supposed to work is that N_Rodian.mdl's texture should be set to Rodian 01 whilst the appearance.2da sets the other Rodian appearances for Rodian 02, 3, 4 and 5. 

However, the N_Rodian.mdl file is set to the N_Rodian02 texture. This results in every Rodian 01 NPC appearing in a yellow jumpsuit like Rodian 02 instead of their intended appearance.

This was fixed in K1R and I believe it was fixed via the 2DA file for that mod.

**Comment by DarthParametric** [comment]
Presumably they added a racetex entry for the first appearance, which is nulled out by default for all alien appearance first entries.
