### ISSUE TITLE
Mission's missing Blaster Pistol

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#583]
When you encounter Mission Vao in the Undercity, she is unarmed but the moment she is recruited she has a Blaster Pistol.

I think the most suitable fix for this would be to give Mission's Undercity encounter UTC file a Blaster Pistol. 

Also, some issues to consider: It is possible to reject Mission Vao and leave her where she is, to progress the game the player HAS to agree to save Big Z so the player has to eventually return to her and recruit her.

The problem is that the player just leaves her, unarmed, in the middle of the Undercity. It would technically be possible to approach Rakghouls, have them chase you and lead them to Mission and neither Mission nor the Rakghouls would react to each other.

Wouldn't it be better to have Mission run towards the Outcast Village and remain dormant in there until the player eventually recruits her?

**Comment by DarthParametric** [comment]
The former is pretty irrelevant. She also comes with a unique sword, but she doesn't run towards you waving that around either.

As to the second, that's outside the scope of K1CP, especially for such an edge case.
