### ISSUE TITLE
Kashyyyk Woorwill's Home - Companion interjections spoken off-screen during Jaraak conversation

### ISSUE THREAD

**Issue by darthbdaman** [KOTORCommunityPatches/K1_Community_Patch#588]
- [x] During a conversation with the Wookie Jaraak, Mission has an interjection. During this line the camera stays focused on Jaraak, even though mission is speaking
- [x] Ditto for Woorwill's DLG - DP

**Comment by DarthParametric** [comment]
I gather this is inside Worrwill's Home? If so that would be `kas23_jaarak_01.dlg` in `kas_m23ab`.

**Comment by darthbdaman** [comment]
Yes that's the file. Mission is set as the speaker, and i don't see anything obviously wrong
