### ISSUE TITLE
Black Vulkar Base - No alarm after overloading the swoop bikes

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#599]
After slicing into the terminal in the Garage Head's office and overloading the swoop bikes in the garage, the terminal reads "ENGINE SET TO OVERLOAD. SOUNDING ALARM," yet no alarm is triggered.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
This is something I have tried to rectify previously, with no success, at least with playing an external SFX. I think it may need to be a VO line in order to get it to work correctly.

**Comment by DarthParametric** [comment]
Possible candidate for inclusion in N-DReW25's [Unofficial Tweak Pack](https://deadlystream.com/files/file/2081-unofficial-k1cp-tweak-pack/).
