### ISSUE TITLE
Taris Lower City Cantina - Rodians disband

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#601]
Most of the times I played through this part, after Mission's cutscene at the cantina, the rodians leave on different paths (one to the left and one to the right), even though they presumably came in together.

**Comment by DarthParametric** [comment]
They both get directed to the same exit waypoint with a one second delay between them. If they move in different directions then that is a pathfinding issue. There's not really much that can be done about that.
