### ISSUE TITLE
Swoop Platform - Disarming the player character?

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#602]
It wouldn't hurt to disarm the player character when entering the swoop platform for realism purposes. They were disarmed already for the duration of the conversation with Gadon and the scene leading to the platform.

**Comment by DarthParametric** [comment]
The PC is already disarmed for the cutscenes. There's no point trying to disarm them outside the cutscenes when player can just manually re-equip themselves, and they need to be armed for the confrontation with Brejik.
