### ISSUE TITLE
Davik's Estate - One line is obviously "[Lie]"

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#604]
Considering the party's plan to take advantage of Davik to steal his ship, the line "I'm looking forward to working with you, Davik" should be preceeded by "[Lie]". Not sure if there's plans for integrating a WIP that deals with dialogue fixes specifically. Maybe I should report this on that thread. Progress on that one has been slow as far as I know though.

**Comment by DarthParametric** [comment]
Aesthetic dialog.tlk changes are outside the scope of the mod.
