### ISSUE TITLE
Dantooine Courtyard - Stuck horn kath hound

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#606]
It is possible for one of the wandering horn kath hounds (the one running across the field) to get stuck behind the pack closest to the ruins the first time the PC explores the area, caught up in a looping path.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
This is an artefact of Odyssey's ropey pathfinding. Not really much we can do about it since it's not a repeatable issue.
