### ISSUE TITLE
Dantooine Courtyard - Wandering Jedi bumps into everyone

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#607]
It is easy for the wandering Jedi to spin around when bumping into the party, sometimes even teleporting himself. If he's there for immersion's sake, he's definitely not helping. The hardest section for him to maneuver around is the first half of the courtyard, since that's where the main NPCs are.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
It's not practical to fix aside from just outright removing his patrol behaviour. The area is simply too narrow and too crowded for Odyssey's pathfinding to deal with.

**Comment by DarthParametric** [comment]
Partially addressed in #548 by jumping the Jedi out of the way for the duration of the conversation with Jon. The same approach could be used for other conversations if needed.
