### ISSUE TITLE
Dantooine Courtyard - Ruins cutscene triggers prematurely

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#608]
The cutscene that triggers when the PC approaches the ruins is rather pointless if they aren't assigned the quest to investigate the ruins yet. Because of this, if the PC has already approached the ruins, the cutscene doesn't fire when it would fit the most, which is when the PC is accompanied by Bastila.

**Comment by DarthParametric** [comment]
Easy enough to resolve with an edit of the trigger's OnEnter script (k_pdan_tomb02). The vanilla script is

```
#include "k_inc_dan"

void main() {
    
    if (IsObjectPartyMember(GetEnteringObject()) && HasNeverTriggered())
        {
            AssignCommand(GetObjectByTag("dan14_cut02", 0), ActionStartConversation(GetFirstPC(), "", FALSE, CONVERSATION_TYPE_CINEMATIC, TRUE));
        }
}

```
The check could be changed to 

```
if (GetIsPC(GetEnteringObject()) && IsNPCPartyMember(NPC_BASTILA) && HasNeverTriggered())
```
