### ISSUE TITLE
Dantooine Sandral Grounds - Duros warrior does not attack

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#609]
One of the Duros warriors did not attack the PC until attacked first. I did flee the fight momentarily, which I noticed causes strange issues from time to time regarding enemy behavior.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
This is an issue with enemy AI that can occur anywhere. It's not something we can address.
