### ISSUE TITLE
Ebon Hawk - Galaxy map cutscene not firing?

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#610]
Not sure what happened here. There's supposed to be a cutscene the first time you enter the Ebon Hawk's cabin, but it failed to fire for me this time. I checked a playthrough on YouTube and this is what it's supposed to say:

[This is the Galaxy Map [...].]
[When you are ready to leave Dantooine [...].]
[A destination is still stored [...].]

I don't know how this could be an issue on my end, but I don't think K1CP could've screwed with this either. I'll add the issue just in case. Maybe someone else could double check with the latest version installed. The first time I entered the cabin was before the PC was actually allowed to leave Dantooine yet.

**Comment by LaIngobernable** [comment]
Apologies. I've been trying to open the script for an hour using different tools, but I can't remember how to get it working and I can't find my notes on how it's done. It's not in the Override folder though.

**Comment by DarthParametric** [comment]
This sounds like a problem on your end, not with K1CP.

**Comment by LaIngobernable** [comment]
Yeah, after playing some more it became clear my hardware has a hard time firing specific things. Happened with Sharina Fizark's trigger next to the hunting lodge as well. I'd say you can chalk this up along with #590 and maybe #609 as issues on my end, simply because of how random they sound. Next batch should be more pertinent, as I know what to look out for on my end now.

**Comment by DarthParametric** [comment]
TSLPatcher bug. One of Sasha's scripts has a `-` in it, and presumably got nuked in the module repack.
