### ISSUE TITLE
Dantooine Jedi Enclave - Vrook's dialogue doesn't reflect Sandral-Matale quest completion

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#611]
You can keep asking Vrook about the Sandral-Matale feud even when the quest has already been completed.

**Comment by DarthParametric** [comment]
Similar problem to #506. I thought we had addressed this one though.

**Comment by LaIngobernable** [comment]
All right, I just came back to Dantooine to tell Vrook about Belaya and he did have the line removed by that time, so what happens there is that you can ask him about the family feud even after it's been solved, and you can ask him endlessly about it, unlike the raiders branch, but when you come back to tell him something new the line isn't there anymore. I can't remember if it was there after exiting and re-entering his dialogue tree last time though. I can redo that part and check if it'll help.

**Comment by DarthParametric** [comment]
Seems this _should_ have been address via the starting conditional [cp_dan13_van_mat](https://github.com/KOTORCommunityPatches/K1_Community_Patch/blob/master/Source/cp_dan13_van_mat.nss) that was added as part of #480. It was added to both Vandar's and Vrook's DLGs. It checks global `DAN_VANDARS_DONE` which should be set once you report back to Vandar about the Feud outcome.

This issue will be closed and marked as a duplicate. Further discussion should be redirected to #480 if warranted.
