### ISSUE TITLE
Korriban - Unfitting dialogue from companions

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#612]
Mission's and Canderous' lines about Korriban only make sense if asked outside the Hawk and past Dreshdae (that is, anywhere on the planet's surface or at the Sith academy). The lines are:

"Korriban is a Sith world, that's for sure. I mean, just look at this place."
"I don't know anything about Korriban, but I get a bad feeling in this place. If there's such a thing as an 'evil' planet, this is it!"

**Comment by DarthParametric** [comment]
Eh, it's fine.
