### ISSUE TITLE
Korriban Dreshdae - PC awkwardly stares at Canderous

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#613]
The PC stares awkwardly at Canderous after his second intervention if he's present during the Lashowe encounter at Dreshdae. Presumably this happens if he doesn't interact with other party members. The PC should just keep looking at Lashowe so that they maintain eye contact for the duration of her following line. There's probably more instances like this in which the PC is forced to look at the party member making the intervention when it doesn't fit.

**Comment by DarthParametric** [comment]
Sub-issue of #160.
