### ISSUE TITLE
Korriban Dreshdae - Human Sith apprentice addresses you as "human"

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#616]
If not wearing robes or a lightsaber, the Sith apprentice tormenting the Rodian and Twi'lek on your way to the Hawk addresses you as "human" even though he is a human himself. He might be better suited as a Twi'lek (blue or orange to prevent clones). He uses the same Asian head as the Czerka shopkeeper anyway.

**Comment by LaIngobernable** [comment]
There might be no way to properly address this, but he also calls you "Jedi" for wearing Dark Jedi robes from the Sith academy.

**Comment by DarthParametric** [comment]
Seems like a non-issue to me.
