### ISSUE TITLE
Bad deformation of Mission's clothing body model when using Security

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#617]
There's an issue with Mission's BB UV mapping whenever she hunches to use Security on crates and footlockers. It's like her belt stretches instead of showing the back of her top.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
You seem to have a fundamental misunderstanding of what UVs are and/or how they work. What you are describing is an animation deformation issue.

**Comment by LaIngobernable** [comment]
Probably. I haven't revised any of my notes on modding and most are most likely incomplete or simply lack appropriate insight. Feel free to rename anything that doesn't quite make sense.
