### ISSUE TITLE
Canderous' BB and BA models could use some tweaking

### ISSUE THREAD

**Issue by muitafruita** [KOTORCommunityPatches/K1_Community_Patch#619]
In Canderous' BB model, the right side of his vest looks a bit deformed when viewed from the side, showing more shirt than it should. The left side of his vest is perpetually clipping with his arm when viewed from the front. There's a bit of clipping on the right side, but it's not as noticeable. In addition, his BA doesn't make sense anatomically: his collarbones are way below where they should be, and it looks like all it needs is some UV tweaking.

[redrob41's fixes](https://deadlystream.com/files/file/1273-party-model-fixes-and-hd-bastila/?ct=1655578968) don't seem to address this, nor Mission's #617.

**Comment by DarthParametric** [comment]
Can be considered a sub-isssue of #229.
