### ISSUE TITLE
Manaan Docking Bay - Sith fighters have floating cannons

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#621]
The Sith fighters docked at the bay where the shuttle to the Sith base is at have floating cannons.

**Comment by DarthParametric** [comment]
Given their appearance as a whole (including poor lightmapping), it might be easier to just replace them altogether with the regular fighter model, although they would need new lightmaps.

**Comment by DarthParametric** [comment]
Replaced the original fighter meshes with higher quality ones pulled from the Star Forge, along with higher resolution diffuse textures. Baked new custom lightmaps.

![Manaan_Sith_Fighter_Replacement](https://user-images.githubusercontent.com/46890653/176991628-6b7bab20-cad6-418f-9938-6f1e347c271b.jpg)

I notice that the rear support pillars/arms for the back pair could also do with rebaked lightmaps.
