### ISSUE TITLE
Global - NPC head Old_B_M2 has unsuitable UVs for the eyelids

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#622]
Ambassador Roland Wann has gray eyelids, and it's probably not makeup.

**Comment by DarthParametric** [comment]
This is a case of Old_B_M2 being a retexture of Old_B_M. They didn't assign a unique island to the eyelid UVs, they just overlaid them on the neck. The beard of Old_B_M2's texture covers this area, causing them to appear grey.

**Comment by DarthParametric** [comment]
@LaIngobernable: Try this. It should resolve it - [K1_Head_Old_B_M2_UV_Fix.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/8938119/K1_Head_Old_B_M2_UV_Fix.zip)
