### ISSUE TITLE
Korriban Sith Academy - Shaardan's corpse is never cleaned up

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#623]
After he's tricked by the PC and murdered by Uthar, Shaardan's corpse remains there by him, even though the PC has traveled to a different planet and come back. I'm counting on the assumption that the Sith believe in body disposal.

**Comment by DarthParametric** [comment]
It's removed before leaving for the Tomb of Naga Sadow as part of #162.
