### ISSUE TITLE
Kashyyyk Upper Shadowlands - Katarn loot makes little sense

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#627]
This one time, Rulan the shapeshifter left "Remains" after being killed (a repair kit), but after he was looted, a new label with his full name was also lootable, this time with 500 credits. I am also fairly certain these other "Remains" were not from a different tach that was also killed just before (and it wouldn't make sense either way, considering the kind of loot).

Edit: In hindsight, this probably was a katarn that was killed previously but never looted, in which case the loot they give makes little sense. Very minor issue, so feel free to dismiss it.

**Comment by DarthParametric** [comment]
I have noticed creatures with no starting inventory and generic scripts dropping random minor loot on death (stuff like medpacs, credits, grenades). I gather that's what you are seeing.
