### ISSUE TITLE
Ebon Hawk - Gizka causing party member displacement

### ISSUE THREAD

**Issue by muitafruita** [KOTORCommunityPatches/K1_Community_Patch#631]
Jolee stands with his foot "stuck" between two pieces of the Hawk's floor geometry, while his other foot's heel is clipping with one of the pieces. This doesn't happen in vanilla as far as I know. In case it matters, he just joined the crew and there's gizka around the ship.

**Comment by DarthParametric** [comment]
In the medbay? The only walkmesh we edit is the central room's, so there shouldn't be anything going on that is the fault of K1CP.

**Comment by LaIngobernable** [comment]
Yup. He's basically really close to the wall. I don't know of any other mod that touches the walkmeshes, and this isn't a heavily modded run at all. But then again, that's what I thought last time and it turned out the problem was that one installer was outdated.

**Comment by DarthParametric** [comment]
> My guess is the one gizka that's also in the medbay displaced him when he spawned

Seems plausible. All the party members get destroyed and respawned every time the Hawk module is loaded. It might be possible to do the same for the Gizka as a safety precaution, but it's kind of an edge case.

**Comment by LaIngobernable** [comment]
It happens with some degree of frequency, I've come to realize. But I refuse to let these gizka go.

**Comment by DarthParametric** [comment]
I think a possible solution to this is adding a check to the existing OnHeartbeat event in the gizka OUD. It can check if it is close to one of the party member spawn-in waypoints and, if so, do an `ActionMoveAwayFromObject`.
