### ISSUE TITLE
Leviathan Prison Block - Overloading the barracks?

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#634]
Everything seems to point to the fact that you were supposed to have the option to overload the conduit in the barracks to get rid of the troops to get to the footlocker where the passcard is. The conduit model is there and the usual camera view in the terminal is there.

**Comment by DarthParametric** [comment]
It's presumably cut content from an originally larger/more difficult version of the level. There were also supposed to be troops in the room in front of the storeroom (where the party gear ends up} that you could gas. They might have removed the overload option so as to not completely trivialise things after they revised the level, although those troops remain completely optional anyway.

Any way, balance changes and cut content restoration aren't in our wheelhouse.
