### ISSUE TITLE
Quest items that may not need to be

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#638]
Not a big deal, but a few items are marked as quest items, which prevents them from being sold:

- Rough-cut Upari Amulet
- Ajunta Pall's Blade
- Sith Lightsaber from the final test on Korriban

I'm guessing the last two need to be quest items for scripts to trigger properly. The first one shouldn't though: it's a power crystal given to you in the Lower Shadowlands for taking the Mando raiders out.

**Comment by DarthParametric** [comment]
The amulet should be fine to just remove the flag from the UTI. For Ajunta Pall's blade, that can have its flag removed via the Academy OnEnter once returning from the Tomb of Naga Sadow and the saber could probably get the same. I'd have to check the Naga Sadow conclusion scripts, as I'm not even sure if there's a check for the saber in the first place (although Uthar does say something along the lines of "You return with lightsaber in hand" as I recall).
