### ISSUE TITLE
Manaan East Central - Contradiction in Hulas' dialogue options

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#639]
If you had murdered Zuulan on Dantooine and return to Hulas after the Leviathan, you have both the option to tell him he's been dealt with and the option to tell him you can't complete the assignment because Dantooine has been destroyed.

**Comment by Salk73** [comment]
I guess it's just a simple correction to k_pman_hulas16.

int StartingConditional() {
	return (GetGlobalNumber("K_Geno_Zuulan") == 1 && GetGlobalNumber("DAN_PLANET_PLOT") == 3);
}

**Comment by DarthParametric** [comment]
Looks like the original script author mixed up state 3 of `K_Geno_Zuulan` (let him go) with state 2 (killed him).
