### ISSUE TITLE
Manaan East Central/Hrakert Station - "A few scientists have survived" but you've killed everyone

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#640]
Unless I missed something, the two scientists that panic at your sight before you get to the rift are the only survivors, and if you decided to murder them, you still have the option to tell the ambassador that a few scientists survived when you report back to him. I guess the guy in the locker could count as part of the research team, but even if he is, one isn't "a few," so he actually doesn't matter for that dialogue option.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
Looking at the DLG, it seems that you could put a starting conditional on that reply to skip it and Roland's response, although there would need to be a global or quest state to check for murdering the two scientists and it doesn't look like either exists.

**Comment by DarthParametric** [comment]
Given the intrusive requirement of adding new globals for something fairly inconsequential, this can be left to a standalone mod.
