### ISSUE TITLE
Unknown World South Beach - Missing lightning defenses between pilars

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#642]
A couple of the lightning sections closest to the wall at the enclave entrance appear to be missing or are inconsistent between saves.

_Submitted by muitafruita_

![Missing_Lightning](https://user-images.githubusercontent.com/46890653/208284172-f0c28f81-303a-4c13-85f3-8a8dacc7cb63.png)

**Comment by DarthParametric** [comment]
So the lightning VFX between the pillars is initiated by a trigger (effecttrig.utt) at the entrance of the area that has the OnEnter [k_punk_effect](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M41AB_Lehon_South_Beach_unk_m41ab/k_punk_effect.nss). Based on some experimentation, it seems that some of the VFX can randomly disappear on loading a save. For example:

![Lehon_Pillar_Lightning](https://user-images.githubusercontent.com/46890653/213103989-4d926eaa-3937-4edf-b228-4af14198a98d.jpg)

I'm not sure how practical that is to resolve. I suppose we could destroy the existing ones and reapply them in the OnEnter, but that would probably be visible to the player when loading a save in front of the compound. I'm not sure if there is an alternative way to "refresh" them.
