### ISSUE TITLE
Korriban Tomb of Tulak Hord - Corpse drops Mandalorian armor but isn't a Mandalorian corpse

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#646]
It's usually not worth changing this kind of stuff, since corpses probably drop various kinds of armor all the time, but the only corpse that gives the player a Mandalorian Battle Armor isn't actually a man wearing a set of Mandalorian armor. Dantooine uses a couple of those, so that one could be used here. It's true that, unless JC's mod is installed, the actual armor the player can wear uses a different body model, but that wouldn't make this case any different from the Mandalorians that drop this and the Mandalorian Assault Armor.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
Switching it doesn't really make much difference if you are arguing from some sort of "immersion" standpoint. The corpse will still be wearing the armour you supposedly stripped off it. I can't see you really gain that much. You're just swapping one type of immersion break for another.

**Comment by LaIngobernable** [comment]
That is true, but I'd argue it's more important for the player to notice the armor as they're exploring the tomb, rather than on their way out, when they know they've already swept the place. It's also a case of signalling high tier loot.

**Comment by DarthParametric** [comment]
Since there's no Mando corpse placeable, the only way to replace it would be to swap the existing placeable for an invisible one and spawn in a Mando creature with a spawn dead OnSpawn script. Doable certainly, but seems excessive for something so incredibly minor so we'll leave it as-is.
