### ISSUE TITLE
Missing tongue in PFHA04 and PFHC03

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#650]
Apparently PFHC03 (head 38) doesn't have a tongue. Admittedly, this is only noticeable with modded content.

**Comment by LaIngobernable** [comment]
Also the case with PFHA04, though this one is almost the exact same model as the Tatooine Czerka officer (head 83), which does have a tongue, so that should be easier to apply.

**Comment by DarthParametric** [comment]
Both vanilla PFHC03 and PFHA04 models absolutely have tongue meshes, which both have enabled render flags.
