### ISSUE TITLE
Taris Hidden Bek Base - Mismatching soundsets

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#651]
Not sure if what I'm looking at are UTCs in their vanilla state or not. Either way, none of the Twi'leks (male and female alike) in tar_m11aa have soundsets that match their appearance. They use either Rodian or Duros or male commoner soundsets.

Just for the sake of not reporting issues that may have already been fixed, are K1CP fixes reflected in the module files viewed in Holocron Toolset?

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
As long as you open the MOD and not the RIM, then yes, HT will show you the patched versions.
Be aware however that soundsets for most NPCs are completely irrelevant. It only matters if they are in combat or damaged/killed off during a cutscene. Random slobs milling about cantinas don't matter, as their soundset will never play.

**Comment by LaIngobernable** [comment]
Gotcha. In that case, at least the female Twi'leks can be given female commoner soundsets so as not to clone Zaerdra's, and males using the more expressive VO can be given the male Twi'lek soundset, which I believe is by the same voice actor. All of these should play out if siding with the Vulkars.
