### ISSUE TITLE
Global - Player heads PFHC01 and PFHC03 have incorrect eye texures in DS transitions

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#652]
I see the same texture screw up of #433 in PFHC01, specifically d2 and d3. Looks like they were playing with transparency between the two ends of the DS transition and just left it like that.

Edit: This problem arises in the cases where the full dark side variant shows reduced iris size. PFHC03 almost has the same problem, only they placed one on top of the other instead of randomly to the side. That one probably looks decent, though I'd have to check in-game.

**Comment by DarthParametric** [comment]
@LaIngobernable: Here, try these out and see how they look - [K1_PFHC01_C03_DS_Texture_Fix.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/9032539/K1_PFHC01_C03_DS_Texture_Fix.zip)

**Comment by LaIngobernable** [comment]
All right, first off, the irises look great. However, the pupils are inconsistent with most DS transitions in the game: in these, the pupil stays pitch black through the descent, whereas the rest experience progressive fading till it acquires a light gray tone (with some degree of variation in some cases).

One more thing: I can see that existing head textures were used as the basis for the veiny white of the eyes (c02, maybe?), which is exactly what I would've done for pfhc01, but not for c03, since her full DS eye is smaller and beneath/on top of her normal eye. The original eyeball is most likely the ideal, least invasive way to go there.
