### ISSUE TITLE
Star Forge Deck - Replicator bin has Security UI

### ISSUE THREAD

**Issue by LaIngobernable** [KOTORCommunityPatches/K1_Community_Patch#654]
The cylinder that spawns the Star Forge robes has Security UI when shielded by the force cage.

**Comment by DarthParametric** [comment]
This is a known issue with placeables. It can't be resolved. See #497 for example.

**Comment by Salk73** [comment]
Usable=0 removes interaction with the placeable but if it can't be changed back to 1 via script to 1 then one possible solution would be to use a non-interactive copy which is replaced with the interactive one when needed.
