### ISSUE TITLE
Force power issues

### ISSUE THREAD

**Issue by ghost** [KOTORCommunityPatches/K1_Community_Patch#655]
Not sure to what extent this is fixable, but just in case it's worth pointing out, I've been repeatedly able to use Force powers throughout this last run when my Force points were depleted (in fact, the number was negative). On top of that, Jolee was in the habit of using Stun Droid on dark Jedi and the PC, successfully.

_Submitted by muitafruita_

**Comment by DarthParametric** [comment]
> Jolee was in the habit of using Stun Droid on dark Jedi and the PC, succesfully

Can't say I have ever seen that behaviour at any time playing the game. Seems like it would be the fault of modified Force power-related scripts.
