### ISSUE TITLE
Taris Upper City North Apartments - Extort and kill Largo with a clean conscience

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#659]
As detailed on the [StrategyWiki](https://strategywiki.org/wiki/Star_Wars:_Knights_of_the_Old_Republic/North_Apartments#Largo.27s_Bounty), dark side points are only granted for certain dialogue options, despite others that lead to the same outcomes. Probably an oversight.

**Comment by DarthParametric** [comment]
Seems like the StrategyWiki entry isn't quite correct. They highlight the branch when returning to Largo after a previous conversation (R1), but you can also seemingly kill him without consequence during your initial conversation with him as long as you have already heard about the bounty from Zax (R22).
