### ISSUE TITLE
Taris Undercity Sewers - Mission opening the Vulkar energy field cutscene

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#66]
Mission doesn't actually interact with the computer panel, just stands in place and says her line. Should be easy enough to script her to walk to it and do the air-typing animation.

Vanilla scene:

https://www.youtube.com/watch?v=tbmgxCNvRaI

I suppose it's not the most terrible thing in KOTOR. It should probably be a standalone mod like my Jolee Shadowlands forcefield mod.

**Comment by Salk73** [comment]
I have taken care of this, if you guys still want to offer an improved cutscene there.

**Comment by DarthParametric** [comment]
I'd suggest just releasing it as a standalone mod.

**Comment by Salk73** [comment]
Just in case you are curious about the result: https://youtu.be/q4OuU9JAcTE

**Comment by Mako88** [comment]
I think this is minor enough (no module edits, etc.) that it'd be OK to include it in the community patch. I think less zoom-in during the typing would be good though (and possibly a slightly different angle - from the side instead of directly behind her?)

**Comment by DarthParametric** [comment]
Should be a static camera behind the terminal, showing the field and low enough/angled to obscure her hands not actually touching anything. I'd also jump the party for the scene setup to avoid having the PC move out of the way.

**Comment by Mako88** [comment]
Re-opening this, as I think it's within the scope of the K1CP.

**Comment by DarthParametric** [comment]
Revised scene - https://www.youtube.com/watch?v=0y9AJdoCIws
