### ISSUE TITLE
Most soundsets lack battle cry despite the audio existing for them.

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#661]
Seemingly a LOT of SSF soundset files have no Battle Cries set for NPCs despite both the audio file and TLK work existing for them.

In most cases, if you copied the TLK number for the Attack Grunt sound and reduce the TLK by 1 you'll find the Battle Cry TLK number.

As an example "n_darkjedif.ssf" has Attack Cry 1 set to "37009" as its first audio. If you changed the TLK to "37008" you'll see that the Dark Jedi had a Battle Cry which yelled "For the Sith!".

Hypothetically, a modder could go through all of the SSF files and restore the battle cry audio for all these soundsets.

**Comment by DarthParametric** [comment]
This can be merged into #565.
