### ISSUE TITLE
Star Forge - Bastila's face not shown when she speaks a line in the Dark Side ending of Carth's romance

### ISSUE THREAD

**Issue by Leilukin** [KOTORCommunityPatches/K1_Community_Patch#664]
If the player has completed Carth's romance subplot and chosen the Dark Side ending, Carth will show up on the Star Forge after the player defeats Malak. When Bastila appears and says, "Don't listen to him, master! Let me strike him down! Seize your victory!!", the game will skip to the player's dialogue options while Bastila's VO of that line is playing.

To fix the issue, just add these lines in `changes.ini`:

```
[k_sta_carth.dlg]
!Destination=Modules\sta_m45aa.mod
EntryList\9\Delay=4294967295
```

Here is a video showing the difference before and after the fix:

https://user-images.githubusercontent.com/58222702/183111285-0bd70fd6-e4a3-4bcc-a3c9-98d02f4a82ee.mp4

**Comment by Salk73** [comment]
As additional note of interest, I wonder if the Persuade animation at E7 is intentional? I guess it is supposed to be Carth's dismissive gesture delivered together with the "Don't interfere, Bastila. This is between me and Revan." line.

**Comment by DarthParametric** [comment]
Seems like that needs a forced camera angle change to mask a pretty transition. Try using 2 and see what that looks like.

P.S. I edited your post to add a blank line above the video in order for it to embed properly.

**Comment by Leilukin** [comment]
@DarthParametric Thanks for the suggestion. I changed the CameraAngle of E9 of to 2 and this is how it looks like in the game:


https://user-images.githubusercontent.com/58222702/207813766-711ee9a5-723f-4c08-b052-8af293a05d2e.mp4

**Comment by DarthParametric** [comment]
Hrm. Bastila has a scripted saber blade override? Looks like that's what's causing my issue with the camera cut. You could swap out her TALK_FORCEFUL for a TALK_NORMAL so she isn't waving the blade in her face. That might look better. Although it could just be the low framerate of the capture. ~18FPS? How does it look on your end in the actual game?

**Comment by Leilukin** [comment]
Yeah, on my computer K1 (at least the GOG version) at higher graphic settings tends to run below 30FPS when I do a video capture, unlike TSL (both GOG and Steam versions) which my computer has no problem with running around 60FPS even at the highest graphical settings when I do a video capture. I use Bandicam to capture screenshots and videos for both KotOR games.

I changed Bastila's animation to TALK_NORMAL and adjusted to the lowest graphic settings. This is what it looks like in my game:


https://user-images.githubusercontent.com/58222702/207822733-4721d2b9-18bf-4c00-a18c-62e8fe56fbf5.mp4

TSLPatcher's ChangeEdit output for changing Bastila's animation would be `EntryList\9\AnimList\0\Animation=10038`

**Comment by Salk73** [comment]
In the video above, Bastila is still using the TALK_FORCEFUL animation.

**Comment by DarthParametric** [comment]
You can upload a save if you want and I can check it on my end, but I believe I have seen enough to go ahead with the change once the anim switch is done.

**Comment by Leilukin** [comment]
Here is a save for it:
[DS Female PC Ending Save.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/10235908/DS.Female.PC.Ending.Save.zip)

@Salk73 I only changed the animation of E9 to TALK_NORMAL because it's the node that my issue focuses on, so E8 still had Bastila use the TALK_FORCEFUL animation in that video.

**Comment by DarthParametric** [comment]
Yeah might need to replace the TALK_FORCEFUL on the line to Carth and then leave it on for the player, or replace them both. Let me check it on my end first and see what the camera switch looks like without anim edits.
