### ISSUE TITLE
Taris North Apartments - What about doors?

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#665]
Minor intervention.

In the North Apartments complex in Taris we have three rooms that have no door. This is contrary to every other apartment complex of Taris (both upper and lower city). I was wondering if it might be desirable to add such doors. Two of them (the Sith partying rooms) would not need any particular attention while the third would need to be kept open if the Sith Commander interrogation is taking place.

**Comment by DarthParametric** [comment]
I would suggest this be submitted to N-DReW25 for inclusion in the [Unofficial Tweak Pack](https://deadlystream.com/files/file/2081-unofficial-k1cp-tweak-pack/).
