### ISSUE TITLE
Taris Lower City Apartments (West) - Calo's cutscene can be disrupted

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#669]
While testing the area above I got to go through the initial Calo's vs Rodians cutscene several times.

Eventually I clicked very fast through it in order to make it to the end and it once happened that Calo attacked with his fists the first time.  I guess the scripting needs safeguarding (NoClick()?) against such possibility.

**Comment by DarthParametric** [comment]
Probably easier to set the Skippable flag in the DLG to false.

**Comment by Salk73** [comment]
Of course that's a decent solution.
