### ISSUE TITLE
The player is unable to ask Juhani about the planet they are on

### ISSUE THREAD

**Issue by Leilukin** [KOTORCommunityPatches/K1_Community_Patch#673]
Juhani's global dialogue file `k_hjuh_dialog.dlg` shows that the player is supposed to have the dialogue option to ask Juhani about the planet they are currently on, like with some other party members. The line is indexed as R6 and R504 in `k_hjuh_dialog.dlg`. However, the player can never access said line in the game.

The cause of the problem comes from the code of the ` k_hjuh_w10` script, which is used for said line:
```
int StartingConditional()
{
    int iResult;
                                                                //Changed by Preston W - Was GetGlobalBoolean
    iResult = ((GetGlobalBoolean("K_AT_EBON_HAWK") == FALSE) && (GetGlobalNumber("K_CURRENT_PLANET") != 40) && (GetGlobalNumber("K_CURRENT_PLANET") != 50));

    return iResult;
}
```

The biggest problem with this script is including the `K_AT_EBON_HAWK` global check, which, as far as I know, is set to TRUE once you reach Taris, long before Juhani can join your party, and the global check stays TRUE throughout the rest of the game. We cannot simply delete the `K_AT_EBON_HAWK` global check from the code, because Juhani doesn't have any comment on Yavin, so we need to add another check to the script to ensure the player can ask Juhani about the planet as long as they're not on Yavin, the Leviathan or the Star Forge.

Here is my fix for the ` k_hjuh_w10` script, which I have also tested out in my game to ensure it works:
```
#include "k_inc_debug"

int StartingConditional()
{
    int nPlanet = GetGlobalNumber("k_current_planet");

    if(nPlanet != 40 && nPlanet != 50 && nPlanet < 55)
    {
        return TRUE;
    }
    return FALSE;
}
```

I borrow the script code from `k_hmis_planet`, which is used in the global dialogue of Mission and Canderous.

**Comment by Salk73** [comment]
It would be interesting to find out if it is actually true that the K_AT_EBON_HAWK boolean is set to TRUE when starting Taris and it stays so throughout the rest of the game.

Because if that is indeed the case, I think that we should fix that rather than the game scripts that are counting on that global to be TRUE or FALSE.

It'd be easy to add OnExit scripts for the EH module that set it to FALSE and tweak the OnEnter EH scripts to switch it back to TRUE.

Let's see if DP or JC have an opinion about it.

**Comment by DarthParametric** [comment]
It is set TRUE when entering the Hawk by `k_pebn_pophawk` and set FALSE when exiting the Hawk by `k_pebn_hawkgo`. There are seven Canderous and Juhani conversation scripts that use it, so I doubt it's a problem.

**Comment by Salk73** [comment]
But I all the on planet saved games I check using KSE report the Global being 1.

**Comment by Leilukin** [comment]
Yeah, I found out through KSE that even the on-planet saves have K_AT_EBON_HAWK being 1, which is why in vanilla, the player cannot ask Juhani about the planet they're on even outside the Ebon Hawk.

**Comment by DarthParametric** [comment]
Hrm, seems `k_pebn_hawkgo` isn't actually executed anywhere. 

![Well_Theres_Your_Problem](https://user-images.githubusercontent.com/46890653/194744271-9a0d3612-c286-4400-afb2-0e7c3ee7a041.jpg)

Per #466, we already have a modified version of `k_pebn_exithawk` (party selection exit script) applied universally across all Hawk modules, so we can just add it to that.

**Comment by Salk73** [comment]
Sounds good to me.

@Leilukin, such change would mean you don't need to modify k_hjuh_w10 at all and it would work globally for those other scripts that do include a check for K_AT_EBON_HAWK.

**Comment by Leilukin** [comment]
> @Leilukin, such change would mean you don't need to modify k_hjuh_w10 to remove the boolean check but only add the extra check for Yavin.

I still think it's better to remove the K_AT_EBON_HAWK check from the `k_hjuh_w10` script, because other party members, namely Carth, Mission, Canderous and Jolee, do not require you to be outside the Ebon Hawk to ask them about the planet you're on.

**Comment by DarthParametric** [comment]
We can just replace the reference in the DLG (since we already edit it anyway) to `k_hmis_planet`. Canderous also uses it as the starting conditional for his "ask about the current planet" branch. 

Interestingly, Jolee has a specific line for asking about the Hawk, and they don't check `K_AT_EBON_HAWK`. Instead they use the starting conditional `k_con_at_ebon`:

```
int StartingConditional()
{
    if(GetIsObjectValid(GetWaypointByTag("K_EBON_HAWK_LOCATION")))
    {
        return TRUE;
    }
    return FALSE;
}
```
Seems like they knew `K_AT_EBON_HAWK` was broken but didn't bother to fix it.

**Comment by Leilukin** [comment]
I'm fine with replacing the script reference in Juhani's DLG to `k_hmis_planet`. My fixed `k_hjuh_w10` script does borrow the code from `k_hmis_planet`, after all.

**Comment by Salk73** [comment]
On a side note, it seems like Bioware was ambivalent about allowing the party members to be asked about the planets they are on already on the Ebon Hawk.

To me, it does make little sense to have it that way but the original k_hmis_planet script doesn't use any check to make sure you're not on the Ebon Hawk when you do.

**Comment by DarthParametric** [comment]
I considered blocking that branch for all party members while on the Hawk, but that would create a bunch of extra crap to dump into the Override, which I want to avoid where possible. Plus Jolee has a specific line when on the Hawk, as mentioned above.
