### ISSUE TITLE
Tatooine - HK-47's face not shown when he speaks a line during the Storyteller conversation

### ISSUE THREAD

**Issue by Leilukin** [KOTORCommunityPatches/K1_Community_Patch#674]
This issue is similar to #664 which I reported. This time, the issue involves HK-47 during the conversation with the Storyteller on Tatooine.

When HK speaks the line "Cautionary: Master, if you mean to suggest that humanity is ancestrally linked to ancient Tatooine, you will strain his belief system to its pitiful meat-bag maximum.", indexed as E83 in `tat20_xstory_01.dlg`, the game will skip to the player's dialogue options while HK's VO of that line is playing.

To fix the issue, just add this line under [tat20_xstory_01.dlg] in `changes.ini`:

`EntryList\83\Delay=4294967295`

Here is a video showing the difference before and after the fix, with K1CP 1.9.2 installed:
https://youtu.be/hkBBIl6-yow

**Comment by DarthParametric** [comment]
Sub-issue of #221.
