### ISSUE TITLE
Leviathan - One part of the player's reply options to Saul makes the screen black during the interrogation scene

### ISSUE THREAD

**Issue by Leilukin** [KOTORCommunityPatches/K1_Community_Patch#675]
During Saul's interrogation scene on the Leviathan, after Saul says the line, "Now, I will ask again - on what mission did the Jedi Council send you?" (indexed as E62 in `lev40_saul403.dlg`), the game shows the player's dialogue options and Saul's previous line, but the rest of the screen goes black, as seen here:
![swkotor 2022-10-13 16-12-11-332](https://user-images.githubusercontent.com/58222702/195545560-3a3891d8-4892-4e48-b388-ed8f9537558b.png)

I found out the issue was caused by K1CP changing the CameraAngle of player's first two reply options, indexed as R69 and R70 in the DLG, to 6 in order to match the third option, indexed as R43, without changing the CameraID as well.

Changing the CameraID of R69 and R70 to 32 fixes the issue:
![swkotor 2022-10-13 16-19-32-090](https://user-images.githubusercontent.com/58222702/195546591-11251c5a-c1b0-42a7-960b-d0f6cb8e2587.png)

The output in `changes.ini` will look something like this under [lev40_saul403.dlg]:
```
AddField0=gff_lev40_saul403_CameraID_0
AddField1=gff_lev40_saul403_CameraID_1
[gff_lev40_saul403_CameraID_0]
FieldType=Int
Path=ReplyList\69
Label=CameraID
Value=32
[gff_lev40_saul403_CameraID_1]
FieldType=Int
Path=ReplyList\70
Label=CameraID
Value=32
```

For comparison, here is a screenshot of this part in the vanilla game:
![swkotor 2022-10-13 16-22-37-720](https://user-images.githubusercontent.com/58222702/195546730-c7e78f01-a862-4d1f-9f22-90957163476a.png)

**Comment by DarthParametric** [comment]
This was already fixed in 08a60498e78ec72e06c84f0de7aaf91ff0aee72e, as detailed in #145. Please search for existing issues before posting new ones.
