### ISSUE TITLE
Taris Undercity - Gendar calling PC UpWorlder

### ISSUE THREAD

**Issue by zappepappe** [KOTORCommunityPatches/K1_Community_Patch#679]
When asking Gendar the way to the sewers he calls the PC "UpWorlder", while in all other instances it is spelled "up-worlder".

**Comment by DarthParametric** [comment]
K1CP doesn't do TLK corrections. You need to use a dedicated TLK mod, such as - https://deadlystream.com/topic/7022-extensive-dialog-overhaul-beta-for-kotor-103/
