### ISSUE TITLE
Taris Lower City Apartments - Mispositioned placeable strongbox

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#68]
Elam Mattic's password-locked strongbox is clipping into the wall. Visible from sides and when opened. Requires a GIT edit.

Since they don't differentiate the apartments by name, it's module tar_m03ab (the one with Calo Nord).

**Comment by JCarter426** [comment]
Fixed.

**Comment by DarthParametric** [comment]
Per the duplicate #307, the fix failed to add the GIT to the GFF list, so the fix is not applied.
