### ISSUE TITLE
Taris Undercity - LS reward for saving Hendar

### ISSUE THREAD

**Issue by zappepappe** [KOTORCommunityPatches/K1_Community_Patch#680]
If you save Hendar from the rakghoul at the gate and talk to Hester you will get a Light Side reward, while if you talk to Hendar you will get the exact same dialog with no reward and won't be able to speak to Hester afterwards.

**Comment by Salk73** [comment]
Could you please check if you can find Hester and Hendar somewhere in the village after talking to them?

Anyway, the problem you reported is confirmed and easy to fix.

```
[tar04_hendar.dlg]
!Destination=modules\tar_m04aa.mod
EntryList\3\Script=k_act_lightsml
```

**Comment by DarthParametric** [comment]
A pull request is only possible when you create a fork of the parent repo and then add a commit with the changes to your repo. You can then issue a PR and Github will assess whether the changes can be merged. If so, it will notify the parent repo for acceptance. Please read Github's documentation on PRs - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests

**Comment by Salk73** [comment]
Got it.

Thanks.
