### ISSUE TITLE
Tatooine Cantina - More NPCs sitting at the tables 

### ISSUE THREAD

**Issue by LtFrankDrebin** [KOTORCommunityPatches/K1_Community_Patch#682]
I have a small QoL suggestion: is it possible to add more sitting NPCs to the tables inside the Tatooine cantina? There are 4 alcoves with tables at the front and the back of the room without any NPCs whatsoever. The Anchorhead cantina always felt a bit empty to me without some NPCs doing idle animations (drinking, talking) like they do on Manaan. Can more of them be added to that module just for the sake of atmosphere, to make it more lively?

**Comment by DarthParametric** [comment]
Not really the goal or purpose of the Community Patches. It's the sort of thing more suited to a standalone mod.
