### ISSUE TITLE
Bothan Needler & Sith Assassin Pistol have mismatched prices

### ISSUE THREAD

**Issue by N-DReW25** [KOTORCommunityPatches/K1_Community_Patch#684]
So the Bothan Needler and Sith Assassin Pistols are Hold Out Blasters, these have a base damage of 1-4.

Both the Bothan Needler and Sith Assassin Pistols have 25% for two rounds stun DC 10  and an Enhancement Bonus of 2 bringing their damage to 3-6.

Unlike the Bothan Needler, the Sith Assassin Pistol also has an additional Damage vs Racial Group Droid 1d10 Ion damage meaning it does additional damage to droids.

This means the Sith Assassin Pistol is slightly stronger than the Bothan Needler, but the Bothan Needler is more expensive to purchase as it costs 1750 credits whereas the Sith Assassin Pistol costs 1700 credits.

These should be swapped around.

**Comment by Salk73** [comment]
There are several ways to go about this.

One is to swap their respective prices so that the better weapon has a higher cost.

But I'd rather keep the original price and make the Bothan Needler's DC vs Stun harder to resist (10->14).
