### ISSUE TITLE
Suvam is missing a Force Persuade check for getting a pazaak deck

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#686]
(reported by Raisins)

If the player does not have a pazaak deck before meeting Suvam on Yavin Station, they have the option of buying one for him or using Force Persuade to make him hand one over for free. The latter option does not actually check whether the player has the Affect Mind/Dominate Mind power.

**Comment by DarthParametric** [comment]
Is that just R93 in the modified yav47_suvam.dlg?
