### ISSUE TITLE
Korriban Tomb of Naga Sadow - The Way of the Sith quest can be left orphaned

### ISSUE THREAD

**Issue by StuckInMyPants** [KOTORCommunityPatches/K1_Community_Patch#696]
During the final part of this quest, you're given 4 dialog options as to who you are going to side with. The bottom two options makes it to where you have to fight both sith. The dialog choice, "You're both mistaken. I chose me." properly updates the journal after the scene ends and the game is unpaused. The dialog choice, "I'm tired of playing along with you Sith scum! You both die!!" does not update the journal and leaves it forever stuck in your active quests.

Attached is a save right before the fight. I was using mods, so hopefully that doesn't induce a crash on vanilla games.
[000009 - Game8.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/12500925/000009.-.Game8.zip)

**Comment by Salk73** [comment]
This should be easily remedied.

```
[kor39_utharwynn.dlg]
!Destination=modules\korr_m39aa.mod
ReplyList\35\Quest=kor35_waysith
ReplyList\35\QuestEntry=50
```

**Comment by DarthParametric** [comment]
E20 has no `QuestEntry` set, so it shouldn't do anything. Since that's the entry where you return with the saber, I expect it's probably a leftover from an earlier stage of the question progression. Maybe they had a separate quest for inside the tomb.

**Comment by DarthParametric** [comment]
The submitted config block was incorrect. It should have been:

```
[kor39_utharwynn.dlg]
!Destination=modules\korr_m39aa.mod
AddField0=gff_kor39_utharwynn_QuestEntry_0
ReplyList\35\Quest=kor35_waysith
[gff_kor39_utharwynn_QuestEntry_0]
FieldType=DWORD
Path=ReplyList\35
Label=QuestEntry
Value=50
```
