### ISSUE TITLE
Taris Lower City Hidden Beks Base - Initial conversation with Gadon facing issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#70]
During the first Gadon convo there are some facing issues during Carth's interjections. 

This may be due to positioning - pathing issues seem to cause the player to run around behind Gadon to initiate dialogue. There's a trigger that fires Zaerdra's conversation as you approach, so perhaps it would be better to just launch straight into Gadon's convo as soon as that is done. That would allow for a herder script to jump the party into position.

**Comment by DarthParametric** [comment]
Prior speaker/listener edits have caused player freezing issues on subsequent nodes to several Zaerdra and Carth lines. The player will need forced animations to get them moving again.

- [ ] Player freeze after Gadon's line about Bastila being hidden "...You'll never find her".
- [ ] Player freeze after Gadon's line "The only hope....win the big season opener of the swoop race".
- [ ] Player freeze after Gadon's line "...If anyone can get inside the Vulkar base, it's her". Basically anything following a Carth or Zaerdra interjection.
- [ ] On Gadon's response to Zaerdra after asking about his eyes, he needs a facing switch halfway through towards the player, and the player needs an off-screen facing as well to point them back at Gadon.

**Comment by Salk73** [comment]
DP,

to your knowledge is it possible at all for the Player to ever trigger R44? 

The conditional script associated with it is the following:

```
int StartingConditional() {
	int int1 = ((GetGlobalBoolean("Tar_BastVulk") == 1) && (GetGlobalBoolean("Tar_GadonMission") != 1));
	return int1;
}

```

**Comment by DarthParametric** [comment]
In tar11_gadon112.dlg? Reply 44 is just an empty node between entries.

**Comment by Salk73** [comment]
Sorry, R44 is only in my own customized .dlg file. 

In the original file is R46.

**Comment by DarthParametric** [comment]
Ah. Yeah I was looking at that the other day. I assume it is cut content, since there's no way to know the Vulkars have Bastila before speaking to Gadon in the shipped game.

**Comment by DarthParametric** [comment]
1.9.0 beta test observations:
- [ ] Zaedra needs her AI disabled for the duration of the conversation to prevent her playing her ambient animations.

**Comment by DarthParametric** [comment]
1.10.0 beta test observations:

- [ ] After the initial "Vulkar spy" intro from Zaerdra, she can be seen to be frozen on the edge of the screen after the switch to Gadon. Needs an anim to flush her on the DLG switch.
