### ISSUE TITLE
Known issues with TSLPatcher - Installer migration to HoloPatcher/PyKotor

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#700]
There are bugs with TSLPatcher that are causing some of our patches not to apply. For example, it will fail to write `-1` to the sint32 `CameraID` field in DLGs. There are 28 examples of `CameraID=-1` in the current changes.ini at the time of writing, although most of those are probably spurious DLGEditor additions rather than actual desired changes. It also does the same for `PlotIndex=-1` (currently unused) and presumably any other sint32 field that might warrant a `-1`.

Current alternative installer options are [HoloPatcher](https://deadlystream.com/files/file/2243-holopatcher/) or some other derivation of its underlying [PyKotor](https://github.com/NickHugi/PyKotor). I have some issues with the way that HoloPatcher works, and I'm not sure how viable a custom PyKotor solution is (I don't plan on learning Python).

**Comment by th3w1zard1** [comment]
A full diff of k1cp tslpatcher vs pykotor can be found here:
https://pastebin.com/UUB8vDcg

**Comment by th3w1zard1** [comment]
> Current alternative installer options are [HoloPatcher](https://deadlystream.com/files/file/2243-holopatcher/) or some other derivation of its underlying [PyKotor](https://github.com/NickHugi/PyKotor). I have some issues with the way that HoloPatcher works, and I'm not sure how viable a custom PyKotor solution is (I don't plan on learning Python).

We've setup holopatcher to support both manually selecting a mod folder's `tslpatchdata` or automatically detecting it like tslpatcher does, when holopatcher.exe is placed next to `tslpatchdata`. The former behavior is what you're used to. I believe the latter behavior makes holopatcher the ideal 1:1 replacement, otherwise, further modifications can be made by request.

**Comment by DarthParametric** [comment]
So it turns out there are surprisingly few TLK overwrites required. Almost all the current changes will need to remain as appends.

```
StrRef0 -> [global.jrl] -> Categories\65\EntryList\18 -> "You learned that the Republic was sending the mercenaries to Hrakert Station..."
StrRef1 -> [global.jrl] -> Categories\65\EntryList\19 -> "You were banished from Manaan and therefore could no longer tell Nilko what you learned about Hrakert Station."
StrRef2 -> [global.jrl] -> Categories\53\EntryList\49 -> "Shaelas refused to talk to you after you poisoned the Kolto supply..."
StrRef3 -> [global.jrl] -> Categories\53\EntryList\50 -> "You were banished from Manaan before you had the chance to tell Shaelas what you learned in the Sith base."
StrRef4 -> [global.jrl] -> Categories\25\EntryList\40 -> "Now that you are banished from Manaan, you can no longer talk to Hulas to continue your quest for the Genoharadan."
StrRef5 -> [global.jrl] -> Categories\26\EntryList\98 -> "You can no longer collect the bounty on Ithorak's head as you were banished from Manaan."
StrRef6 -> [global.jrl] -> Categories\27\EntryList\97 -> "You were banished from Manaan and can no longer collect Lorgal's bounty."
StrRef7 -> [global.jrl] -> Categories\28\EntryList\98 -> "As you are no longer allowed to visit Ahto City you can't collect the bounty on Rulan's head either."
StrRef8 -> [global.jrl] -> Categories\29\EntryList\98 -> "Now that you're banished from Ahto City, there's no way you can still collect Vorn's bounty."
StrRef9 -> [global.jrl] -> Categories\30\EntryList\97 -> "You can no longer collect Zuulan's bounty since you were banished from Manaan."
StrRef10 -> [global.jrl] -> Categories\47\EntryList\75 -> "You are no longer allowed to visit Ahto City and therefore you can't compete in Manaan's Swoop races anymore."
StrRef11 -> [global.jrl] -> Categories\77\EntryList\45 -> "You were banished from Ahto City before the trial involving Sunry and the murdered Sith woman Elassa began..."
StrRef12 -> [n_trandoshan.ssf] -> "Trandoshan Battle Cry 1"
StrRef13 -> [n_trandoshan.ssf] -> "Trandoshan Attack Grunt 1"
StrRef14 -> [n_trandoshan.ssf] -> "Selkath Pain Grunt 1" ??? Should be Trandoshan
StrRef15 -> [n_trandoshan.ssf] -> "Trandoshan Death Cry"
StrRef16 -> [cp_dan14_sdroid.dlg] -> EntryList\13\Text(strref) -> "Casus is dead? Then it is as we feared. I will be sure Nurik is given this news, though it will break his heart."
StrRef17 -> [cp_dan14_sdroid.dlg] -> EntryList\12\Text(strref) -> "You may give the diary to me. Take these credits. They are a reward for recovering his son's diary."
StrRef18 -> [cp_dan14_sdroid.dlg] -> ReplyList\19\Text(strref) -> "He was mauled to death by kath hounds. I found a diary on the body."
StrRef19 -> [global.jrl] -> Categories\14\EntryList\30 -> "K1CP: Placeholder quest state for Casus" Currently unused
StrRef20 -> [global.jrl] -> Categories\14\EntryList\40 -> "With the Sandral and Matale familes both wiped out, you have little use for Casus' diary any more and quietly dispose of it..."
StrRef21 -> [m28ab_c01.dlg] -> EntryList\1\Text(strref) -> "Come on - hurry up!"
StrRef22 -> [m28ab_c01.dlg] -> EntryList\2\Text(strref) -> "Don't just stand there, we have to keep moving! The water is filled with..."
StrRef23 -> [m28ab_c01.dlg] -> EntryList\3\Text(strref) -> "Ahhhhhhh...."
StrRef24 -> [global.jrl] -> Categories\23\EntryList\50 -> "You never managed to find Dustil and talk to him before the whole Academy turned against you..."
StrRef25 -> [global.jrl] -> Categories\23\EntryList\60 -> "You found and spoke to Dustil, promising to find evidence of the true nature of the Sith. Unfortunately..."
StrRef26 -> [global.jrl] -> Categories\23\EntryList\70 -> "You found proof of Uthar's direct role in the death of Selene. Unfortunately..."
StrRef27 -> [missdoor_dlg.dlg] -> EntryList\29\Text(strref) -> "Okay then, off we go. Just look for the force shield and we'll know we're there."
StrRef28 -> [tar10_elevcar001.uti] -> Description(strref)/DescIdentified(strref) -> "This is a pass card that grants full access to the elevator security control terminal."
StrRef29 -> [tar02_messenger.dlg] -> EntryList\7\Text(strref) -> "Canderous didn't say why he wanted to meet you. He only said he had an offer you couldn't refuse."
StrRef30 -> [k_hjol_dialog.dlg] -> [gff_k_hjol_dialog_EntryList_353_0] -> "I suppose I am, in a way, despite the smell."
StrRef31 -> [kor38b_mekel.dlg] -> EntryList\7\Text(strref) -> "Commentary: The master keeps me around to comment on decisions. Don't you master?"
StrRef32 -> [credits.2da] -> RowIndex=15 -> ""
StrRef33 -> ??? -> "Trapped woman (?)" ???? Unimplemented? Should be for the Gamorrean trap in the Dune Sea
StrRef34 -> [lev_m40aa_plev_elev_dlg.dlg] -> ReplyList\3\Text(strref) / [lev_m40ab_plev_elev_dlg.dlg] -> ReplyList\3\Text(strref) -> "Command Deck"
```
The only overwrite candidates appear to be StrRef27, StrRef29, StrRef30, StrRef31, StrRef32. Possibly StrRef16 as well, but I'd need to check that one to be sure.

**Comment by th3w1zard1** [comment]
> The only overwrite candidates appear to be StrRef27, StrRef29, StrRef30, StrRef31, StrRef32. Possibly StrRef16 as well, but I'd need to check that one to be sure.
> 
> So the revised `[TLKList]` would look something like this:
> 
> ```
> [TLKList]
> File0=append.tlk
> StrRef0:15=0:15
> StrRef17:26=17:26
> StrRef28=28
> StrRef33:34=33:34
> 
> [append.tlk]
> ???=16
> ???=27
> ???=29
> ???=30
> ???=31
> ???=32
> ```
> 
> Not sure what the original StrRef IDs to overwrite would be, so I'll have to dig those out. Just using generic `???` for now.

You might need to put all your replacements in a different TLK file. `append.tlk` is a hardcoded name used for append syntax, when I added replacement support I never considered someone would want to use the same tlk file for both appends and replacements. So I've no idea if your example would work.
Regardless, for readability reasons you should put your replacements in another file `replace.tlk` or something.

**Comment by DarthParametric** [comment]
Just tried it out and it does actually work fine - mechanically at least - using append.tlk for both sets of StrRefs. Used the following config:

```
[TLKList]
File0=append.tlk
StrRef0:26=0:26
StrRef28=28
StrRef30=30
StrRef33:34=33:34

[append.tlk]
25859=27
45953=29
15985=31
42190=32
```
Ended up leaving StrRef16 as an append. 

Of course there is the point you raised about clarity between change types, but I don't see that as an issue. The only people likely to be messing with it are those wanting to do translations. Leaving it as a single `append.tlk` as it has always been is less likely to cause confusion than adding an entirely new second TLK.

Patched TLK attached: [K1CP_dialog.tlk_Overwrite_Test.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/12902361/K1CP_dialog.tlk_Overwrite_Test.zip)

**Comment by JCarter426** [comment]
What about using the maximum signed integer value 4294967295 instead of -1? ChangeEdit uses this value for a delay of -1, for example ([see here](https://github.com/KOTORCommunityPatches/K1_Community_Patch/blob/ff205d7da9db0aea8bfba47e2a4b173e408f8773/tslpatchdata/changes.ini#L4346C31-L4346C31)).

**Comment by DarthParametric** [comment]
That field is unsigned. See the related discussion around [here](https://discord.com/channels/259507540503691267/259507540503691267/1159496222449606688).

**Comment by JCarter426** [comment]
Well, that's unfortunate. TSLPatcher does support arbitrary binary file changes, which could theoretically fix the invalid values, but I doubt there is a way in the existing context to programmatically determine the which bytes need to be edited.

Also:

>StrRef0:15=0:15

Where is this syntax coming from? This isn't legal INI. Is this supposed to be shorthand for a range of instructions?

**Comment by DarthParametric** [comment]
> Where is this syntax coming from?

Added HoloPatcher syntax. Since TSLPatcher doesn't support TLK overwrites anyway, there's little point in sticking to the old syntax.

> Is this supposed to be shorthand for a range of instructions?

Yeah. In that example, it will append all StrRefs from 0 to 15.

**Comment by JCarter426** [comment]
I would advise against that. It's not an issue of TSLPatcher being able to parse it, but of making each instruction a valid key/value, which is easier for tools to parse and required by INI standards.

**Comment by DarthParametric** [comment]
So you want:
```
[TLKList]
File0=append.tlk
StrRef0=0
StrRef1=1
StrRef2=2
StrRef3=3
StrRef4=4
StrRef5=5
StrRef6=6
StrRef7=7
StrRef8=8
StrRef9=9
StrRef10=10
StrRef11=11
StrRef12=12
StrRef13=13
StrRef14=14
StrRef15=15
StrRef16=16
StrRef17=17
StrRef18=18
StrRef19=19
StrRef20=20
StrRef21=21
StrRef22=22
StrRef23=23
StrRef24=24
StrRef25=25
StrRef26=26
StrRef28=28
StrRef30=30
StrRef33=33
StrRef34=34

[append.tlk]
25859=27
45953=29
15985=31
42190=32
```

**Comment by JCarter426** [comment]
Considering these will generally be auto-generated by tools and not written by hand, yes, I'd advise for a syntax that is easier for tools to work with, even if it looks clunkier. The alternative is for future tools to have to deal with a non-standard syntax, of which we have enough examples already.

**Comment by th3w1zard1** [comment]
> I would advise against that. It's not an issue of TSLPatcher being able to parse it, but of making each instruction a valid key/value, which is easier for tools to parse and required by INI standards.

Normal ini does treat colons the same as equals you are correct. But most ini parsers easily let you configure the delimiter between key/value. If it's still a problem, just replace : with a '-' (dash) as both are treated the same in pykotor's tlklist parser
