### ISSUE TITLE
Crashed Swoops – Incorrect Windscreen Texture

### ISSUE THREAD

**Issue by WildKarrde1138** [KOTORCommunityPatches/K1_Community_Patch#703]
The vanilla crashed swoop placeables do not use the same windscreen texture as the regular swoops or the crashed speeders.  It appears to be the texture from the main body of one of the regular swoops with many of the details visible on close inspection, so presumably this was not intentional.  Attached are edited placeable models for consideration which have been revised to use the typical windscreen texture.

[K1 Crashed Swoop Windscreen Fix - Proposed.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/12910759/K1.Crashed.Swoop.Windscreen.Fix.-.Proposed.zip)

Before:
![Crashed Swoop 1 - Before](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/142758114/6a588008-da5f-412d-ae34-6e5374c8b2b3)

After:
![Crashed Swoop 1 - After](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/142758114/cdf3a870-3674-4620-9cdd-fc3de6c41296)

Before:
![Crashed Swoop 2 - Before](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/142758114/a2f3acec-ba7f-43a9-a411-07617fcbfc4f)

After:
![Crashed Swoop 2 - After](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/142758114/ed6bac85-0ed2-4f1b-878b-d770bc94ddd2)

**Comment by DarthParametric** [comment]
I noticed when looking at these for #797 that the one in the final picture has a pretty terrible walkmesh. Can be fixed at the same time as enabling the shadows.
