### ISSUE TITLE
Taris Davik's Estate - Calo/Davik hangar fight can be reinitiated

### ISSUE THREAD

**Issue by th3w1zard1** [KOTORCommunityPatches/K1_Community_Patch#708]
By 'restarting the sequence' I mean the dialog sequence of 'Well well well, look what we have here: Thieves in the hanger!' happens *again* after clicking the door.

I was doing pretty bad in the fight on expert difficulty, so I tried clicking the door as Canderous which caused my main PC to resurrect, and then the sequence restarted.

Is this a fixable bug? Sorry if it's already been reported.

**Module**: `tar_m08aa.mod` 
**Dialog**: `tar08_davik082.dlg`
**Door**: `tar08_hangardoor.utd`
![image](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/2219836/b49597b8-354e-44b9-8e0b-a3c749c45399)

**Comment by th3w1zard1** [comment]
![20231106165306_1](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/2219836/8a17e8ff-4181-4b2e-a3ee-609358524389)
![20231106165626_1](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/2219836/4ed91ea1-2135-45af-8943-12404b7c8e7c)
![20231106165638_1](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/2219836/4a99b510-ae9b-462f-8bcf-c5b5d50e7a54)
![20231106165641_1](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/2219836/b5015f89-a8f3-455b-9bde-c63d92f2fa3e)
![20231106165651_1](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/2219836/a6fa6211-af5b-4581-9301-54aaf9439360)

**Comment by DarthParametric** [comment]
This would appear to be an error with [k_ptar_expstartd](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M08AA_Taris_Daviks_Estate_tar_m08aa/k_ptar_expstartd.nss) which fires on the first node of the scene's DLG (tar08_davik082.dlg). Amongst other things, it closes the door and then locks it via:
```
AssignCommand(oDoor, ActionCloseDoor(oDoor));
DelayCommand(1.0, AssignCommand(oDoor, ActionLockObject(oDoor)));
```
However, it would appear that `ActionLockObject` is not functioning as intended. The usual approach would be to use `SetLocked(oDoor, TRUE)`, so switching it to that should resolve the problem.

Here's a revised script if you want to test it: [k_ptar_expstartd.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/13276345/k_ptar_expstartd.zip)

**Comment by DarthParametric** [comment]
One addition thing I noticed, unrelated to the issue at hand, is that at the end of the initial scene the party and Davik/Calo will just stand there looking at each other. Calo and Davik do get a `GN_DetermineCombatRound` at the DLG's exit node, but it appears that they are too far apart (just over 20m) for the combat AI to kick in. Can be alleviated by moving the party forwards during the scene (hijacking [k_ptar_davwalk](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M08AA_Taris_Daviks_Estate_tar_m08aa/k_ptar_davwalk.nss)).

**Comment by DarthParametric** [comment]
1.10.0 beta test observations:

- [ ] There's an issue with the entry where close combat party members run away from Calo. Seems like it can take longer than the stunt anim, causing him to briefly teleport to world zero before the next entry. The script that governs it either needs a hard delay cap to less than the anim, or some other adjustment. Possibly an `ActionPauseConversation` can be removed altogether, since the DLG should now be set up to delay based purely on anim length and is set to unskippable.
- [ ] During that same entry, if you have the whole party ganking Calo in melee, they can all try to run to the same waypoint, which causes the usual pathing issues. Each PM needs a separate destination.
