### ISSUE TITLE
Taris Lower City Hidden Beks Base - Bek mooks attack with fists

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#71]
If you side with the Vulkars and kill Gadon, many of the Beks (especially in the front section) appear to lack melee (or any) weapons and will attack with punches/kicks. Once again may be the first round AI issue.

**Comment by DarthParametric** [comment]
Seems like all the "ambient" Beks out the front have melee weapons in their inventory. So it is indeed the first combat round problem again.

**Comment by JCarter426** [comment]
Well, that's typical. Sounds like a job for JC.
