### ISSUE TITLE
Installed patch over Steam copy of the game, game now refuses to open if there is no Disc Drive

### ISSUE THREAD

**Issue by Nicholas-Steel** [KOTORCommunityPatches/K1_Community_Patch#721]
As the title says, applying the patch to the Steam version breaks its No-CD crack.

**Comment by DarthParametric** [comment]
It doesn't do anything to the exe. You installed something else that broke it presumably.

**Comment by Nicholas-Steel** [comment]
I'm not the person that actually ran in to this issue so my knowledge is limited, but after they installed the patch the game would display this 
![image](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/11567846/038ed4ee-03a3-471c-9c0d-e2b368444f2f)

The patch was downloaded via https://deadlystream.com/files/file/1258-kotor-1-community-patch/

**Comment by DarthParametric** [comment]
Closing this since it has nothing to do with K1CP. As I said, it doesn't touch the exe.
