### ISSUE TITLE
Taris Lower City Javyar's Cantina - Canderous post-Sith Base conversation repeated lines

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#73]
In Canderous' post-Sith Base conversation, if you talk to him and tell him you have things to do first, when you come back he repeats the same opening lines of dialogue again. It would be preferable to alter this to something akin to "You're back", depending on available VO that can be harvested.

**Comment by JCarter426** [comment]
Done.
