### ISSUE TITLE
Manaan Hrakert Rift - Star Map does not close

### ISSUE THREAD

**Issue by WildKarrde1138** [KOTORCommunityPatches/K1_Community_Patch#734]
Unlike the star maps on Tatooine, Kashyyyk, and Korriban, the one on Manaan does not seem to close after showing the player the map.  From examining the scripts, it looks like Manaan is the only one of the four that does not use the utility function UT_StarMap4RunStarMap, which (among other things) queues the open, map, and close animations in sequence.  The Manaan map queues the open and map animations in  k_pman_starmap05.ncs but apparently never queues the close animation.  Attached is a proposed fix which adjusts the code to match UT_StarMap2PlayAnimation (leaving out the SW_PLOT_HAS_TALKED_TO check, which wasn’t in the original k_pman_starmap05).
[Manaan Star Map Close Fix - Proposed.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/13537885/Manaan.Star.Map.Close.Fix.-.Proposed.zip)

It's also worth noting that the Dantooine star map doesn’t appear to close either, which I presume was intentional so that it stays open through the conversation that follows.  Not sure if it would be worth adding a command somewhere to close it after the conversation ends or if it’s better to leave as-is.

**Comment by DarthParametric** [comment]
The changes made as part of #756 can be utilised to address this. 

See also #105 for previous edits made to the Dantooine map sequence that can incorporate the same changes.

**Comment by DarthParametric** [comment]
Couple of other issues I spotted.

- [ ] The star map is sitting a few inches off the ground.
- [ ] The second shot of the open map, static cam 6, is from a low angle, which shows the hole in the top of the skybox.

**Comment by DarthParametric** [comment]
1.10.0 beta test 2 observations:

- [ ] The additional static cam shots should be added to all map stages, not just the final one.
