### ISSUE TITLE
Global - Star Map placeable doesn't play the correct SFX on closing

### ISSUE THREAD

**Issue by WildKarrde1138** [KOTORCommunityPatches/K1_Community_Patch#757]
- According to placeableobjsnds.2da, there are separate sounds for opening and closing the Star Map: pl_starmap_open and pl_starmap_close, respectively.  In-game, however, it sounds like the map plays pl_starmap_open for both opening and closing.  Changing the “used” field for the Star Map in placeableobjsnds.2da to pl_starmap_close appears to fix the issue and plays the correct sound when closing the maps.
- When the Korriban Star Map opens, the opening sound is overlayed on itself with a slight delay.  This appears to be because k_pkor_star_map.nss triggers a sound object which also plays pl_starmap_open.  Since the sound effect already plays automatically with the animation, the SoundObjectPlay command would seem to be redundant (although, interestingly, Kashyyyk and Tatooine also manually queue the sound effect with a PlaySound command).
- The open and close sounds for the Tatooine Star Map seem to be unusually quiet compared to the other planets, sometimes to the point of being inaudible.  I have not determined what the cause might be.

**Comment by DarthParametric** [comment]
I believe the Dantooine Ruin star map also has a sound object to play SFX.

**Comment by DarthParametric** [comment]
Confirmed that the 2DA edit works. If you want to supply the ini config that will be less work for me.
