### ISSUE TITLE
Taris Upper City Cantina - Clone patron appearances

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#77]
There are two female patrons on the far opposite side of the entrance standing right next to each other that have the same appearance. Short blonde hair, green (?) clothes. 

I believe @JCarter426 said he had addressed this? Was a fix pushed already?

**Comment by JCarter426** [comment]
I fixed some clone issues with the commoners in appearance.2da, but it looks like several UTCs there still repeat appearances. In that case, even though the two women have different UTCs, they're both pointing to Lite_Commoner_Female_04.
