### ISSUE TITLE
Kashyyyk Czerka Landing Port - Conversation between Juhani and Canderous is never heard

### ISSUE THREAD

**Issue by H27-M42** [KOTORCommunityPatches/K1_Community_Patch#780]
Quote:

"Due to a small glitch in a dialogue file Bioware forgot to fix, a conversation between Juhani and Canderous that takes place on Kashyyyk is never heard in the final version of the game

If you have KOTOR Tool, you should be able to remedy this.

INSTRUCTIONS

Just open RIMs/Modules/kas_m22aa_s.rim and find 22aa_zaalb02_01.dlg [sic] under dialog. Just move Juhani’s branch below Canderous’ and save the file to your override folder"

Should be 22aa_zaalb01_01.dlg instead of 22aa_zaalb02_01.dlg though, source: [LucasForums (archive)](https://web.archive.org/web/20080118110300/http://www.lucasforums.com/showthread.php?t=184979), [backup](https://www.tapatalk.com/groups/kotor_movies/missing-juhani-and-canderous-conversation-t758.html)

**Comment by DarthParametric** [comment]
This is a sub-issue of #513.
