### ISSUE TITLE
[GLOBAL] PFHC04 mouth/teeth issue? 

### ISSUE THREAD

**Issue by Salk73** [KOTORCommunityPatches/K1_Community_Patch#782]
In the initial sequence I noticed a problem with the rendering of the teeth.

I'm attaching here four pictures taken in sequence to illustrate.

![Pic1](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/49585226/f47d5091-10ea-4825-bba2-123e00b15fde)
![Pic2](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/49585226/889feabe-3ab7-414a-b193-c787a7e3c4b6)
![Pic3](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/49585226/b9ded73c-195e-40ec-9184-7de5ae62ca06)
![Pic4](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/49585226/75439328-7114-47c9-85fa-695e1cf6f5b8)

Can something be done about it?

**Comment by DarthParametric** [comment]
Sub-issue of #404. Please post it in there.
