### ISSUE TITLE
Empty rocks in the Krayt Dragon Cave.

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#785]
As per a recent change in the K1CP 1.10 update, the two lightsaber crystals that are found on rock placeables in the Krayt Dragon cave were moved to the corpse placeable with Jedi Master Robes.

This latest change creates two issues, the first issue is that the two lightsaber crystals being found on these rocks did make sense when you think about it... the crystals are found amongst a rock formation, in the sci-fi Star Wars universe it wouldn't be too much of a stretch to assume that crystals would be growing inside a Krayt Dragon cave (especially as it houses a Dark Side infused Star Map).

You could argue that the specific Opila upgrade crystal shouldn't grow in a cave on Tatooine because its description indicates that it grows in an asteroid field, though the same argument can be applied to the Rubat upgrade crystals found in the Dantooine crystal cave as they're apparently mined on Phemis.

And the second issue is the most important one, since these crystals have been moved from the rocks and onto the Jedi corpse this has left two empty rock placeables inside the cave. I have three ideas for a fix here: 1) move the crystals back to their vanilla locations. 2) set the rock placeables to static. 3) remove the rock placeables entirely.

Also, after checking the associated placeables and this GitHub, I must ask this... did you guys move the crystals and blaster rifle items around using the on-enter script? Since K1CP is now probably THE most popular K1 mod and is on par with TSLRCM why does K1CP need this awkward switcheroo function? You're not saving anyone with compatibility, and even if you were K1CP is so popular other mods should be made compatible with it, not the other way around. Why not just modify the placeables directly and save those changes in the .MOD?

**Comment by DarthParametric** [comment]
> did you guys move the crystals and blaster rifle items around using the on-enter script?

No.

Anyway this is a sub-issue of #210. Move discussion to there.
