### ISSUE TITLE
Tatooine Cantina - Furko Nellis's uses the Fat Commoner Model

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#786]
Furko Nellis is a Pazaak player in the Tatooine Cantina who uses the vanilla Fat Commoner model which uses a male player head.

https://starwars.fandom.com/wiki/Furko_Nellis

In the most recent update, the fixed Fat Commoner model was removed thus restoring it to the broken vanilla model. The broken vanilla model wasn't too noticeable when it used "N_FatComM01"as its texture, but as part K1CP's old fix the fat texture was replaced with "N_CommM01" via the appearance.2da.

Again, using "N_CommM01" wouldn't be noticeable if it was the vanilla "N_CommM01" skin... but K1CP replaced that texture with the K2 "N_CommM01" texture which causes the black background elements of the texture to appear on the vanilla Fat model.

Here are a few solutions to solve this problem:

Solution 1: Restore the fixed Fat Commoner model but only use it for Furko Nellis.

Solution 2: Restore the vanilla "N_FatComM01" texture so that Furko Nellis looks as he does in the vanilla game.

Solution 3: Give Furko Nellis a generic commoner appearance, thus removing the Fat Commoner model from K1CP once and for all.

**Comment by DarthParametric** [comment]
This was a mistake on my part. The 2DA revision wasn't implemented correctly. Added to #539 in [this post](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/539#issuecomment-1872518608).
