### ISSUE TITLE
Unable to progress Dwindling Supplies when checking the Supplies container.

### ISSUE THREAD

**Issue by Gezmondo** [KOTORCommunityPatches/K1_Community_Patch#788]
When I check the supplies after speaking to Zaalbar, the dialogue is "[This is a store of emergency food and supplies]", instead of the dialogue that continues the quest.

After looking at the ebo_supplies.dlg, it looks like the conditional that continues the quest "k_ebo_sasha1040" is misspelled as "k_ebo_sasha10-40". After editing it in the dlg, I am able to continue the quest. I'm not sure what other mods edit that dlg, or if this is just an old bug, but I figured I'd report it.

**Comment by DarthParametric** [comment]
> I'm not sure what other mods edit that dlg

Not K1CP. `k_ebo_sasha10-40` is the correct vanilla script. You're using some other mod that broke it. The quest works correctly in K1CP so this is a problem on your end.
