### ISSUE TITLE
Taris Sith Base Governor's Quarters - it's possible to retrigger the dialog during the fight.

### ISSUE THREAD

**Issue by th3w1zard1** [KOTORCommunityPatches/K1_Community_Patch#790]
When you enter the room, after exiting the elevator, the sith dude greets you with 'Who dares enter...'.

Once that dialog finishes the fight begins. If you mistime your attack right at the beginning, it tries to retrigger the dialog (replays 'Who dares enter...'), causing a myriad of bugs and giving potentially unlimited dark side points. Very odd git camera behavior.

Is this something the k1cp would be willing to fix?

**Comment by DarthParametric** [comment]
Can't recall ever encountering it, and we don't edit that module so it's presumably not an error on our part. You sure it's not from another mod?

**Comment by th3w1zard1** [comment]
Yes to clarify this isn't a k1cp bug, it's a vanilla bug. You can reproduce it by attacking the guy too quickly after he finishes talking

**Comment by th3w1zard1** [comment]
Possibly similar to #708

**Comment by DarthParametric** [comment]
OK so it's a simple [OnOpen script](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Modules/M09AB_Taris_Sith_Base_Governors_Quarters_tar_m09ab/k_ptar_govtlk_en.nss) on the door that signals the Governor to begin a conversation via `UT_InitConversation`. The DLG then fires the generic [`k_act_atkonend`](https://github.com/KOTORCommunityPatches/Vanilla_KOTOR_Script_Source/blob/master/K1/Data/scripts.bif/k_act_atkonend.nss) which sets him hostile and fires `GN_DetermineCombatRound` to have him attack after 0.5 seconds.

I see two problems. The first is that the DLG is not setting a Talked To boolean to prevent that branch starting again. The second is that there clearly needs to be a `NoClicksFor` on the exit script to curb the behaviour of click spammers.

**Comment by th3w1zard1** [comment]
Sorry I forgot to follow up here. Looking at the DLG in question I believe what your solution entails matches up with the behavior I was seeing in the bug.
