### ISSUE TITLE
Updating with v1.10 over v1.9.2

### ISSUE THREAD

**Issue by s0rl0v** [KOTORCommunityPatches/K1_Community_Patch#791]
Hello team!

I have installed KOTOR a year ago with community patch and some mods, I remember it took a lot of time and actually I don't remember the exact list of what I've installed :)

So, is it possible to update KOTOR installation with v1.10 if I have already installed v1.9.2 version before?
Will it break something?

I didn't find any info about installing comminity patch updates, so here I am.

Thank you for your work and have a nice day.

**Comment by DarthParametric** [comment]
No, there's no migration path from a previous version. A clean install is the only option. Your existing saves would _probably_ still be fine, but no guarantees. Especially regarding Xor, since further changes to his implementation were made.
