### ISSUE TITLE
Tatooine Eastern Dune Sea - Wrong Rodian texture used in Calo's Cutscene

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#792]
When Calo is introduced just outside the Krayt Dragon Cave, there is a unique cutscene which has two Rodian and two Aqualish sitters inside of Speeder objects to give the impress that these guys used a speeder to reach your location. The problem begins when the fade to black occurs and the real NPCs spawn in, because of K1CP's recent N_Rodian01 texture fix the Rodians who spawn in use a different skin than the Rodian sitters at the start of the cutscene.

The Rodian sitters use the yellow N_Rodian02 texture whilst the Rodian NPCs use the N_Rodian01 texture. This bug didn't exist in the vanilla game because the N_Rodian01 Rodians used the wrong N_Rodian02 texture.

There are two ways of fixing this, either give the Rodian sitters the proper N_Rodian01 texture or swap the appearances of the Rodian NPCs from N_Rodian01 to N_Rodian02 to match the sitters.

**Comment by DarthParametric** [comment]
Sub-issue of #582.
