### ISSUE TITLE
Global - Inconsistent model variation for Calo Nord's blasters

### ISSUE THREAD

**Issue by N-DReW2020** [KOTORCommunityPatches/K1_Community_Patch#794]
Throughout the vanilla game and the promotional material using Calo Nord, he consistently uses two Mandalorian Heavy Pistols. An issue with these pistols in the vanilla game is that he won't drop them on some planets.

This was fixed in an earlier update of the K1CP, but instead of making the Mandalorian Heavy Pistols droppable it replaced those pistols with an Arkanian Heavy Pistol and a Zabrak Tystel Mark III and made those droppable instead.

These two pistols were in Calo's inventory for a stunt version of Calo called "bp_calo_ambush.utc". This could suggest that the Arkanian & Zabrak pistols were early picks for Calo's weapons in earlier builds before being replaced with the Mandalorian pistols... but this stunt Calo is only used when Calo is depicted on a speeder bike outside the Krayt Dragon cave & is deleted and replaced with the actual Calo Nord you fight (bp_calo_ambush_2.utc)

There are also a few disparities between all the Calo UTCs across the game. Calo in Javyar's Cantina & the apartment has an Insta-Kill Heavy Blaster that uses the Mandalorian Heavy Blaster model, in Davik's Estate he uses normal Heavy Blasters and across the different planets where he fights you in the vanilla game he'll again use Mandalorian Heavy Blasters.

And on Tatooine, Calo had a Retinal Combat Implant and a Nerve Amplifier Belt equipped unlike all the other planets (the K1CP has removed these items to keep them consistent with the other planets) and in Davik's Estate Calo wears a Retinal Combat Implant, Sonic Nullifiers and Sith Power Gauntlets.

These last few items might be outside the scope of the K1CP, but the blaster disparities should be fixed.

**Comment by djh269** [comment]
I ran into this issue when I last played K1CP, it was always my assumption that he should drop 2 Mandalorian Heavy Blasters

**Comment by Salk73** [comment]
I think Bioware decided to equip Calo with two simple heavy blasters at Davik's because the fight there is already quite tough and Calo shooting with two heavy blasters would make it even harder.

**Comment by N-DReW2020** [comment]
> I think Bioware decided to equip Calo with two simple heavy blasters at Davik's because the fight there is already quite tough and Calo shooting with two Mandalorian heavy blasters would make it too hard.

The Mandalorian Heavy Blasters in the Javyar's Cantina scene are custom items that simply have the Mandalorian Heavy Blaster texture and the Insta-Kill effect. Even if Mandalorian Heavy Blasters are too strong for Taris (would have to be play tested), you can always give Calo a custom Heavy Blaster item that uses the Mandalorian Heavy Blaster texture with no stats (making it the equivalent of a Heavy Blaster but with the appearance of a Mandalorian Heavy Blaster).

**Comment by Salk73** [comment]
> Even if Mandalorian Heavy Blasters are too strong for Taris (would have to be play tested)

The K1 CP isn't supposed to make alter the balance of the original game challenge. I don't think any playtesting is necessary to decode whether it's the case to swap Calo's pistols in Taris to Mandolorian Heavy Blasters. It'd be find to have standard Heavy Blasters looking like Mandalorian Heavy Blasters, though I'm not sure it's any of K1 CP's business either. There is no clear mistake there: Bioware might have wanted to equip Calo exactly with the pistols he shoots with there.
