### ISSUE TITLE
Why no source code from the executable?

### ISSUE THREAD

**Issue by dougg0k** [KOTORCommunityPatches/K1_Community_Patch#795]
Also why no build steps included?

All the other files except the most important ones that will show me whether what you are offering are actually safe or not, are not available.

<https://www.virustotal.com/gui/file/cdee80d28f9f87ffaa0b39fdfb46a2a3139858d87b3695d5161c96c02df14068> - I would like to see the source code to confirm the false positives.

It cannot be the Holo Patcher alone as it gives different scan results, and the Install.exe are the one causing all the false positives.

Any reason to use this Install.exe rather than the Holopatcher itself?

**Comment by DarthParametric** [comment]
K1CP is not affiliated with PyKotor/HoloPatcher, just as it wasn't with TSLPatcher.

See here - https://github.com/NickHugi/PyKotor/tree/master/Tools/HoloPatcher

**Comment by dougg0k** [comment]
Right, but why no source code and no build steps included?

**Comment by dougg0k** [comment]
Is there a problem in answering the main question? 

Seems that it was not answered intentionally.

**Comment by DarthParametric** [comment]
I gave you a link to the PyKotor repository if you want to see the source, build HoloPatcher yourself, or simply get the latest bleeding edge version from the automated Actions. 

The version of HP bundled with K1CP was provided by Cortisol (PyKotor's author) at the time of release in December. There have been subsequent public releases of the standalone HP exe on DeadlyStream since then, and numerous updates to the source code. If you want to replace the bundled version with a newer update, it should work perfectly fine. 

The false-positive AV reports are a known issue with any PyInstaller packed executable. The authors of PyKotor are exploring potential avenues to mitigate the problem for future versions.

**Comment by th3w1zard1** [comment]
@dougg0k 

> Right, but why no source code and no build steps included?
> I would like to see the source code to confirm the false positives.

A simple google search yields the source code: <https://github.com/NickHugi/PyKotor>

Kindly direct further queries towards the correct github repository, there's no need to bother the k1cp folks with this baggage.

> Is there a problem in answering the main question?
> 
> Seems that it was not answered intentionally.
> Also why no build steps included?

Are you for real? You mean to tell me that anytime you create anything, whether it's a JPEG, mdl/mdx, whatever, you provide the source code to every tool used to do so, and provide build instructions on how to let others do this? You have total comprehension of how your operating system works, your filesystem drivers responsible for managing the communication from your os buffers to the storage? No... we all use software and we don't always know how it works... You realize the game itself is not open-source right?

> Any reason to use this Install.exe rather than the Holopatcher itself?

This is HoloPatcher.exe renamed to Install.exe. If you compare the version number on that EXE (v1.42) to the matching release on github, the sha256 hashes are matching. You can verify these kinds of things using `certtool` on windows.

To answer your question, the av detections are false-positives... There's a fantastic explanation available here:
<https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md>

**Comment by dougg0k** [comment]
You are asking if I am for real, just seemed like the main question was avoided as the issue was closed.

For sure, not every closed source tool has to or provide the source, the point is subjective on the what and who is behind it.

Why would you not post the source code online for a simple tool like this and coming straight as sending unrelated arguments to a valid question?!

By proving the source code, it would mean that it is open source and trustworthy and that I am not being deceived by the tool and/or arguments alone. Of course I have the choice to not use it, the point is that is they provide as community tool, so anyone else if not me using, would end up being deceived instead.

I am not saying that this is the case, just the point of the question.

What does me knowing every internal aspect of the OS related to this tool? Because it's closed source? Like I said is dependat on what and where is coming from. Different people could have different goals in mind if that were even anything to be considered.

They are not even the same size, how they would have the same hashsum?

```
nu ❯ du
   7.30 MiB INSTALL.exe
   9.09 MiB HoloPatcher.exe
  16.39 MiB total

nu ❯ sha256sum HoloPatcher.exe
7a1cc0fb30c5f3653fac36b9d8283d04c5a3db308e55c247cc1593c6ef45690f  HoloPatcher.exe

nu ❯ sha256sum INSTALL.exe
5cc9fc7aeafefb8b18cd584de0ad530f5c7a057e4b0a1308ed7bc6a9e4bc3fbe  INSTALL.exe
```

**Comment by th3w1zard1** [comment]
1. you should forward your complaints over to [the PyKotor repo](https://github.com/NickHugi/PyKotor/) and post an issue saying they should do better version control as that's a valid complaint. This isn't the k1cp's problem. 
2. You've compared a total of two files. You realize there's about 10 different releases now right? Match the version manifest
![image](https://github.com/KOTORCommunityPatches/K1_Community_Patch/assets/2219836/c6391cd3-a91d-4878-9aa9-9f120dd920b3) What versions did you compare.
3. HoloPatcher follows semantic versioning and follows its strict backwards compatibility rules. Just use another patch version or build it yourself from src

The sad truth is if someone like you or me wants to develop as a hobby in their free time, but can't afford $200/mo signing licenses, this problem really can and does kill projects...

**Comment by dougg0k** [comment]
> This is HoloPatcher.exe renamed to Install.exe. If you compare the version number on that EXE (v1.42) to the matching release on github, the sha256 hashes are matching. You can verify these kinds of things using `certtool` on windows.

You said to compare 1.42, that it was renamed. 

There is nothing to complain, as you are the one who do not provide the source code from your version, not them. You obviously have the choice not to, I never said you did.

Your install file are still suspicicious and that's about it.

**Comment by dougg0k** [comment]
I clearly compared the wrong version, they have the same size with the `1.43`. I had compared with the latest as I didnt know the current one from your install. 

They seem to have the same amount of results in the scan, I guess I am wrong on this, my bad.
