### ISSUE TITLE
Xor post-combat dialogue

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#8]
Sometimes Xor doesn't initiate his dialogue if he is killed before his friends.

**Comment by JCarter426** [comment]
[According to Past JC](https://deadlystream.com/topic/6214-conversation-sometimes-not-starting/?tab=comments#comment-64398), it must be Xor's perception event failing to fire. Possibly copying that script to a custom heartbeat script would bypass the problem.

**Comment by JCarter426** [comment]
I have a save that leads directly into the encounter, but even after going through it five times, I didn't get the bug. I have experienced it in the past, though, so I know it happens. But without a guaranteed way to trigger it, there's nothing to be done.

**Comment by JCarter426** [comment]
[000160 - Game159.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/2816846/000160.-.Game159.zip)

I've attached a save for testing, at least. I think it's clean and should load regardless of mods.

If you hit "return to _Ebon Hawk_", Xor will come.

**Comment by DarthParametric** [comment]
Interestingly, this save causes a hard crash on load on XP. In 10 I can't transit back to the Hawk without crashing back to the main menu, but I can manually run back, hop in, then come back out. He didn't spawn for me.

**Comment by JCarter426** [comment]
I'm pretty sure I've only ever had him spawn spawn on Manaan. I definitely fought him there the last two times, and the bug happened to me on one of those. Though I can't get it to happen anymore, it seems.

**Comment by JCarter426** [comment]
Could not reproduce. Closed until we have a reliable way of testing it.

**Comment by DarthParametric** [comment]
The transit issue is at least resolvable with a fix from Darth333 - http://www.jeuxvideo.com/forums/1-7045-9914472-1-0-1-0-0.htm

```
The error is in the script k_sup_gohawk.nss, or instead of putting

SetGlobalNumber ("K_XOR_AMBUSH", 1);

Bioware put: SetGlobalNumber ("K_XOR_AMBUSH", TRUE);
```

**Comment by JCarter426** [comment]
Added triggering the encounter as [its own issue](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/29).

**Comment by DarthParametric** [comment]
Just got this issue on Tatooine when killing him last. Again though, it wasn't reproducible. On reloading the save prior to entering the docks, the next time the conversation triggered correctly even though I repeated it as close as possible to the previous fight.
