### ISSUE TITLE
Manaan Ahto West Cantina - One of the bar booth had a gap issue

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#82]
One of the bar booth `(mesh) BarBoothP0` on Ahto West cantina `Model Name: M26aa_11a` had a gap issue.

Screenshot: 
![AWC_BarBoothP0](https://user-images.githubusercontent.com/50026566/56845776-8687d780-68f0-11e9-9473-05678bcef1d8.jpg)

**Comment by DarthParametric** [comment]
Took me a second to spot it, but I see now - the light surround on the righthand side.

Also looks like a lightmap issue on the panel to the lower left.

**Comment by ebmar** [comment]
>...looks like a lightmap issue on the panel to the lower left.

That wouldn't be the one with the issue then. The third booth from the entrance likely had the same problem.

**Comment by DarthParametric** [comment]
There are still gaps in the cantina booths. It might be best to black box the entire room, or at least the outer booth section.

**Comment by DarthParametric** [comment]
Added a black box to hopefully avoid light bleed from any remaining gaps. Also edited some lightmap UVs to remove the overly dark ceilings in two of the booths., and an incorrectly dark corner in one of them

![Manaan_Cantina_Booth_Issues](https://user-images.githubusercontent.com/46890653/57777536-7e8bbc80-7765-11e9-8762-25de049960cf.jpg)

**Comment by ebmar** [comment]
**_Awesome_**! Nice workaround with the `black box`, and hats-off for the lightmap UVs re-adjustments.
