### ISSUE TITLE
The male Twi'lek head has clipping issues with the upper teeth during some animations

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#84]
The outer edges of the upper teeth mesh clip through the cheeks during certain animations. Very noticeable on Zhar in the post-training montage conversation (especially if you have seen it a bunch of times in succession....).

Did someone already release a mod fixing this? I seem to recall something like that. Anyway, this is my own implementation.

**Comment by ebmar** [comment]
> Did someone already release a mod fixing this?

Apparently someone hasn't. `Ashton Scorpius` did some tweaking on [his mod](https://deadlystream.com/files/file/1430-k1-twilek-male-3d-ears/) but as quoted from the mod's page -
>...an additional adjustment by fixing the eyelid origins, so that they no longer clip through the face when blinking.

He didn't seem to touch the upper teeth mesh there.

**Comment by DarthParametric** [comment]
Yeah I know about the ear mod, but that's not it. I think I was thinking of a TSL mod. There was one recently that fixed some bones with activated render flags.

I didn't notice any issues with the eyelids. I guess I'll have to go back and take a closer look.
