### ISSUE TITLE
Droids in Davik's storage room can be gassed

### ISSUE THREAD

**Issue by JCarter426** [KOTORCommunityPatches/K1_Community_Patch#85]
Either Davik had invested in a startup company working on a prototype organic-droid hybrid, or these weren't meant to be droids. Mechanically, their race is human (thus prone to gas) and they have Rodian soundsets and vibroswords in their inventory.

**Comment by DarthParametric** [comment]
Ah, I wonder why they got destroyed by the gas. Although I am sure I have seen that in other modules as well.

There's at least one room that is only droids, so I suppose you could swap out the gas for a power conduit, although that seems like kind of a pain. What are the balance implications of switching them back to (actual) meatbags?

**Comment by JCarter426** [comment]
It shouldn't affect the gameplay at all, since mechanically they are humans who look like droids.

**Comment by DarthParametric** [comment]
Aside from weapons I guess. Although that is somewhat moot if you gas them either way.
