### ISSUE TITLE
The fat commoner model has some UV/texture issues

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#90]
The vanilla fat commoner model has some issues. A better option is to replace it with a modified version of the regular commoner model:

![Fat_Commoner_Male](https://user-images.githubusercontent.com/46890653/56950163-2b681600-6b78-11e9-9e1e-17210fea09fc.jpg)

It would be a straight override of the model, but appearance.2da would need some edits. There is only a single vanilla row (for male, another for female) that uses a player head. The texture references would need to be swapped for the regular commoner ones, and some new rows with different heads would ideally be added.

Here is Handon using the Tatooine commoner head:

![Fat_Commoner_Handon_01](https://user-images.githubusercontent.com/46890653/56953315-9ff28300-6b7f-11e9-97a8-1c541ddf2655.jpg)

![Fat_Commoner_Handon_02](https://user-images.githubusercontent.com/46890653/56953328-a8e35480-6b7f-11e9-9937-d8139cbaa9b8.jpg)

**Comment by Salk73** [comment]
DP,

is the female fat model ever used in the game? I'm trying to remember but I don't think I saw it anywhere.

**Comment by DarthParametric** [comment]
Not that I am aware of, no.

**Comment by Salk73** [comment]
From what you can see it could theoretically be used or do you think it might be unfinished/bugged?

I wouldn't mind introducing some variety in the game in that sense but I fear that the model is just not good enough (the male one is not that great to begin with).

**Comment by DarthParametric** [comment]
A cursory glance would suggest it is ok, although it only has a single texture variant. Like the male model it - for some unknown reason - uses different UVs than the regular commoner model. Although in this case it isn't anywhere near as divergent. It appears to just be the palms of the hands and the shoulders/upper arms that are the problem areas, so with a bit of UV massaging it could be made to use the normal commoner textures.
