### ISSUE TITLE
General - Rakghoul's inactive bumpmap

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#91]
Apparently, the Rakghouls `Model Name: C_Rakghoul` meant to have an active tangentspace/bumpmap with them; as seen with their texture information `C_Rakghoul01.tpc`:
```
bumpyshinytexture CM_SpecMap
bumpmaptexture C_Rakghoul01b
```
But far as the game does they doesn't look to have the model having an active tangentspace/bumpmap flag. Perhaps to _restore_ the developer intention should they'd be activated? I'd personally think it'd enhances the appearance of the Rakghouls.

Edit: it's weird - from the model looks like it had some of their ~~meshes~~ skins having an active tangentspace flag:
```
node skin RARm
  parent C_Rakghoul
  ...
  tangentspace 1
node skin Head
  parent C_Rakghoul
  ...
  tangentspace 1
```
But the game _and_ `MDLEdit` doesn't seem to recognize it.

**Comment by DarthParametric** [comment]
The danglymesh Hair is set as `tangentspace 0` despite sharing `C_Rakghoul01`. That is probably what causes MDLEdit to not show the texture as ticked, but I wouldn't have thought that would have any actual effect on the model in-game. I guess try enabling the tangentspace flag on that node and see what happens.

**Comment by ebmar** [comment]
> The danglymesh Hair is set as tangentspace 0... try enabling the tangentspace flag on that node...

Yeah, they does look similar; the vanilla and the `MDLedit` _ticked_ bumpmap flag. Can't say they look 100% the same because can't compare them in real-time. Interesting case. Safe to say that this issue has been resolved, I think.

**Comment by DarthParametric** [comment]
If you want to do further testing, you can swap out the normal map with a flat one. Here. try this:

[C_Rakghoul01b.zip](https://github.com/KOTORCommunityPatches/K1_Community_Patch/files/3144630/C_Rakghoul01b.zip)

**Comment by ebmar** [comment]
So, I guess the best way to solve this was to see what actually is `node danglymesh Hair` on a 3D program and yeah, it didn't look like it needs an active `tangentspace` flag with it, hahah. And about -
> ...swap out the normal map with a flat one

There's a definitive difference between the vanilla bumpmap with the attached flat one [obviously]. Can surely say that you're right about `MDLEdit to not show the texture as ticked` for this particular case. Could use the information for future [modding] references.

**Comment by DarthParametric** [comment]
Calling this another case of "Odyssey's normal mapping is so piss-weak it's worthless".
