### ISSUE TITLE
Taris Lower City Swoop Platform - Player runs around behind the race announcer's desk to initiate dialogue

### ISSUE THREAD

**Issue by DarthParametric** [KOTORCommunityPatches/K1_Community_Patch#92]
The player has some personal space issues. They can't initiate conversations unless they are right in someone's face. 

One solution would be to put a trigger in front of the desk and force the player into position.

**Comment by ebmar** [comment]
> ...put a trigger in front of the desk and force the player into position.

Can a trigger be put around the desk without it automatically fired? With a purpose that the player can initiate the convo from a distance further than it was, which in this case - from behind the desk.

Because some player -including me- I think, like to visit Bastila's cage and see things closer before initiating a race.

**Comment by DarthParametric** [comment]
You can do a check based on quest states or local booleans (e.g. have you talked to the guy yet). If you fire it once, put the player in the conversation, and they back out of it, then the only real option to prevent it continuously firing is to not fire it again until after the next race. Which means if you leave the convo and go peer at Bastila, you'd have to manually initiate the conversation. The only real other control is the physical size of the trigger. We can make it small enough that you have to get close to the desk, but you don't want it so small you can pretty much miss it completely - that would invalidate the entire reason for having it.

**Comment by ebmar** [comment]
Thanks for the details! So,

> Which means if you leave the convo and go peer at Bastila, you'd have to manually initiate the conversation.

That sounds good! I oversight the fact that the player can leave a convo and with the post initial one they can initiate it manually.

> The only real other control is the physical size of the trigger... don't want it so small you can pretty much miss it completely...

Yeah, I can see that. Good luck on nailing that!

**Comment by DarthParametric** [comment]
I don't think this is easily resolvable within the scope of K1CP. Given that a dialogue event isn't registered until the conversation actually begins, there's no way to intercept a player mid-traversal with a script, nor identify via a trigger that a player passing through intends to talk the announcer. I can see a possible solution with some walkmesh trickery perhaps, boxing the announcer in, but that potentially just introduces more problems.
