### ISSUE TITLE
Tatooine Docking Bay - Idle Docking Bay Mechanic

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#93]
On Tatooine Docking Bay `tat_m17ab` there's a Docking Bay Mechanic `tat17_01mech_01.utc` which gets paid for doing nothing, but once in a while keeps bluffing on doing some mech' stuff `tat17_01mech_01.dlg`:
> Leave me be. If I don't get these converters working, I lose my job.

Perhaps giving him an actual work around the bay will makes the place more lively? I'm thinking of him doing some kneeling-computer-fiddling animation [similar to what Sandcrawler Mechanic `tat17_05mecha_01.utc` does in front of the Anchorhead Czerka Office `tat_m17aa`] on this platform -
![Power_Converters_Props](https://user-images.githubusercontent.com/50026566/56971678-e0f49280-6b93-11e9-9b0f-4fc8cb3b7473.jpg)
That comes first on my mind when thinking about the `converters`.

**Comment by DarthParametric** [comment]
I think this is probably more suited to a standalone mod. There's no real issue with it as it is.

**Comment by ebmar** [comment]
Cool - and yeah, it's not breaking the game in any way, also the _misleading_ dialogue happened not so often. As you said, it more suited as a stand-alone mod kind of stuffs - which perhaps a more flexible implementation can act as an improvement; such as custom models for the `converters` and more.
