### ISSUE TITLE
Taris Lower Sewers - Sleeping Gamorrean Elite

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#95]
Well, it's not _that_ sleeping - it's just he was slow to react to incoming danger, lol. So, on Taris Lower Sewers `tar_m05aa` there's a Gamorrean Elite [either `tar04_gamelite0.utc` or `tar04_gamelite1.utc` - can't really sure which one] that is not going hostile despite his gangs went rampage to the party. Here's a clear illustration:
![Slow_to_React_Gamo_Elite](https://user-images.githubusercontent.com/50026566/57177963-e6075980-6e93-11e9-9ed1-b0b0d567f2b1.jpg)
It seem to me that to went hostile a creature must have sights to the [targeted] hostile[?]. Perhaps moving him to another position or changing the orientation could nullify this issue? Also I'm curious as if this is a local issue I have or anyone could regenerate this also.

Edit: also this is not the first time it happened - as with this `bug tracking` attempt I decided to report this issue to clarify this with the K1CP team.

**Comment by DarthParametric** [comment]
Don't recall having encountered this myself. The problem is AI, not faction (i.e., he's already hostile). The real question why he is shoved in a corner. If he is intended to stand idle and not patrol then he needs to be moved so he can perceive the party when the door opens.

**Comment by ebmar** [comment]
> ...the map showing the exact spot...

Roughly showing the exact spot:
![lbl_mapm05aa](https://user-images.githubusercontent.com/50026566/57179306-b877db80-6ea6-11e9-8ee9-e4fb68798389.jpg)
His current position is marked by the red dot. And also his current GIT positioning (~):
```
XOrientation: N/A
XPosition: 244.65500
YOrientation: N/A
YPosition: 180.53215
ZPosition: 29.85958
```

**Comment by DarthParametric** [comment]
How do you feel about save editing to test a fix?

```
Creature List\13\XPosition=245.623992919922
Creature List\13\YPosition=186.787994384766
Creature List\13\ZPosition=29.6620006561279
Creature List\13\XOrientation=-1
Creature List\13\YOrientation=1.22514845490862e-16
```

**Comment by ebmar** [comment]
> ...save editing to test a fix...

No probs - be back with an update.
