### ISSUE TITLE
Manaan Ahto West - Facing and camera angle issues on Sunry Murder Trial

### ISSUE THREAD

**Issue by ebmar** [KOTORCommunityPatches/K1_Community_Patch#96]
There are several facing and camera angle issues on Judge Shelkar's DLG `man26_seljud1.dlg` as part of `Sunry Murder Trial` side-quest that happened on Manaan Ahto West `manm26aa`; namely with some of Jolee's nodes. There're possibilities with other party members but I haven't produced them, except Juhani - I think she's looking OK as she wasn't very active on that event. If it's plausible I'd like to update this repo with new findings along with their fixes.

This is my first findings with their fixes [based on my preferences]:
```
[InstallList]
install_folderXYZ=modules

[GFFList]
FileXYZ=man26_seljud1.dlg

[man26_seljud1.dlg]
!Destination=modules\manm26aa.mod
EntryList\19\Listener=PLAYER
EntryList\19\CameraAngle=1
EntryList\22\CameraAngle=1

[install_folderXYZ]
FileXYZ=manm26aa.mod
```
Though that doesn't eliminate the facing issues, as Jolee seem to always facing the direction he was at _at_ the start of the dialogue.

**Comment by DarthParametric** [comment]
Jolee will likely need scripted facing commands to make him co-operate.

**Comment by DarthParametric** [comment]
Consider this rolled into #136.
